
namespace final_motoDix
{
    partial class frmRegisterClient
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmRegisterClient));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bflblCreateAccount1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bftxtFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSecondName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSurname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSecondSurname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxMobileNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxConfirmMobileNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bfbtnRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bflblCreateAccount2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.SuspendLayout();
            // 
            // bflblCreateAccount1
            // 
            this.bflblCreateAccount1.AllowParentOverrides = false;
            this.bflblCreateAccount1.AutoEllipsis = false;
            this.bflblCreateAccount1.AutoSize = false;
            this.bflblCreateAccount1.AutoSizeHeightOnly = true;
            this.bflblCreateAccount1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblCreateAccount1.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.bflblCreateAccount1.ForeColor = System.Drawing.Color.Black;
            this.bflblCreateAccount1.Location = new System.Drawing.Point(153, 29);
            this.bflblCreateAccount1.Name = "bflblCreateAccount1";
            this.bflblCreateAccount1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblCreateAccount1.Size = new System.Drawing.Size(107, 29);
            this.bflblCreateAccount1.TabIndex = 0;
            this.bflblCreateAccount1.Text = "Create a ";
            this.bflblCreateAccount1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bflblCreateAccount1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bflblCreateAccount1.Click += new System.EventHandler(this.bflblCreateAccount_Click);
            // 
            // bftxtFirstName
            // 
            this.bftxtFirstName.AcceptsReturn = false;
            this.bftxtFirstName.AcceptsTab = false;
            this.bftxtFirstName.AnimationSpeed = 200;
            this.bftxtFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtFirstName.AutoSizeHeight = true;
            this.bftxtFirstName.BackColor = System.Drawing.Color.Transparent;
            this.bftxtFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtFirstName.BackgroundImage")));
            this.bftxtFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtFirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtFirstName.BorderRadius = 1;
            this.bftxtFirstName.BorderThickness = 1;
            this.bftxtFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtFirstName.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtFirstName.DefaultText = "";
            this.bftxtFirstName.FillColor = System.Drawing.Color.White;
            this.bftxtFirstName.HideSelection = true;
            this.bftxtFirstName.IconLeft = null;
            this.bftxtFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtFirstName.IconPadding = 10;
            this.bftxtFirstName.IconRight = null;
            this.bftxtFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtFirstName.Lines = new string[0];
            this.bftxtFirstName.Location = new System.Drawing.Point(47, 92);
            this.bftxtFirstName.MaxLength = 32767;
            this.bftxtFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtFirstName.Modified = false;
            this.bftxtFirstName.Multiline = false;
            this.bftxtFirstName.Name = "bftxtFirstName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtFirstName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtFirstName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtFirstName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtFirstName.OnIdleState = stateProperties4;
            this.bftxtFirstName.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtFirstName.PasswordChar = '\0';
            this.bftxtFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtFirstName.PlaceholderText = "First name";
            this.bftxtFirstName.ReadOnly = false;
            this.bftxtFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtFirstName.SelectedText = "";
            this.bftxtFirstName.SelectionLength = 0;
            this.bftxtFirstName.SelectionStart = 0;
            this.bftxtFirstName.ShortcutsEnabled = true;
            this.bftxtFirstName.Size = new System.Drawing.Size(193, 37);
            this.bftxtFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtFirstName.TabIndex = 1;
            this.bftxtFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtFirstName.TextMarginBottom = 0;
            this.bftxtFirstName.TextMarginLeft = 3;
            this.bftxtFirstName.TextMarginTop = 1;
            this.bftxtFirstName.TextPlaceholder = "First name";
            this.bftxtFirstName.UseSystemPasswordChar = false;
            this.bftxtFirstName.WordWrap = true;
            // 
            // bftxtSecondName
            // 
            this.bftxtSecondName.AcceptsReturn = false;
            this.bftxtSecondName.AcceptsTab = false;
            this.bftxtSecondName.AnimationSpeed = 200;
            this.bftxtSecondName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSecondName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSecondName.AutoSizeHeight = true;
            this.bftxtSecondName.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSecondName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSecondName.BackgroundImage")));
            this.bftxtSecondName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSecondName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSecondName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSecondName.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSecondName.BorderRadius = 1;
            this.bftxtSecondName.BorderThickness = 1;
            this.bftxtSecondName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSecondName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondName.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSecondName.DefaultText = "";
            this.bftxtSecondName.FillColor = System.Drawing.Color.White;
            this.bftxtSecondName.HideSelection = true;
            this.bftxtSecondName.IconLeft = null;
            this.bftxtSecondName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondName.IconPadding = 10;
            this.bftxtSecondName.IconRight = null;
            this.bftxtSecondName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondName.Lines = new string[0];
            this.bftxtSecondName.Location = new System.Drawing.Point(293, 92);
            this.bftxtSecondName.MaxLength = 32767;
            this.bftxtSecondName.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSecondName.Modified = false;
            this.bftxtSecondName.Multiline = false;
            this.bftxtSecondName.Name = "bftxtSecondName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSecondName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondName.OnIdleState = stateProperties8;
            this.bftxtSecondName.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSecondName.PasswordChar = '\0';
            this.bftxtSecondName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSecondName.PlaceholderText = "Second name";
            this.bftxtSecondName.ReadOnly = false;
            this.bftxtSecondName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSecondName.SelectedText = "";
            this.bftxtSecondName.SelectionLength = 0;
            this.bftxtSecondName.SelectionStart = 0;
            this.bftxtSecondName.ShortcutsEnabled = true;
            this.bftxtSecondName.Size = new System.Drawing.Size(193, 37);
            this.bftxtSecondName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSecondName.TabIndex = 2;
            this.bftxtSecondName.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSecondName.TextMarginBottom = 0;
            this.bftxtSecondName.TextMarginLeft = 3;
            this.bftxtSecondName.TextMarginTop = 1;
            this.bftxtSecondName.TextPlaceholder = "Second name";
            this.bftxtSecondName.UseSystemPasswordChar = false;
            this.bftxtSecondName.WordWrap = true;
            // 
            // bftxtSurname
            // 
            this.bftxtSurname.AcceptsReturn = false;
            this.bftxtSurname.AcceptsTab = false;
            this.bftxtSurname.AnimationSpeed = 200;
            this.bftxtSurname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSurname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSurname.AutoSizeHeight = true;
            this.bftxtSurname.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSurname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSurname.BackgroundImage")));
            this.bftxtSurname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSurname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSurname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSurname.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSurname.BorderRadius = 1;
            this.bftxtSurname.BorderThickness = 1;
            this.bftxtSurname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSurname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSurname.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSurname.DefaultText = "";
            this.bftxtSurname.FillColor = System.Drawing.Color.White;
            this.bftxtSurname.HideSelection = true;
            this.bftxtSurname.IconLeft = null;
            this.bftxtSurname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSurname.IconPadding = 10;
            this.bftxtSurname.IconRight = null;
            this.bftxtSurname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSurname.Lines = new string[0];
            this.bftxtSurname.Location = new System.Drawing.Point(47, 156);
            this.bftxtSurname.MaxLength = 32767;
            this.bftxtSurname.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSurname.Modified = false;
            this.bftxtSurname.Multiline = false;
            this.bftxtSurname.Name = "bftxtSurname";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSurname.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSurname.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSurname.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSurname.OnIdleState = stateProperties12;
            this.bftxtSurname.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSurname.PasswordChar = '\0';
            this.bftxtSurname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSurname.PlaceholderText = "Surname";
            this.bftxtSurname.ReadOnly = false;
            this.bftxtSurname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSurname.SelectedText = "";
            this.bftxtSurname.SelectionLength = 0;
            this.bftxtSurname.SelectionStart = 0;
            this.bftxtSurname.ShortcutsEnabled = true;
            this.bftxtSurname.Size = new System.Drawing.Size(193, 37);
            this.bftxtSurname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSurname.TabIndex = 3;
            this.bftxtSurname.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSurname.TextMarginBottom = 0;
            this.bftxtSurname.TextMarginLeft = 3;
            this.bftxtSurname.TextMarginTop = 1;
            this.bftxtSurname.TextPlaceholder = "Surname";
            this.bftxtSurname.UseSystemPasswordChar = false;
            this.bftxtSurname.WordWrap = true;
            // 
            // bftxtSecondSurname
            // 
            this.bftxtSecondSurname.AcceptsReturn = false;
            this.bftxtSecondSurname.AcceptsTab = false;
            this.bftxtSecondSurname.AnimationSpeed = 200;
            this.bftxtSecondSurname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSecondSurname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSecondSurname.AutoSizeHeight = true;
            this.bftxtSecondSurname.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSecondSurname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSecondSurname.BackgroundImage")));
            this.bftxtSecondSurname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSecondSurname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSecondSurname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSecondSurname.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSecondSurname.BorderRadius = 1;
            this.bftxtSecondSurname.BorderThickness = 1;
            this.bftxtSecondSurname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSecondSurname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondSurname.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSecondSurname.DefaultText = "";
            this.bftxtSecondSurname.FillColor = System.Drawing.Color.White;
            this.bftxtSecondSurname.HideSelection = true;
            this.bftxtSecondSurname.IconLeft = null;
            this.bftxtSecondSurname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondSurname.IconPadding = 10;
            this.bftxtSecondSurname.IconRight = null;
            this.bftxtSecondSurname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSecondSurname.Lines = new string[0];
            this.bftxtSecondSurname.Location = new System.Drawing.Point(293, 156);
            this.bftxtSecondSurname.MaxLength = 32767;
            this.bftxtSecondSurname.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSecondSurname.Modified = false;
            this.bftxtSecondSurname.Multiline = false;
            this.bftxtSecondSurname.Name = "bftxtSecondSurname";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondSurname.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSecondSurname.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondSurname.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSecondSurname.OnIdleState = stateProperties16;
            this.bftxtSecondSurname.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSecondSurname.PasswordChar = '\0';
            this.bftxtSecondSurname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSecondSurname.PlaceholderText = "Second Surname";
            this.bftxtSecondSurname.ReadOnly = false;
            this.bftxtSecondSurname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSecondSurname.SelectedText = "";
            this.bftxtSecondSurname.SelectionLength = 0;
            this.bftxtSecondSurname.SelectionStart = 0;
            this.bftxtSecondSurname.ShortcutsEnabled = true;
            this.bftxtSecondSurname.Size = new System.Drawing.Size(193, 37);
            this.bftxtSecondSurname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSecondSurname.TabIndex = 4;
            this.bftxtSecondSurname.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSecondSurname.TextMarginBottom = 0;
            this.bftxtSecondSurname.TextMarginLeft = 3;
            this.bftxtSecondSurname.TextMarginTop = 1;
            this.bftxtSecondSurname.TextPlaceholder = "Second Surname";
            this.bftxtSecondSurname.UseSystemPasswordChar = false;
            this.bftxtSecondSurname.WordWrap = true;
            // 
            // bftxtxEmail
            // 
            this.bftxtxEmail.AcceptsReturn = false;
            this.bftxtxEmail.AcceptsTab = false;
            this.bftxtxEmail.AnimationSpeed = 200;
            this.bftxtxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxEmail.AutoSizeHeight = true;
            this.bftxtxEmail.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxEmail.BackgroundImage")));
            this.bftxtxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxEmail.BorderRadius = 1;
            this.bftxtxEmail.BorderThickness = 1;
            this.bftxtxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxEmail.DefaultText = "";
            this.bftxtxEmail.FillColor = System.Drawing.Color.White;
            this.bftxtxEmail.HideSelection = true;
            this.bftxtxEmail.IconLeft = null;
            this.bftxtxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.IconPadding = 10;
            this.bftxtxEmail.IconRight = null;
            this.bftxtxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.Lines = new string[0];
            this.bftxtxEmail.Location = new System.Drawing.Point(47, 225);
            this.bftxtxEmail.MaxLength = 32767;
            this.bftxtxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxEmail.Modified = false;
            this.bftxtxEmail.Multiline = false;
            this.bftxtxEmail.Name = "bftxtxEmail";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxEmail.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnIdleState = stateProperties20;
            this.bftxtxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxEmail.PasswordChar = '\0';
            this.bftxtxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxEmail.PlaceholderText = "E-mail";
            this.bftxtxEmail.ReadOnly = false;
            this.bftxtxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxEmail.SelectedText = "";
            this.bftxtxEmail.SelectionLength = 0;
            this.bftxtxEmail.SelectionStart = 0;
            this.bftxtxEmail.ShortcutsEnabled = true;
            this.bftxtxEmail.Size = new System.Drawing.Size(193, 37);
            this.bftxtxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxEmail.TabIndex = 5;
            this.bftxtxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxEmail.TextMarginBottom = 0;
            this.bftxtxEmail.TextMarginLeft = 3;
            this.bftxtxEmail.TextMarginTop = 1;
            this.bftxtxEmail.TextPlaceholder = "E-mail";
            this.bftxtxEmail.UseSystemPasswordChar = false;
            this.bftxtxEmail.WordWrap = true;
            // 
            // bftxtConfirmEmail
            // 
            this.bftxtConfirmEmail.AcceptsReturn = false;
            this.bftxtConfirmEmail.AcceptsTab = false;
            this.bftxtConfirmEmail.AnimationSpeed = 200;
            this.bftxtConfirmEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmEmail.AutoSizeHeight = true;
            this.bftxtConfirmEmail.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmEmail.BackgroundImage")));
            this.bftxtConfirmEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmEmail.BorderRadius = 1;
            this.bftxtConfirmEmail.BorderThickness = 1;
            this.bftxtConfirmEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmEmail.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmEmail.DefaultText = "";
            this.bftxtConfirmEmail.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmEmail.HideSelection = true;
            this.bftxtConfirmEmail.IconLeft = null;
            this.bftxtConfirmEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmEmail.IconPadding = 10;
            this.bftxtConfirmEmail.IconRight = null;
            this.bftxtConfirmEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmEmail.Lines = new string[0];
            this.bftxtConfirmEmail.Location = new System.Drawing.Point(293, 225);
            this.bftxtConfirmEmail.MaxLength = 32767;
            this.bftxtConfirmEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmEmail.Modified = false;
            this.bftxtConfirmEmail.Multiline = false;
            this.bftxtConfirmEmail.Name = "bftxtConfirmEmail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmEmail.OnIdleState = stateProperties24;
            this.bftxtConfirmEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmEmail.PasswordChar = '\0';
            this.bftxtConfirmEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmEmail.PlaceholderText = "Confirm e-mail";
            this.bftxtConfirmEmail.ReadOnly = false;
            this.bftxtConfirmEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmEmail.SelectedText = "";
            this.bftxtConfirmEmail.SelectionLength = 0;
            this.bftxtConfirmEmail.SelectionStart = 0;
            this.bftxtConfirmEmail.ShortcutsEnabled = true;
            this.bftxtConfirmEmail.Size = new System.Drawing.Size(193, 37);
            this.bftxtConfirmEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmEmail.TabIndex = 6;
            this.bftxtConfirmEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmEmail.TextMarginBottom = 0;
            this.bftxtConfirmEmail.TextMarginLeft = 3;
            this.bftxtConfirmEmail.TextMarginTop = 1;
            this.bftxtConfirmEmail.TextPlaceholder = "Confirm e-mail";
            this.bftxtConfirmEmail.UseSystemPasswordChar = false;
            this.bftxtConfirmEmail.WordWrap = true;
            // 
            // bftxtxMobileNumber
            // 
            this.bftxtxMobileNumber.AcceptsReturn = false;
            this.bftxtxMobileNumber.AcceptsTab = false;
            this.bftxtxMobileNumber.AnimationSpeed = 200;
            this.bftxtxMobileNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxMobileNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxMobileNumber.AutoSizeHeight = true;
            this.bftxtxMobileNumber.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxMobileNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxMobileNumber.BackgroundImage")));
            this.bftxtxMobileNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxMobileNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxMobileNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxMobileNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxMobileNumber.BorderRadius = 1;
            this.bftxtxMobileNumber.BorderThickness = 1;
            this.bftxtxMobileNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxMobileNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxMobileNumber.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxMobileNumber.DefaultText = "";
            this.bftxtxMobileNumber.FillColor = System.Drawing.Color.White;
            this.bftxtxMobileNumber.HideSelection = true;
            this.bftxtxMobileNumber.IconLeft = null;
            this.bftxtxMobileNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxMobileNumber.IconPadding = 10;
            this.bftxtxMobileNumber.IconRight = null;
            this.bftxtxMobileNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxMobileNumber.Lines = new string[0];
            this.bftxtxMobileNumber.Location = new System.Drawing.Point(47, 289);
            this.bftxtxMobileNumber.MaxLength = 32767;
            this.bftxtxMobileNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxMobileNumber.Modified = false;
            this.bftxtxMobileNumber.Multiline = false;
            this.bftxtxMobileNumber.Name = "bftxtxMobileNumber";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxMobileNumber.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxMobileNumber.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxMobileNumber.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxMobileNumber.OnIdleState = stateProperties28;
            this.bftxtxMobileNumber.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxMobileNumber.PasswordChar = '\0';
            this.bftxtxMobileNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxMobileNumber.PlaceholderText = "Mobile number";
            this.bftxtxMobileNumber.ReadOnly = false;
            this.bftxtxMobileNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxMobileNumber.SelectedText = "";
            this.bftxtxMobileNumber.SelectionLength = 0;
            this.bftxtxMobileNumber.SelectionStart = 0;
            this.bftxtxMobileNumber.ShortcutsEnabled = true;
            this.bftxtxMobileNumber.Size = new System.Drawing.Size(193, 37);
            this.bftxtxMobileNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxMobileNumber.TabIndex = 7;
            this.bftxtxMobileNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxMobileNumber.TextMarginBottom = 0;
            this.bftxtxMobileNumber.TextMarginLeft = 3;
            this.bftxtxMobileNumber.TextMarginTop = 1;
            this.bftxtxMobileNumber.TextPlaceholder = "Mobile number";
            this.bftxtxMobileNumber.UseSystemPasswordChar = false;
            this.bftxtxMobileNumber.WordWrap = true;
            // 
            // bftxtxConfirmMobileNumber
            // 
            this.bftxtxConfirmMobileNumber.AcceptsReturn = false;
            this.bftxtxConfirmMobileNumber.AcceptsTab = false;
            this.bftxtxConfirmMobileNumber.AnimationSpeed = 200;
            this.bftxtxConfirmMobileNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxConfirmMobileNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxConfirmMobileNumber.AutoSizeHeight = true;
            this.bftxtxConfirmMobileNumber.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxConfirmMobileNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxConfirmMobileNumber.BackgroundImage")));
            this.bftxtxConfirmMobileNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxConfirmMobileNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxConfirmMobileNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxConfirmMobileNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxConfirmMobileNumber.BorderRadius = 1;
            this.bftxtxConfirmMobileNumber.BorderThickness = 1;
            this.bftxtxConfirmMobileNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxConfirmMobileNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxConfirmMobileNumber.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxConfirmMobileNumber.DefaultText = "";
            this.bftxtxConfirmMobileNumber.FillColor = System.Drawing.Color.White;
            this.bftxtxConfirmMobileNumber.HideSelection = true;
            this.bftxtxConfirmMobileNumber.IconLeft = null;
            this.bftxtxConfirmMobileNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxConfirmMobileNumber.IconPadding = 10;
            this.bftxtxConfirmMobileNumber.IconRight = null;
            this.bftxtxConfirmMobileNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxConfirmMobileNumber.Lines = new string[0];
            this.bftxtxConfirmMobileNumber.Location = new System.Drawing.Point(293, 289);
            this.bftxtxConfirmMobileNumber.MaxLength = 32767;
            this.bftxtxConfirmMobileNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxConfirmMobileNumber.Modified = false;
            this.bftxtxConfirmMobileNumber.Multiline = false;
            this.bftxtxConfirmMobileNumber.Name = "bftxtxConfirmMobileNumber";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxConfirmMobileNumber.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxConfirmMobileNumber.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxConfirmMobileNumber.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxConfirmMobileNumber.OnIdleState = stateProperties32;
            this.bftxtxConfirmMobileNumber.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxConfirmMobileNumber.PasswordChar = '\0';
            this.bftxtxConfirmMobileNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxConfirmMobileNumber.PlaceholderText = "Confirm Mobile number";
            this.bftxtxConfirmMobileNumber.ReadOnly = false;
            this.bftxtxConfirmMobileNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxConfirmMobileNumber.SelectedText = "";
            this.bftxtxConfirmMobileNumber.SelectionLength = 0;
            this.bftxtxConfirmMobileNumber.SelectionStart = 0;
            this.bftxtxConfirmMobileNumber.ShortcutsEnabled = true;
            this.bftxtxConfirmMobileNumber.Size = new System.Drawing.Size(193, 37);
            this.bftxtxConfirmMobileNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxConfirmMobileNumber.TabIndex = 8;
            this.bftxtxConfirmMobileNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxConfirmMobileNumber.TextMarginBottom = 0;
            this.bftxtxConfirmMobileNumber.TextMarginLeft = 3;
            this.bftxtxConfirmMobileNumber.TextMarginTop = 1;
            this.bftxtxConfirmMobileNumber.TextPlaceholder = "Confirm Mobile number";
            this.bftxtxConfirmMobileNumber.UseSystemPasswordChar = false;
            this.bftxtxConfirmMobileNumber.WordWrap = true;
            // 
            // bftxtPassword
            // 
            this.bftxtPassword.AcceptsReturn = false;
            this.bftxtPassword.AcceptsTab = false;
            this.bftxtPassword.AnimationSpeed = 200;
            this.bftxtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPassword.AutoSizeHeight = true;
            this.bftxtPassword.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPassword.BackgroundImage")));
            this.bftxtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPassword.BorderRadius = 1;
            this.bftxtPassword.BorderThickness = 1;
            this.bftxtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPassword.DefaultText = "";
            this.bftxtPassword.FillColor = System.Drawing.Color.White;
            this.bftxtPassword.HideSelection = true;
            this.bftxtPassword.IconLeft = null;
            this.bftxtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.IconPadding = 10;
            this.bftxtPassword.IconRight = null;
            this.bftxtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.Lines = new string[0];
            this.bftxtPassword.Location = new System.Drawing.Point(47, 359);
            this.bftxtPassword.MaxLength = 32767;
            this.bftxtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPassword.Modified = false;
            this.bftxtPassword.Multiline = false;
            this.bftxtPassword.Name = "bftxtPassword";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPassword.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnIdleState = stateProperties36;
            this.bftxtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPassword.PasswordChar = '\0';
            this.bftxtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPassword.PlaceholderText = "Passsword";
            this.bftxtPassword.ReadOnly = false;
            this.bftxtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPassword.SelectedText = "";
            this.bftxtPassword.SelectionLength = 0;
            this.bftxtPassword.SelectionStart = 0;
            this.bftxtPassword.ShortcutsEnabled = true;
            this.bftxtPassword.Size = new System.Drawing.Size(193, 37);
            this.bftxtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPassword.TabIndex = 9;
            this.bftxtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPassword.TextMarginBottom = 0;
            this.bftxtPassword.TextMarginLeft = 3;
            this.bftxtPassword.TextMarginTop = 1;
            this.bftxtPassword.TextPlaceholder = "Passsword";
            this.bftxtPassword.UseSystemPasswordChar = false;
            this.bftxtPassword.WordWrap = true;
            // 
            // bftxtConfirmPassword
            // 
            this.bftxtConfirmPassword.AcceptsReturn = false;
            this.bftxtConfirmPassword.AcceptsTab = false;
            this.bftxtConfirmPassword.AnimationSpeed = 200;
            this.bftxtConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmPassword.AutoSizeHeight = true;
            this.bftxtConfirmPassword.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmPassword.BackgroundImage")));
            this.bftxtConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmPassword.BorderRadius = 1;
            this.bftxtConfirmPassword.BorderThickness = 1;
            this.bftxtConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmPassword.DefaultText = "";
            this.bftxtConfirmPassword.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmPassword.HideSelection = true;
            this.bftxtConfirmPassword.IconLeft = null;
            this.bftxtConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.IconPadding = 10;
            this.bftxtConfirmPassword.IconRight = null;
            this.bftxtConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.Lines = new string[0];
            this.bftxtConfirmPassword.Location = new System.Drawing.Point(293, 359);
            this.bftxtConfirmPassword.MaxLength = 32767;
            this.bftxtConfirmPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmPassword.Modified = false;
            this.bftxtConfirmPassword.Multiline = false;
            this.bftxtConfirmPassword.Name = "bftxtConfirmPassword";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmPassword.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnIdleState = stateProperties40;
            this.bftxtConfirmPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmPassword.PasswordChar = '\0';
            this.bftxtConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmPassword.PlaceholderText = "Confirm Passsword";
            this.bftxtConfirmPassword.ReadOnly = false;
            this.bftxtConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmPassword.SelectedText = "";
            this.bftxtConfirmPassword.SelectionLength = 0;
            this.bftxtConfirmPassword.SelectionStart = 0;
            this.bftxtConfirmPassword.ShortcutsEnabled = true;
            this.bftxtConfirmPassword.Size = new System.Drawing.Size(193, 37);
            this.bftxtConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmPassword.TabIndex = 10;
            this.bftxtConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmPassword.TextMarginBottom = 0;
            this.bftxtConfirmPassword.TextMarginLeft = 3;
            this.bftxtConfirmPassword.TextMarginTop = 1;
            this.bftxtConfirmPassword.TextPlaceholder = "Confirm Passsword";
            this.bftxtConfirmPassword.UseSystemPasswordChar = false;
            this.bftxtConfirmPassword.WordWrap = true;
            this.bftxtConfirmPassword.TextChanged += new System.EventHandler(this.bftxtConfirmPassword_TextChanged);
            // 
            // bfbtnRegister
            // 
            this.bfbtnRegister.AllowAnimations = true;
            this.bfbtnRegister.AllowMouseEffects = true;
            this.bfbtnRegister.AllowToggling = false;
            this.bfbtnRegister.AnimationSpeed = 200;
            this.bfbtnRegister.AutoGenerateColors = false;
            this.bfbtnRegister.AutoRoundBorders = false;
            this.bfbtnRegister.AutoSizeLeftIcon = true;
            this.bfbtnRegister.AutoSizeRightIcon = true;
            this.bfbtnRegister.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnRegister.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bfbtnRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnRegister.BackgroundImage")));
            this.bfbtnRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnRegister.ButtonText = "Register";
            this.bfbtnRegister.ButtonTextMarginLeft = 0;
            this.bfbtnRegister.ColorContrastOnClick = 45;
            this.bfbtnRegister.ColorContrastOnHover = 45;
            this.bfbtnRegister.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bfbtnRegister.CustomizableEdges = borderEdges1;
            this.bfbtnRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnRegister.DisabledFillColor = System.Drawing.Color.Empty;
            this.bfbtnRegister.DisabledForecolor = System.Drawing.Color.Empty;
            this.bfbtnRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bfbtnRegister.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bfbtnRegister.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegister.IconLeft = null;
            this.bfbtnRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnRegister.IconMarginLeft = 11;
            this.bfbtnRegister.IconPadding = 10;
            this.bfbtnRegister.IconRight = null;
            this.bfbtnRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnRegister.IconSize = 25;
            this.bfbtnRegister.IdleBorderColor = System.Drawing.Color.Empty;
            this.bfbtnRegister.IdleBorderRadius = 0;
            this.bfbtnRegister.IdleBorderThickness = 0;
            this.bfbtnRegister.IdleFillColor = System.Drawing.Color.Empty;
            this.bfbtnRegister.IdleIconLeftImage = null;
            this.bfbtnRegister.IdleIconRightImage = null;
            this.bfbtnRegister.IndicateFocus = false;
            this.bfbtnRegister.Location = new System.Drawing.Point(166, 425);
            this.bfbtnRegister.Margin = new System.Windows.Forms.Padding(4);
            this.bfbtnRegister.Name = "bfbtnRegister";
            this.bfbtnRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnRegister.OnDisabledState.BorderRadius = 1;
            this.bfbtnRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnRegister.OnDisabledState.BorderThickness = 1;
            this.bfbtnRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnRegister.OnDisabledState.IconLeftImage = null;
            this.bfbtnRegister.OnDisabledState.IconRightImage = null;
            this.bfbtnRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bfbtnRegister.onHoverState.BorderRadius = 1;
            this.bfbtnRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnRegister.onHoverState.BorderThickness = 1;
            this.bfbtnRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bfbtnRegister.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegister.onHoverState.IconLeftImage = null;
            this.bfbtnRegister.onHoverState.IconRightImage = null;
            this.bfbtnRegister.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnRegister.OnIdleState.BorderRadius = 1;
            this.bfbtnRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnRegister.OnIdleState.BorderThickness = 1;
            this.bfbtnRegister.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnRegister.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegister.OnIdleState.IconLeftImage = null;
            this.bfbtnRegister.OnIdleState.IconRightImage = null;
            this.bfbtnRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnRegister.OnPressedState.BorderRadius = 1;
            this.bfbtnRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnRegister.OnPressedState.BorderThickness = 1;
            this.bfbtnRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnRegister.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegister.OnPressedState.IconLeftImage = null;
            this.bfbtnRegister.OnPressedState.IconRightImage = null;
            this.bfbtnRegister.Size = new System.Drawing.Size(192, 29);
            this.bfbtnRegister.TabIndex = 11;
            this.bfbtnRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnRegister.TextMarginLeft = 0;
            this.bfbtnRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnRegister.UseDefaultRadiusAndThickness = true;
            // 
            // bflblCreateAccount2
            // 
            this.bflblCreateAccount2.AllowParentOverrides = false;
            this.bflblCreateAccount2.AutoEllipsis = false;
            this.bflblCreateAccount2.AutoSize = false;
            this.bflblCreateAccount2.AutoSizeHeightOnly = true;
            this.bflblCreateAccount2.CursorType = null;
            this.bflblCreateAccount2.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.bflblCreateAccount2.ForeColor = System.Drawing.Color.White;
            this.bflblCreateAccount2.Location = new System.Drawing.Point(266, 29);
            this.bflblCreateAccount2.Name = "bflblCreateAccount2";
            this.bflblCreateAccount2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblCreateAccount2.Size = new System.Drawing.Size(149, 29);
            this.bflblCreateAccount2.TabIndex = 12;
            this.bflblCreateAccount2.Text = "new account";
            this.bflblCreateAccount2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bflblCreateAccount2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmRegisterClient
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.ClientSize = new System.Drawing.Size(534, 510);
            this.Controls.Add(this.bflblCreateAccount2);
            this.Controls.Add(this.bfbtnRegister);
            this.Controls.Add(this.bftxtConfirmPassword);
            this.Controls.Add(this.bftxtPassword);
            this.Controls.Add(this.bftxtxConfirmMobileNumber);
            this.Controls.Add(this.bftxtxMobileNumber);
            this.Controls.Add(this.bftxtConfirmEmail);
            this.Controls.Add(this.bftxtxEmail);
            this.Controls.Add(this.bftxtSecondSurname);
            this.Controls.Add(this.bftxtSurname);
            this.Controls.Add(this.bftxtSecondName);
            this.Controls.Add(this.bflblCreateAccount1);
            this.Controls.Add(this.bftxtFirstName);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRegisterClient";
            this.Text = "frmRegister";
            this.Load += new System.EventHandler(this.frmRegister_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bflblCreateAccount1;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtFirstName;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSecondName;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSurname;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSecondSurname;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxEmail;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmEmail;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxMobileNumber;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxConfirmMobileNumber;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bfbtnRegister;
        private Bunifu.UI.WinForms.BunifuLabel bflblCreateAccount2;
    }
}