
namespace final_motoDix.Vistas
{
    partial class frmHome
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmHome));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panelVertical = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bfbtnCerrarSesion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bfbtnSolicitudesCondutor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bfbtnDetallesViaje = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bfpbImagenPerfil = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bflblNombreUsuario = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblTipoUsuario = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bfbtnMisViajes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bfbtnViajar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bfbtnTrabajaConNosotros = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.panelContenedor = new System.Windows.Forms.Panel();
            this.panelHeader = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.ptbMaximizar = new System.Windows.Forms.PictureBox();
            this.ptbCerrar = new System.Windows.Forms.PictureBox();
            this.ptbMinizar = new System.Windows.Forms.PictureBox();
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.bfbtnCrearAdministrador = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.bfSnackbarHome = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.panelVertical.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bfpbImagenPerfil)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.panelContenedor.SuspendLayout();
            this.panelHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ptbMaximizar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbCerrar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbMinizar)).BeginInit();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelVertical
            // 
            this.panelVertical.BackColor = System.Drawing.Color.Transparent;
            this.panelVertical.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelVertical.BackgroundImage")));
            this.panelVertical.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelVertical.BorderRadius = 1;
            this.panelVertical.Controls.Add(this.flowLayoutPanel1);
            this.panelVertical.Controls.Add(this.panel1);
            this.panelVertical.Controls.Add(this.bfbtnCerrarSesion);
            this.panelVertical.Controls.Add(this.bunifuButton21);
            this.panelVertical.Controls.Add(this.bfbtnTrabajaConNosotros);
            this.panelVertical.Cursor = System.Windows.Forms.Cursors.Default;
            this.panelVertical.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelVertical.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelVertical.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelVertical.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelVertical.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelVertical.Location = new System.Drawing.Point(0, 0);
            this.panelVertical.Margin = new System.Windows.Forms.Padding(2);
            this.panelVertical.Name = "panelVertical";
            this.panelVertical.Quality = 10;
            this.panelVertical.Size = new System.Drawing.Size(218, 742);
            this.panelVertical.TabIndex = 0;
            // 
            // bfbtnCerrarSesion
            // 
            this.bfbtnCerrarSesion.AllowAnimations = true;
            this.bfbtnCerrarSesion.AllowMouseEffects = true;
            this.bfbtnCerrarSesion.AllowToggling = false;
            this.bfbtnCerrarSesion.AnimationSpeed = 200;
            this.bfbtnCerrarSesion.AutoGenerateColors = false;
            this.bfbtnCerrarSesion.AutoRoundBorders = false;
            this.bfbtnCerrarSesion.AutoSizeLeftIcon = true;
            this.bfbtnCerrarSesion.AutoSizeRightIcon = true;
            this.bfbtnCerrarSesion.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnCerrarSesion.BackgroundImage")));
            this.bfbtnCerrarSesion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCerrarSesion.ButtonText = "Cerrar sesión.";
            this.bfbtnCerrarSesion.ButtonTextMarginLeft = 0;
            this.bfbtnCerrarSesion.ColorContrastOnClick = 45;
            this.bfbtnCerrarSesion.ColorContrastOnHover = 45;
            this.bfbtnCerrarSesion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bfbtnCerrarSesion.CustomizableEdges = borderEdges6;
            this.bfbtnCerrarSesion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnCerrarSesion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnCerrarSesion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnCerrarSesion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnCerrarSesion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnCerrarSesion.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bfbtnCerrarSesion.ForeColor = System.Drawing.Color.Red;
            this.bfbtnCerrarSesion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnCerrarSesion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnCerrarSesion.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnCerrarSesion.IconMarginLeft = 11;
            this.bfbtnCerrarSesion.IconPadding = 10;
            this.bfbtnCerrarSesion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnCerrarSesion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnCerrarSesion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnCerrarSesion.IconSize = 25;
            this.bfbtnCerrarSesion.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.IdleBorderRadius = 1;
            this.bfbtnCerrarSesion.IdleBorderThickness = 1;
            this.bfbtnCerrarSesion.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.IdleIconLeftImage = null;
            this.bfbtnCerrarSesion.IdleIconRightImage = null;
            this.bfbtnCerrarSesion.IndicateFocus = false;
            this.bfbtnCerrarSesion.Location = new System.Drawing.Point(3, 692);
            this.bfbtnCerrarSesion.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnCerrarSesion.Name = "bfbtnCerrarSesion";
            this.bfbtnCerrarSesion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnCerrarSesion.OnDisabledState.BorderRadius = 1;
            this.bfbtnCerrarSesion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCerrarSesion.OnDisabledState.BorderThickness = 1;
            this.bfbtnCerrarSesion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnCerrarSesion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnCerrarSesion.OnDisabledState.IconLeftImage = null;
            this.bfbtnCerrarSesion.OnDisabledState.IconRightImage = null;
            this.bfbtnCerrarSesion.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnCerrarSesion.onHoverState.BorderRadius = 1;
            this.bfbtnCerrarSesion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCerrarSesion.onHoverState.BorderThickness = 1;
            this.bfbtnCerrarSesion.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnCerrarSesion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnCerrarSesion.onHoverState.IconLeftImage = null;
            this.bfbtnCerrarSesion.onHoverState.IconRightImage = null;
            this.bfbtnCerrarSesion.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.OnIdleState.BorderRadius = 1;
            this.bfbtnCerrarSesion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCerrarSesion.OnIdleState.BorderThickness = 1;
            this.bfbtnCerrarSesion.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnCerrarSesion.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.bfbtnCerrarSesion.OnIdleState.IconLeftImage = null;
            this.bfbtnCerrarSesion.OnIdleState.IconRightImage = null;
            this.bfbtnCerrarSesion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnCerrarSesion.OnPressedState.BorderRadius = 1;
            this.bfbtnCerrarSesion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCerrarSesion.OnPressedState.BorderThickness = 1;
            this.bfbtnCerrarSesion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnCerrarSesion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnCerrarSesion.OnPressedState.IconLeftImage = null;
            this.bfbtnCerrarSesion.OnPressedState.IconRightImage = null;
            this.bfbtnCerrarSesion.Size = new System.Drawing.Size(208, 39);
            this.bfbtnCerrarSesion.TabIndex = 9;
            this.bfbtnCerrarSesion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnCerrarSesion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnCerrarSesion.TextMarginLeft = 0;
            this.bfbtnCerrarSesion.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnCerrarSesion.UseDefaultRadiusAndThickness = true;
            this.bfbtnCerrarSesion.Click += new System.EventHandler(this.bfbtnCerrarSesion_Click);
            // 
            // bfbtnSolicitudesCondutor
            // 
            this.bfbtnSolicitudesCondutor.AllowAnimations = true;
            this.bfbtnSolicitudesCondutor.AllowMouseEffects = true;
            this.bfbtnSolicitudesCondutor.AllowToggling = false;
            this.bfbtnSolicitudesCondutor.AnimationSpeed = 200;
            this.bfbtnSolicitudesCondutor.AutoGenerateColors = false;
            this.bfbtnSolicitudesCondutor.AutoRoundBorders = false;
            this.bfbtnSolicitudesCondutor.AutoSizeLeftIcon = true;
            this.bfbtnSolicitudesCondutor.AutoSizeRightIcon = true;
            this.bfbtnSolicitudesCondutor.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnSolicitudesCondutor.BackgroundImage")));
            this.bfbtnSolicitudesCondutor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnSolicitudesCondutor.ButtonText = "Solicitudes de conductores";
            this.bfbtnSolicitudesCondutor.ButtonTextMarginLeft = 0;
            this.bfbtnSolicitudesCondutor.ColorContrastOnClick = 45;
            this.bfbtnSolicitudesCondutor.ColorContrastOnHover = 45;
            this.bfbtnSolicitudesCondutor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bfbtnSolicitudesCondutor.CustomizableEdges = borderEdges4;
            this.bfbtnSolicitudesCondutor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnSolicitudesCondutor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnSolicitudesCondutor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnSolicitudesCondutor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnSolicitudesCondutor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnSolicitudesCondutor.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnSolicitudesCondutor.ForeColor = System.Drawing.Color.White;
            this.bfbtnSolicitudesCondutor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnSolicitudesCondutor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnSolicitudesCondutor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnSolicitudesCondutor.IconMarginLeft = 11;
            this.bfbtnSolicitudesCondutor.IconPadding = 10;
            this.bfbtnSolicitudesCondutor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnSolicitudesCondutor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnSolicitudesCondutor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnSolicitudesCondutor.IconSize = 25;
            this.bfbtnSolicitudesCondutor.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.IdleBorderRadius = 1;
            this.bfbtnSolicitudesCondutor.IdleBorderThickness = 1;
            this.bfbtnSolicitudesCondutor.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.IdleIconLeftImage = null;
            this.bfbtnSolicitudesCondutor.IdleIconRightImage = null;
            this.bfbtnSolicitudesCondutor.IndicateFocus = false;
            this.bfbtnSolicitudesCondutor.Location = new System.Drawing.Point(2, 132);
            this.bfbtnSolicitudesCondutor.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnSolicitudesCondutor.Name = "bfbtnSolicitudesCondutor";
            this.bfbtnSolicitudesCondutor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnSolicitudesCondutor.OnDisabledState.BorderRadius = 1;
            this.bfbtnSolicitudesCondutor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnSolicitudesCondutor.OnDisabledState.BorderThickness = 1;
            this.bfbtnSolicitudesCondutor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnSolicitudesCondutor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnSolicitudesCondutor.OnDisabledState.IconLeftImage = null;
            this.bfbtnSolicitudesCondutor.OnDisabledState.IconRightImage = null;
            this.bfbtnSolicitudesCondutor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnSolicitudesCondutor.onHoverState.BorderRadius = 1;
            this.bfbtnSolicitudesCondutor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnSolicitudesCondutor.onHoverState.BorderThickness = 1;
            this.bfbtnSolicitudesCondutor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnSolicitudesCondutor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnSolicitudesCondutor.onHoverState.IconLeftImage = null;
            this.bfbtnSolicitudesCondutor.onHoverState.IconRightImage = null;
            this.bfbtnSolicitudesCondutor.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.OnIdleState.BorderRadius = 1;
            this.bfbtnSolicitudesCondutor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnSolicitudesCondutor.OnIdleState.BorderThickness = 1;
            this.bfbtnSolicitudesCondutor.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnSolicitudesCondutor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnSolicitudesCondutor.OnIdleState.IconLeftImage = null;
            this.bfbtnSolicitudesCondutor.OnIdleState.IconRightImage = null;
            this.bfbtnSolicitudesCondutor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnSolicitudesCondutor.OnPressedState.BorderRadius = 1;
            this.bfbtnSolicitudesCondutor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnSolicitudesCondutor.OnPressedState.BorderThickness = 1;
            this.bfbtnSolicitudesCondutor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnSolicitudesCondutor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnSolicitudesCondutor.OnPressedState.IconLeftImage = null;
            this.bfbtnSolicitudesCondutor.OnPressedState.IconRightImage = null;
            this.bfbtnSolicitudesCondutor.Size = new System.Drawing.Size(205, 38);
            this.bfbtnSolicitudesCondutor.TabIndex = 8;
            this.bfbtnSolicitudesCondutor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnSolicitudesCondutor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnSolicitudesCondutor.TextMarginLeft = 0;
            this.bfbtnSolicitudesCondutor.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnSolicitudesCondutor.UseDefaultRadiusAndThickness = true;
            this.bfbtnSolicitudesCondutor.Click += new System.EventHandler(this.bfbtnSolicitudesCondutor_Click);
            // 
            // bfbtnDetallesViaje
            // 
            this.bfbtnDetallesViaje.AllowAnimations = true;
            this.bfbtnDetallesViaje.AllowMouseEffects = true;
            this.bfbtnDetallesViaje.AllowToggling = false;
            this.bfbtnDetallesViaje.AnimationSpeed = 200;
            this.bfbtnDetallesViaje.AutoGenerateColors = false;
            this.bfbtnDetallesViaje.AutoRoundBorders = false;
            this.bfbtnDetallesViaje.AutoSizeLeftIcon = true;
            this.bfbtnDetallesViaje.AutoSizeRightIcon = true;
            this.bfbtnDetallesViaje.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnDetallesViaje.BackgroundImage")));
            this.bfbtnDetallesViaje.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnDetallesViaje.ButtonText = "Solicitudes y detalles \r\nde viaje";
            this.bfbtnDetallesViaje.ButtonTextMarginLeft = 0;
            this.bfbtnDetallesViaje.ColorContrastOnClick = 45;
            this.bfbtnDetallesViaje.ColorContrastOnHover = 45;
            this.bfbtnDetallesViaje.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bfbtnDetallesViaje.CustomizableEdges = borderEdges3;
            this.bfbtnDetallesViaje.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnDetallesViaje.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnDetallesViaje.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnDetallesViaje.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnDetallesViaje.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnDetallesViaje.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnDetallesViaje.ForeColor = System.Drawing.Color.White;
            this.bfbtnDetallesViaje.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnDetallesViaje.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnDetallesViaje.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnDetallesViaje.IconMarginLeft = 11;
            this.bfbtnDetallesViaje.IconPadding = 10;
            this.bfbtnDetallesViaje.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnDetallesViaje.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnDetallesViaje.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnDetallesViaje.IconSize = 25;
            this.bfbtnDetallesViaje.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.IdleBorderRadius = 1;
            this.bfbtnDetallesViaje.IdleBorderThickness = 1;
            this.bfbtnDetallesViaje.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.IdleIconLeftImage = null;
            this.bfbtnDetallesViaje.IdleIconRightImage = null;
            this.bfbtnDetallesViaje.IndicateFocus = false;
            this.bfbtnDetallesViaje.Location = new System.Drawing.Point(2, 90);
            this.bfbtnDetallesViaje.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnDetallesViaje.Name = "bfbtnDetallesViaje";
            this.bfbtnDetallesViaje.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnDetallesViaje.OnDisabledState.BorderRadius = 1;
            this.bfbtnDetallesViaje.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnDetallesViaje.OnDisabledState.BorderThickness = 1;
            this.bfbtnDetallesViaje.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnDetallesViaje.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnDetallesViaje.OnDisabledState.IconLeftImage = null;
            this.bfbtnDetallesViaje.OnDisabledState.IconRightImage = null;
            this.bfbtnDetallesViaje.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnDetallesViaje.onHoverState.BorderRadius = 1;
            this.bfbtnDetallesViaje.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnDetallesViaje.onHoverState.BorderThickness = 1;
            this.bfbtnDetallesViaje.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnDetallesViaje.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnDetallesViaje.onHoverState.IconLeftImage = null;
            this.bfbtnDetallesViaje.onHoverState.IconRightImage = null;
            this.bfbtnDetallesViaje.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.OnIdleState.BorderRadius = 1;
            this.bfbtnDetallesViaje.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnDetallesViaje.OnIdleState.BorderThickness = 1;
            this.bfbtnDetallesViaje.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnDetallesViaje.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnDetallesViaje.OnIdleState.IconLeftImage = null;
            this.bfbtnDetallesViaje.OnIdleState.IconRightImage = null;
            this.bfbtnDetallesViaje.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnDetallesViaje.OnPressedState.BorderRadius = 1;
            this.bfbtnDetallesViaje.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnDetallesViaje.OnPressedState.BorderThickness = 1;
            this.bfbtnDetallesViaje.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnDetallesViaje.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnDetallesViaje.OnPressedState.IconLeftImage = null;
            this.bfbtnDetallesViaje.OnPressedState.IconRightImage = null;
            this.bfbtnDetallesViaje.Size = new System.Drawing.Size(205, 38);
            this.bfbtnDetallesViaje.TabIndex = 7;
            this.bfbtnDetallesViaje.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnDetallesViaje.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnDetallesViaje.TextMarginLeft = 0;
            this.bfbtnDetallesViaje.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnDetallesViaje.UseDefaultRadiusAndThickness = true;
            this.bfbtnDetallesViaje.Click += new System.EventHandler(this.bfbtnDetallesViaje_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.bfpbImagenPerfil);
            this.panel1.Controls.Add(this.bflblNombreUsuario);
            this.panel1.Controls.Add(this.bflblTipoUsuario);
            this.panel1.Location = new System.Drawing.Point(1, 1);
            this.panel1.Margin = new System.Windows.Forms.Padding(2);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(213, 194);
            this.panel1.TabIndex = 5;
            // 
            // bfpbImagenPerfil
            // 
            this.bfpbImagenPerfil.AllowFocused = false;
            this.bfpbImagenPerfil.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bfpbImagenPerfil.AutoSizeHeight = true;
            this.bfpbImagenPerfil.BorderRadius = 53;
            this.bfpbImagenPerfil.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bfpbImagenPerfil.ErrorImage")));
            this.bfpbImagenPerfil.Image = ((System.Drawing.Image)(resources.GetObject("bfpbImagenPerfil.Image")));
            this.bfpbImagenPerfil.IsCircle = true;
            this.bfpbImagenPerfil.Location = new System.Drawing.Point(44, 8);
            this.bfpbImagenPerfil.Name = "bfpbImagenPerfil";
            this.bfpbImagenPerfil.Size = new System.Drawing.Size(106, 106);
            this.bfpbImagenPerfil.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bfpbImagenPerfil.TabIndex = 6;
            this.bfpbImagenPerfil.TabStop = false;
            this.bfpbImagenPerfil.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bfpbImagenPerfil.Click += new System.EventHandler(this.bfpbImagenPerfil_Click);
            // 
            // bflblNombreUsuario
            // 
            this.bflblNombreUsuario.AllowParentOverrides = false;
            this.bflblNombreUsuario.AutoEllipsis = false;
            this.bflblNombreUsuario.CursorType = null;
            this.bflblNombreUsuario.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblNombreUsuario.ForeColor = System.Drawing.Color.White;
            this.bflblNombreUsuario.Location = new System.Drawing.Point(8, 120);
            this.bflblNombreUsuario.Margin = new System.Windows.Forms.Padding(2);
            this.bflblNombreUsuario.Name = "bflblNombreUsuario";
            this.bflblNombreUsuario.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblNombreUsuario.Size = new System.Drawing.Size(102, 15);
            this.bflblNombreUsuario.TabIndex = 2;
            this.bflblNombreUsuario.Text = "Nombre de usuario";
            this.bflblNombreUsuario.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblNombreUsuario.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bflblTipoUsuario
            // 
            this.bflblTipoUsuario.AllowParentOverrides = false;
            this.bflblTipoUsuario.AutoEllipsis = false;
            this.bflblTipoUsuario.AutoSize = false;
            this.bflblTipoUsuario.Cursor = System.Windows.Forms.Cursors.Default;
            this.bflblTipoUsuario.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblTipoUsuario.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblTipoUsuario.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bflblTipoUsuario.Location = new System.Drawing.Point(8, 149);
            this.bflblTipoUsuario.Margin = new System.Windows.Forms.Padding(2);
            this.bflblTipoUsuario.Name = "bflblTipoUsuario";
            this.bflblTipoUsuario.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblTipoUsuario.Size = new System.Drawing.Size(104, 25);
            this.bflblTipoUsuario.TabIndex = 1;
            this.bflblTipoUsuario.Text = "Tipo de usuario";
            this.bflblTipoUsuario.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblTipoUsuario.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Ayuda";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges7;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleBorderRadius = 1;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(4, 650);
            this.bunifuButton21.Margin = new System.Windows.Forms.Padding(2);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(208, 38);
            this.bunifuButton21.TabIndex = 4;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bfbtnMisViajes
            // 
            this.bfbtnMisViajes.AllowAnimations = true;
            this.bfbtnMisViajes.AllowMouseEffects = true;
            this.bfbtnMisViajes.AllowToggling = false;
            this.bfbtnMisViajes.AnimationSpeed = 200;
            this.bfbtnMisViajes.AutoGenerateColors = false;
            this.bfbtnMisViajes.AutoRoundBorders = false;
            this.bfbtnMisViajes.AutoSizeLeftIcon = true;
            this.bfbtnMisViajes.AutoSizeRightIcon = true;
            this.bfbtnMisViajes.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnMisViajes.BackgroundImage")));
            this.bfbtnMisViajes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnMisViajes.ButtonText = "Mis viajes";
            this.bfbtnMisViajes.ButtonTextMarginLeft = 0;
            this.bfbtnMisViajes.ColorContrastOnClick = 45;
            this.bfbtnMisViajes.ColorContrastOnHover = 45;
            this.bfbtnMisViajes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bfbtnMisViajes.CustomizableEdges = borderEdges2;
            this.bfbtnMisViajes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnMisViajes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnMisViajes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnMisViajes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnMisViajes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnMisViajes.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnMisViajes.ForeColor = System.Drawing.Color.White;
            this.bfbtnMisViajes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnMisViajes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnMisViajes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnMisViajes.IconMarginLeft = 11;
            this.bfbtnMisViajes.IconPadding = 10;
            this.bfbtnMisViajes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnMisViajes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnMisViajes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnMisViajes.IconSize = 25;
            this.bfbtnMisViajes.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.IdleBorderRadius = 1;
            this.bfbtnMisViajes.IdleBorderThickness = 1;
            this.bfbtnMisViajes.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.IdleIconLeftImage = null;
            this.bfbtnMisViajes.IdleIconRightImage = null;
            this.bfbtnMisViajes.IndicateFocus = false;
            this.bfbtnMisViajes.Location = new System.Drawing.Point(2, 44);
            this.bfbtnMisViajes.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnMisViajes.Name = "bfbtnMisViajes";
            this.bfbtnMisViajes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnMisViajes.OnDisabledState.BorderRadius = 1;
            this.bfbtnMisViajes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnMisViajes.OnDisabledState.BorderThickness = 1;
            this.bfbtnMisViajes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnMisViajes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnMisViajes.OnDisabledState.IconLeftImage = null;
            this.bfbtnMisViajes.OnDisabledState.IconRightImage = null;
            this.bfbtnMisViajes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnMisViajes.onHoverState.BorderRadius = 1;
            this.bfbtnMisViajes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnMisViajes.onHoverState.BorderThickness = 1;
            this.bfbtnMisViajes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnMisViajes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnMisViajes.onHoverState.IconLeftImage = null;
            this.bfbtnMisViajes.onHoverState.IconRightImage = null;
            this.bfbtnMisViajes.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.OnIdleState.BorderRadius = 1;
            this.bfbtnMisViajes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnMisViajes.OnIdleState.BorderThickness = 1;
            this.bfbtnMisViajes.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnMisViajes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnMisViajes.OnIdleState.IconLeftImage = null;
            this.bfbtnMisViajes.OnIdleState.IconRightImage = null;
            this.bfbtnMisViajes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnMisViajes.OnPressedState.BorderRadius = 1;
            this.bfbtnMisViajes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnMisViajes.OnPressedState.BorderThickness = 1;
            this.bfbtnMisViajes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnMisViajes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnMisViajes.OnPressedState.IconLeftImage = null;
            this.bfbtnMisViajes.OnPressedState.IconRightImage = null;
            this.bfbtnMisViajes.Size = new System.Drawing.Size(207, 42);
            this.bfbtnMisViajes.TabIndex = 2;
            this.bfbtnMisViajes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnMisViajes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnMisViajes.TextMarginLeft = 0;
            this.bfbtnMisViajes.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnMisViajes.UseDefaultRadiusAndThickness = true;
            this.bfbtnMisViajes.Click += new System.EventHandler(this.bfbtnMisViajes_Click);
            // 
            // bfbtnViajar
            // 
            this.bfbtnViajar.AllowAnimations = true;
            this.bfbtnViajar.AllowMouseEffects = true;
            this.bfbtnViajar.AllowToggling = false;
            this.bfbtnViajar.AnimationSpeed = 200;
            this.bfbtnViajar.AutoGenerateColors = false;
            this.bfbtnViajar.AutoRoundBorders = false;
            this.bfbtnViajar.AutoSizeLeftIcon = true;
            this.bfbtnViajar.AutoSizeRightIcon = true;
            this.bfbtnViajar.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnViajar.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnViajar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnViajar.BackgroundImage")));
            this.bfbtnViajar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnViajar.ButtonText = "¿Á donde deseas viajar?";
            this.bfbtnViajar.ButtonTextMarginLeft = 0;
            this.bfbtnViajar.ColorContrastOnClick = 45;
            this.bfbtnViajar.ColorContrastOnHover = 45;
            this.bfbtnViajar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bfbtnViajar.CustomizableEdges = borderEdges1;
            this.bfbtnViajar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnViajar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnViajar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnViajar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnViajar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnViajar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnViajar.ForeColor = System.Drawing.Color.White;
            this.bfbtnViajar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnViajar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnViajar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnViajar.IconMarginLeft = 11;
            this.bfbtnViajar.IconPadding = 10;
            this.bfbtnViajar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnViajar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnViajar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnViajar.IconSize = 25;
            this.bfbtnViajar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnViajar.IdleBorderRadius = 1;
            this.bfbtnViajar.IdleBorderThickness = 1;
            this.bfbtnViajar.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnViajar.IdleIconLeftImage = null;
            this.bfbtnViajar.IdleIconRightImage = null;
            this.bfbtnViajar.IndicateFocus = false;
            this.bfbtnViajar.Location = new System.Drawing.Point(2, 2);
            this.bfbtnViajar.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnViajar.Name = "bfbtnViajar";
            this.bfbtnViajar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnViajar.OnDisabledState.BorderRadius = 1;
            this.bfbtnViajar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnViajar.OnDisabledState.BorderThickness = 1;
            this.bfbtnViajar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnViajar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnViajar.OnDisabledState.IconLeftImage = null;
            this.bfbtnViajar.OnDisabledState.IconRightImage = null;
            this.bfbtnViajar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnViajar.onHoverState.BorderRadius = 1;
            this.bfbtnViajar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnViajar.onHoverState.BorderThickness = 1;
            this.bfbtnViajar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnViajar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnViajar.onHoverState.IconLeftImage = null;
            this.bfbtnViajar.onHoverState.IconRightImage = null;
            this.bfbtnViajar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnViajar.OnIdleState.BorderRadius = 1;
            this.bfbtnViajar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnViajar.OnIdleState.BorderThickness = 1;
            this.bfbtnViajar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnViajar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnViajar.OnIdleState.IconLeftImage = null;
            this.bfbtnViajar.OnIdleState.IconRightImage = null;
            this.bfbtnViajar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnViajar.OnPressedState.BorderRadius = 1;
            this.bfbtnViajar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnViajar.OnPressedState.BorderThickness = 1;
            this.bfbtnViajar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnViajar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnViajar.OnPressedState.IconLeftImage = null;
            this.bfbtnViajar.OnPressedState.IconRightImage = null;
            this.bfbtnViajar.Size = new System.Drawing.Size(205, 38);
            this.bfbtnViajar.TabIndex = 1;
            this.bfbtnViajar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnViajar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnViajar.TextMarginLeft = 0;
            this.bfbtnViajar.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnViajar.UseDefaultRadiusAndThickness = true;
            this.bfbtnViajar.Click += new System.EventHandler(this.bfbtnViajar_Click);
            // 
            // bfbtnTrabajaConNosotros
            // 
            this.bfbtnTrabajaConNosotros.AllowAnimations = true;
            this.bfbtnTrabajaConNosotros.AllowMouseEffects = true;
            this.bfbtnTrabajaConNosotros.AllowToggling = false;
            this.bfbtnTrabajaConNosotros.AnimationSpeed = 200;
            this.bfbtnTrabajaConNosotros.AutoGenerateColors = false;
            this.bfbtnTrabajaConNosotros.AutoRoundBorders = false;
            this.bfbtnTrabajaConNosotros.AutoSizeLeftIcon = true;
            this.bfbtnTrabajaConNosotros.AutoSizeRightIcon = true;
            this.bfbtnTrabajaConNosotros.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnTrabajaConNosotros.BackgroundImage")));
            this.bfbtnTrabajaConNosotros.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnTrabajaConNosotros.ButtonText = "! Trabaja con nosotros ¡";
            this.bfbtnTrabajaConNosotros.ButtonTextMarginLeft = 0;
            this.bfbtnTrabajaConNosotros.ColorContrastOnClick = 45;
            this.bfbtnTrabajaConNosotros.ColorContrastOnHover = 45;
            this.bfbtnTrabajaConNosotros.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bfbtnTrabajaConNosotros.CustomizableEdges = borderEdges8;
            this.bfbtnTrabajaConNosotros.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnTrabajaConNosotros.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnTrabajaConNosotros.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnTrabajaConNosotros.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnTrabajaConNosotros.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnTrabajaConNosotros.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnTrabajaConNosotros.ForeColor = System.Drawing.Color.Gold;
            this.bfbtnTrabajaConNosotros.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnTrabajaConNosotros.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnTrabajaConNosotros.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnTrabajaConNosotros.IconMarginLeft = 11;
            this.bfbtnTrabajaConNosotros.IconPadding = 10;
            this.bfbtnTrabajaConNosotros.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnTrabajaConNosotros.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnTrabajaConNosotros.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnTrabajaConNosotros.IconSize = 25;
            this.bfbtnTrabajaConNosotros.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.IdleBorderRadius = 1;
            this.bfbtnTrabajaConNosotros.IdleBorderThickness = 1;
            this.bfbtnTrabajaConNosotros.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.IdleIconLeftImage = null;
            this.bfbtnTrabajaConNosotros.IdleIconRightImage = null;
            this.bfbtnTrabajaConNosotros.IndicateFocus = false;
            this.bfbtnTrabajaConNosotros.Location = new System.Drawing.Point(3, 611);
            this.bfbtnTrabajaConNosotros.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnTrabajaConNosotros.Name = "bfbtnTrabajaConNosotros";
            this.bfbtnTrabajaConNosotros.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnTrabajaConNosotros.OnDisabledState.BorderRadius = 1;
            this.bfbtnTrabajaConNosotros.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnTrabajaConNosotros.OnDisabledState.BorderThickness = 1;
            this.bfbtnTrabajaConNosotros.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnTrabajaConNosotros.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnTrabajaConNosotros.OnDisabledState.IconLeftImage = null;
            this.bfbtnTrabajaConNosotros.OnDisabledState.IconRightImage = null;
            this.bfbtnTrabajaConNosotros.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnTrabajaConNosotros.onHoverState.BorderRadius = 1;
            this.bfbtnTrabajaConNosotros.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnTrabajaConNosotros.onHoverState.BorderThickness = 1;
            this.bfbtnTrabajaConNosotros.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnTrabajaConNosotros.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnTrabajaConNosotros.onHoverState.IconLeftImage = null;
            this.bfbtnTrabajaConNosotros.onHoverState.IconRightImage = null;
            this.bfbtnTrabajaConNosotros.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.OnIdleState.BorderRadius = 1;
            this.bfbtnTrabajaConNosotros.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnTrabajaConNosotros.OnIdleState.BorderThickness = 1;
            this.bfbtnTrabajaConNosotros.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnTrabajaConNosotros.OnIdleState.ForeColor = System.Drawing.Color.Gold;
            this.bfbtnTrabajaConNosotros.OnIdleState.IconLeftImage = null;
            this.bfbtnTrabajaConNosotros.OnIdleState.IconRightImage = null;
            this.bfbtnTrabajaConNosotros.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnTrabajaConNosotros.OnPressedState.BorderRadius = 1;
            this.bfbtnTrabajaConNosotros.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnTrabajaConNosotros.OnPressedState.BorderThickness = 1;
            this.bfbtnTrabajaConNosotros.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnTrabajaConNosotros.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnTrabajaConNosotros.OnPressedState.IconLeftImage = null;
            this.bfbtnTrabajaConNosotros.OnPressedState.IconRightImage = null;
            this.bfbtnTrabajaConNosotros.Size = new System.Drawing.Size(208, 35);
            this.bfbtnTrabajaConNosotros.TabIndex = 1;
            this.bfbtnTrabajaConNosotros.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnTrabajaConNosotros.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnTrabajaConNosotros.TextMarginLeft = 0;
            this.bfbtnTrabajaConNosotros.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnTrabajaConNosotros.UseDefaultRadiusAndThickness = true;
            this.bfbtnTrabajaConNosotros.Click += new System.EventHandler(this.bfbtnTrabajaConNosotros_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(787, 10);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(20, 21);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 15;
            this.pictureBox1.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(815, 10);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(21, 21);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 16;
            this.pictureBox2.TabStop = false;
            // 
            // panelContenedor
            // 
            this.panelContenedor.Controls.Add(this.panelHeader);
            this.panelContenedor.Cursor = System.Windows.Forms.Cursors.Default;
            this.panelContenedor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelContenedor.Location = new System.Drawing.Point(218, 0);
            this.panelContenedor.Margin = new System.Windows.Forms.Padding(2);
            this.panelContenedor.Name = "panelContenedor";
            this.panelContenedor.Size = new System.Drawing.Size(947, 742);
            this.panelContenedor.TabIndex = 17;
            this.panelContenedor.Paint += new System.Windows.Forms.PaintEventHandler(this.panelContenedor_Paint);
            // 
            // panelHeader
            // 
            this.panelHeader.BackColor = System.Drawing.Color.Transparent;
            this.panelHeader.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelHeader.BackgroundImage")));
            this.panelHeader.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelHeader.BorderRadius = 1;
            this.panelHeader.Controls.Add(this.ptbMaximizar);
            this.panelHeader.Controls.Add(this.ptbCerrar);
            this.panelHeader.Controls.Add(this.ptbMinizar);
            this.panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelHeader.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelHeader.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelHeader.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelHeader.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.panelHeader.Location = new System.Drawing.Point(0, 0);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Quality = 10;
            this.panelHeader.Size = new System.Drawing.Size(947, 29);
            this.panelHeader.TabIndex = 0;
            // 
            // ptbMaximizar
            // 
            this.ptbMaximizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ptbMaximizar.Image = ((System.Drawing.Image)(resources.GetObject("ptbMaximizar.Image")));
            this.ptbMaximizar.Location = new System.Drawing.Point(902, 3);
            this.ptbMaximizar.Name = "ptbMaximizar";
            this.ptbMaximizar.Size = new System.Drawing.Size(17, 18);
            this.ptbMaximizar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ptbMaximizar.TabIndex = 61;
            this.ptbMaximizar.TabStop = false;
            this.ptbMaximizar.Click += new System.EventHandler(this.ptbMaximizar_Click);
            // 
            // ptbCerrar
            // 
            this.ptbCerrar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ptbCerrar.Image = ((System.Drawing.Image)(resources.GetObject("ptbCerrar.Image")));
            this.ptbCerrar.Location = new System.Drawing.Point(925, 3);
            this.ptbCerrar.Name = "ptbCerrar";
            this.ptbCerrar.Size = new System.Drawing.Size(18, 18);
            this.ptbCerrar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ptbCerrar.TabIndex = 60;
            this.ptbCerrar.TabStop = false;
            this.ptbCerrar.Click += new System.EventHandler(this.ptbCerrar_Click);
            // 
            // ptbMinizar
            // 
            this.ptbMinizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ptbMinizar.Image = ((System.Drawing.Image)(resources.GetObject("ptbMinizar.Image")));
            this.ptbMinizar.Location = new System.Drawing.Point(877, 3);
            this.ptbMinizar.Name = "ptbMinizar";
            this.ptbMinizar.Size = new System.Drawing.Size(17, 18);
            this.ptbMinizar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ptbMinizar.TabIndex = 59;
            this.ptbMinizar.TabStop = false;
            this.ptbMinizar.Click += new System.EventHandler(this.ptbMinizar_Click);
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.panelHeader;
            this.bunifuDragControl1.Vertical = true;
            // 
            // bfbtnCrearAdministrador
            // 
            this.bfbtnCrearAdministrador.AllowAnimations = true;
            this.bfbtnCrearAdministrador.AllowMouseEffects = true;
            this.bfbtnCrearAdministrador.AllowToggling = false;
            this.bfbtnCrearAdministrador.AnimationSpeed = 200;
            this.bfbtnCrearAdministrador.AutoGenerateColors = false;
            this.bfbtnCrearAdministrador.AutoRoundBorders = false;
            this.bfbtnCrearAdministrador.AutoSizeLeftIcon = true;
            this.bfbtnCrearAdministrador.AutoSizeRightIcon = true;
            this.bfbtnCrearAdministrador.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.BackColor1 = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnCrearAdministrador.BackgroundImage")));
            this.bfbtnCrearAdministrador.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCrearAdministrador.ButtonText = "Crear un perfil de Administrador";
            this.bfbtnCrearAdministrador.ButtonTextMarginLeft = 0;
            this.bfbtnCrearAdministrador.ColorContrastOnClick = 45;
            this.bfbtnCrearAdministrador.ColorContrastOnHover = 45;
            this.bfbtnCrearAdministrador.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bfbtnCrearAdministrador.CustomizableEdges = borderEdges5;
            this.bfbtnCrearAdministrador.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnCrearAdministrador.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnCrearAdministrador.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnCrearAdministrador.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnCrearAdministrador.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnCrearAdministrador.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnCrearAdministrador.ForeColor = System.Drawing.Color.White;
            this.bfbtnCrearAdministrador.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnCrearAdministrador.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnCrearAdministrador.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnCrearAdministrador.IconMarginLeft = 11;
            this.bfbtnCrearAdministrador.IconPadding = 10;
            this.bfbtnCrearAdministrador.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnCrearAdministrador.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnCrearAdministrador.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnCrearAdministrador.IconSize = 25;
            this.bfbtnCrearAdministrador.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.IdleBorderRadius = 1;
            this.bfbtnCrearAdministrador.IdleBorderThickness = 1;
            this.bfbtnCrearAdministrador.IdleFillColor = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.IdleIconLeftImage = null;
            this.bfbtnCrearAdministrador.IdleIconRightImage = null;
            this.bfbtnCrearAdministrador.IndicateFocus = false;
            this.bfbtnCrearAdministrador.Location = new System.Drawing.Point(2, 174);
            this.bfbtnCrearAdministrador.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnCrearAdministrador.Name = "bfbtnCrearAdministrador";
            this.bfbtnCrearAdministrador.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnCrearAdministrador.OnDisabledState.BorderRadius = 1;
            this.bfbtnCrearAdministrador.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCrearAdministrador.OnDisabledState.BorderThickness = 1;
            this.bfbtnCrearAdministrador.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnCrearAdministrador.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnCrearAdministrador.OnDisabledState.IconLeftImage = null;
            this.bfbtnCrearAdministrador.OnDisabledState.IconRightImage = null;
            this.bfbtnCrearAdministrador.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnCrearAdministrador.onHoverState.BorderRadius = 1;
            this.bfbtnCrearAdministrador.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCrearAdministrador.onHoverState.BorderThickness = 1;
            this.bfbtnCrearAdministrador.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnCrearAdministrador.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnCrearAdministrador.onHoverState.IconLeftImage = null;
            this.bfbtnCrearAdministrador.onHoverState.IconRightImage = null;
            this.bfbtnCrearAdministrador.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.OnIdleState.BorderRadius = 1;
            this.bfbtnCrearAdministrador.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCrearAdministrador.OnIdleState.BorderThickness = 1;
            this.bfbtnCrearAdministrador.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bfbtnCrearAdministrador.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnCrearAdministrador.OnIdleState.IconLeftImage = null;
            this.bfbtnCrearAdministrador.OnIdleState.IconRightImage = null;
            this.bfbtnCrearAdministrador.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnCrearAdministrador.OnPressedState.BorderRadius = 1;
            this.bfbtnCrearAdministrador.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnCrearAdministrador.OnPressedState.BorderThickness = 1;
            this.bfbtnCrearAdministrador.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnCrearAdministrador.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnCrearAdministrador.OnPressedState.IconLeftImage = null;
            this.bfbtnCrearAdministrador.OnPressedState.IconRightImage = null;
            this.bfbtnCrearAdministrador.Size = new System.Drawing.Size(205, 38);
            this.bfbtnCrearAdministrador.TabIndex = 10;
            this.bfbtnCrearAdministrador.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnCrearAdministrador.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnCrearAdministrador.TextMarginLeft = 0;
            this.bfbtnCrearAdministrador.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnCrearAdministrador.UseDefaultRadiusAndThickness = true;
            this.bfbtnCrearAdministrador.Click += new System.EventHandler(this.bfbtnCrearAdministrador_Click);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.flowLayoutPanel1.Controls.Add(this.bfbtnViajar);
            this.flowLayoutPanel1.Controls.Add(this.bfbtnMisViajes);
            this.flowLayoutPanel1.Controls.Add(this.bfbtnDetallesViaje);
            this.flowLayoutPanel1.Controls.Add(this.bfbtnSolicitudesCondutor);
            this.flowLayoutPanel1.Controls.Add(this.bfbtnCrearAdministrador);
            this.flowLayoutPanel1.Location = new System.Drawing.Point(5, 211);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(208, 225);
            this.flowLayoutPanel1.TabIndex = 1;
            // 
            // bfSnackbarHome
            // 
            this.bfSnackbarHome.AllowDragging = false;
            this.bfSnackbarHome.AllowMultipleViews = true;
            this.bfSnackbarHome.ClickToClose = true;
            this.bfSnackbarHome.DoubleClickToClose = true;
            this.bfSnackbarHome.DurationAfterIdle = 4000;
            this.bfSnackbarHome.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.ErrorOptions.ActionBorderRadius = 1;
            this.bfSnackbarHome.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bfSnackbarHome.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bfSnackbarHome.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bfSnackbarHome.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bfSnackbarHome.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bfSnackbarHome.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bfSnackbarHome.ErrorOptions.IconLeftMargin = 12;
            this.bfSnackbarHome.FadeCloseIcon = false;
            this.bfSnackbarHome.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bfSnackbarHome.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.InformationOptions.ActionBorderRadius = 1;
            this.bfSnackbarHome.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bfSnackbarHome.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bfSnackbarHome.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bfSnackbarHome.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bfSnackbarHome.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bfSnackbarHome.InformationOptions.IconLeftMargin = 12;
            this.bfSnackbarHome.Margin = 5;
            this.bfSnackbarHome.MaximumSize = new System.Drawing.Size(0, 0);
            this.bfSnackbarHome.MaximumViews = 7;
            this.bfSnackbarHome.MessageRightMargin = 15;
            this.bfSnackbarHome.MinimumSize = new System.Drawing.Size(0, 0);
            this.bfSnackbarHome.ShowBorders = false;
            this.bfSnackbarHome.ShowCloseIcon = false;
            this.bfSnackbarHome.ShowIcon = true;
            this.bfSnackbarHome.ShowShadows = true;
            this.bfSnackbarHome.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.SuccessOptions.ActionBorderRadius = 1;
            this.bfSnackbarHome.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bfSnackbarHome.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bfSnackbarHome.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bfSnackbarHome.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bfSnackbarHome.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bfSnackbarHome.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bfSnackbarHome.SuccessOptions.IconLeftMargin = 12;
            this.bfSnackbarHome.ViewsMargin = 7;
            this.bfSnackbarHome.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bfSnackbarHome.WarningOptions.ActionBorderRadius = 1;
            this.bfSnackbarHome.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bfSnackbarHome.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bfSnackbarHome.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bfSnackbarHome.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bfSnackbarHome.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bfSnackbarHome.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bfSnackbarHome.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bfSnackbarHome.WarningOptions.IconLeftMargin = 12;
            this.bfSnackbarHome.ZoomCloseIcon = true;
            // 
            // frmHome
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1165, 742);
            this.Controls.Add(this.panelContenedor);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.panelVertical);
            this.Cursor = System.Windows.Forms.Cursors.SizeAll;
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "frmHome";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmMain";
            this.Load += new System.EventHandler(this.frmHome_Load);
            this.panelVertical.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bfpbImagenPerfil)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.panelContenedor.ResumeLayout(false);
            this.panelHeader.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ptbMaximizar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbCerrar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbMinizar)).EndInit();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel panelVertical;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Panel panelContenedor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnViajar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnTrabajaConNosotros;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnMisViajes;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuLabel bflblTipoUsuario;
        private Bunifu.UI.WinForms.BunifuLabel bflblNombreUsuario;
        private Bunifu.UI.WinForms.BunifuPictureBox bfpbImagenPerfil;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.UI.WinForms.BunifuGradientPanel panelHeader;
        private System.Windows.Forms.PictureBox ptbMaximizar;
        private System.Windows.Forms.PictureBox ptbCerrar;
        private System.Windows.Forms.PictureBox ptbMinizar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnDetallesViaje;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnSolicitudesCondutor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnCerrarSesion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnCrearAdministrador;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuSnackbar bfSnackbarHome;
    }
}