
namespace final_motoDix.Vistas
{
    partial class frmPerfil
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPerfil));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties89 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties90 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties91 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties92 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties93 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties94 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties95 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties96 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties97 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties98 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties99 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties100 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties101 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties102 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties103 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties104 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties105 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties106 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties107 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties108 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties113 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties114 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties115 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties116 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties117 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties118 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties119 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties120 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties121 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties122 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties123 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties124 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties125 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties126 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties127 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties128 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties129 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties130 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties131 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties132 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bftxtConfirmPasswordPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPasswordPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmacionCelularPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtNumeroCelPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmarEmailPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxEmailPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.lblNombreUsuarioPerfil = new System.Windows.Forms.Label();
            this.lblTipoUsuarioPerfil = new System.Windows.Forms.Label();
            this.lblDatosPersonales = new System.Windows.Forms.Label();
            this.cmbGeneroPerfil = new System.Windows.Forms.ComboBox();
            this.bflblGenero = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblFechaNacimiento = new Bunifu.UI.WinForms.BunifuLabel();
            this.bfdtpFechaNacimientoPerfil = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bftxtDocumentoPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoApellidoperfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerApellidoPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoNombrePerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerNombrePerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuVScrollBar1 = new Bunifu.UI.WinForms.BunifuVScrollBar();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bftxtConfirmPasswordPerfil
            // 
            this.bftxtConfirmPasswordPerfil.AcceptsReturn = false;
            this.bftxtConfirmPasswordPerfil.AcceptsTab = false;
            this.bftxtConfirmPasswordPerfil.AnimationSpeed = 200;
            this.bftxtConfirmPasswordPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmPasswordPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmPasswordPerfil.AutoSizeHeight = true;
            this.bftxtConfirmPasswordPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmPasswordPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmPasswordPerfil.BackgroundImage")));
            this.bftxtConfirmPasswordPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmPasswordPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmPasswordPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmPasswordPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmPasswordPerfil.BorderRadius = 1;
            this.bftxtConfirmPasswordPerfil.BorderThickness = 1;
            this.bftxtConfirmPasswordPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmPasswordPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmPasswordPerfil.DefaultText = "";
            this.bftxtConfirmPasswordPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmPasswordPerfil.HideSelection = true;
            this.bftxtConfirmPasswordPerfil.IconLeft = null;
            this.bftxtConfirmPasswordPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.IconPadding = 10;
            this.bftxtConfirmPasswordPerfil.IconRight = null;
            this.bftxtConfirmPasswordPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.Lines = new string[0];
            this.bftxtConfirmPasswordPerfil.Location = new System.Drawing.Point(338, 692);
            this.bftxtConfirmPasswordPerfil.MaxLength = 32767;
            this.bftxtConfirmPasswordPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmPasswordPerfil.Modified = false;
            this.bftxtConfirmPasswordPerfil.Multiline = false;
            this.bftxtConfirmPasswordPerfil.Name = "bftxtConfirmPasswordPerfil";
            stateProperties89.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties89.FillColor = System.Drawing.Color.Empty;
            stateProperties89.ForeColor = System.Drawing.Color.Empty;
            stateProperties89.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnActiveState = stateProperties89;
            stateProperties90.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties90.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties90.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties90.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmPasswordPerfil.OnDisabledState = stateProperties90;
            stateProperties91.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties91.FillColor = System.Drawing.Color.Empty;
            stateProperties91.ForeColor = System.Drawing.Color.Empty;
            stateProperties91.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnHoverState = stateProperties91;
            stateProperties92.BorderColor = System.Drawing.Color.Silver;
            stateProperties92.FillColor = System.Drawing.Color.White;
            stateProperties92.ForeColor = System.Drawing.Color.Empty;
            stateProperties92.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnIdleState = stateProperties92;
            this.bftxtConfirmPasswordPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmPasswordPerfil.PasswordChar = '\0';
            this.bftxtConfirmPasswordPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmPasswordPerfil.PlaceholderText = "Confirmar Contraseña";
            this.bftxtConfirmPasswordPerfil.ReadOnly = false;
            this.bftxtConfirmPasswordPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmPasswordPerfil.SelectedText = "";
            this.bftxtConfirmPasswordPerfil.SelectionLength = 0;
            this.bftxtConfirmPasswordPerfil.SelectionStart = 0;
            this.bftxtConfirmPasswordPerfil.ShortcutsEnabled = true;
            this.bftxtConfirmPasswordPerfil.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmPasswordPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmPasswordPerfil.TabIndex = 36;
            this.bftxtConfirmPasswordPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmPasswordPerfil.TextMarginBottom = 0;
            this.bftxtConfirmPasswordPerfil.TextMarginLeft = 3;
            this.bftxtConfirmPasswordPerfil.TextMarginTop = 1;
            this.bftxtConfirmPasswordPerfil.TextPlaceholder = "Confirmar Contraseña";
            this.bftxtConfirmPasswordPerfil.UseSystemPasswordChar = false;
            this.bftxtConfirmPasswordPerfil.WordWrap = true;
            // 
            // bftxtPasswordPerfil
            // 
            this.bftxtPasswordPerfil.AcceptsReturn = false;
            this.bftxtPasswordPerfil.AcceptsTab = false;
            this.bftxtPasswordPerfil.AnimationSpeed = 200;
            this.bftxtPasswordPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPasswordPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPasswordPerfil.AutoSizeHeight = true;
            this.bftxtPasswordPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPasswordPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPasswordPerfil.BackgroundImage")));
            this.bftxtPasswordPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPasswordPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPasswordPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPasswordPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPasswordPerfil.BorderRadius = 1;
            this.bftxtPasswordPerfil.BorderThickness = 1;
            this.bftxtPasswordPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPasswordPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPasswordPerfil.DefaultText = "";
            this.bftxtPasswordPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPasswordPerfil.HideSelection = true;
            this.bftxtPasswordPerfil.IconLeft = null;
            this.bftxtPasswordPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.IconPadding = 10;
            this.bftxtPasswordPerfil.IconRight = null;
            this.bftxtPasswordPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.Lines = new string[0];
            this.bftxtPasswordPerfil.Location = new System.Drawing.Point(73, 692);
            this.bftxtPasswordPerfil.MaxLength = 32767;
            this.bftxtPasswordPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPasswordPerfil.Modified = false;
            this.bftxtPasswordPerfil.Multiline = false;
            this.bftxtPasswordPerfil.Name = "bftxtPasswordPerfil";
            stateProperties93.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties93.FillColor = System.Drawing.Color.Empty;
            stateProperties93.ForeColor = System.Drawing.Color.Empty;
            stateProperties93.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnActiveState = stateProperties93;
            stateProperties94.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties94.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties94.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties94.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPasswordPerfil.OnDisabledState = stateProperties94;
            stateProperties95.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties95.FillColor = System.Drawing.Color.Empty;
            stateProperties95.ForeColor = System.Drawing.Color.Empty;
            stateProperties95.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnHoverState = stateProperties95;
            stateProperties96.BorderColor = System.Drawing.Color.Silver;
            stateProperties96.FillColor = System.Drawing.Color.White;
            stateProperties96.ForeColor = System.Drawing.Color.Empty;
            stateProperties96.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnIdleState = stateProperties96;
            this.bftxtPasswordPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPasswordPerfil.PasswordChar = '\0';
            this.bftxtPasswordPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPasswordPerfil.PlaceholderText = "Contraseña";
            this.bftxtPasswordPerfil.ReadOnly = false;
            this.bftxtPasswordPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPasswordPerfil.SelectedText = "";
            this.bftxtPasswordPerfil.SelectionLength = 0;
            this.bftxtPasswordPerfil.SelectionStart = 0;
            this.bftxtPasswordPerfil.ShortcutsEnabled = true;
            this.bftxtPasswordPerfil.Size = new System.Drawing.Size(226, 37);
            this.bftxtPasswordPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPasswordPerfil.TabIndex = 35;
            this.bftxtPasswordPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPasswordPerfil.TextMarginBottom = 0;
            this.bftxtPasswordPerfil.TextMarginLeft = 3;
            this.bftxtPasswordPerfil.TextMarginTop = 1;
            this.bftxtPasswordPerfil.TextPlaceholder = "Contraseña";
            this.bftxtPasswordPerfil.UseSystemPasswordChar = false;
            this.bftxtPasswordPerfil.WordWrap = true;
            // 
            // bftxtConfirmacionCelularPerfil
            // 
            this.bftxtConfirmacionCelularPerfil.AcceptsReturn = false;
            this.bftxtConfirmacionCelularPerfil.AcceptsTab = false;
            this.bftxtConfirmacionCelularPerfil.AnimationSpeed = 200;
            this.bftxtConfirmacionCelularPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmacionCelularPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmacionCelularPerfil.AutoSizeHeight = true;
            this.bftxtConfirmacionCelularPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmacionCelularPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmacionCelularPerfil.BackgroundImage")));
            this.bftxtConfirmacionCelularPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmacionCelularPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmacionCelularPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmacionCelularPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmacionCelularPerfil.BorderRadius = 1;
            this.bftxtConfirmacionCelularPerfil.BorderThickness = 1;
            this.bftxtConfirmacionCelularPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmacionCelularPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmacionCelularPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmacionCelularPerfil.DefaultText = "";
            this.bftxtConfirmacionCelularPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmacionCelularPerfil.HideSelection = true;
            this.bftxtConfirmacionCelularPerfil.IconLeft = null;
            this.bftxtConfirmacionCelularPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmacionCelularPerfil.IconPadding = 10;
            this.bftxtConfirmacionCelularPerfil.IconRight = null;
            this.bftxtConfirmacionCelularPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmacionCelularPerfil.Lines = new string[0];
            this.bftxtConfirmacionCelularPerfil.Location = new System.Drawing.Point(338, 608);
            this.bftxtConfirmacionCelularPerfil.MaxLength = 32767;
            this.bftxtConfirmacionCelularPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmacionCelularPerfil.Modified = false;
            this.bftxtConfirmacionCelularPerfil.Multiline = false;
            this.bftxtConfirmacionCelularPerfil.Name = "bftxtConfirmacionCelularPerfil";
            stateProperties97.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties97.FillColor = System.Drawing.Color.Empty;
            stateProperties97.ForeColor = System.Drawing.Color.Empty;
            stateProperties97.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmacionCelularPerfil.OnActiveState = stateProperties97;
            stateProperties98.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties98.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties98.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties98.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmacionCelularPerfil.OnDisabledState = stateProperties98;
            stateProperties99.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties99.FillColor = System.Drawing.Color.Empty;
            stateProperties99.ForeColor = System.Drawing.Color.Empty;
            stateProperties99.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmacionCelularPerfil.OnHoverState = stateProperties99;
            stateProperties100.BorderColor = System.Drawing.Color.Silver;
            stateProperties100.FillColor = System.Drawing.Color.White;
            stateProperties100.ForeColor = System.Drawing.Color.Empty;
            stateProperties100.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmacionCelularPerfil.OnIdleState = stateProperties100;
            this.bftxtConfirmacionCelularPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmacionCelularPerfil.PasswordChar = '\0';
            this.bftxtConfirmacionCelularPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmacionCelularPerfil.PlaceholderText = "Confirme numero celular";
            this.bftxtConfirmacionCelularPerfil.ReadOnly = false;
            this.bftxtConfirmacionCelularPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmacionCelularPerfil.SelectedText = "";
            this.bftxtConfirmacionCelularPerfil.SelectionLength = 0;
            this.bftxtConfirmacionCelularPerfil.SelectionStart = 0;
            this.bftxtConfirmacionCelularPerfil.ShortcutsEnabled = true;
            this.bftxtConfirmacionCelularPerfil.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmacionCelularPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmacionCelularPerfil.TabIndex = 34;
            this.bftxtConfirmacionCelularPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmacionCelularPerfil.TextMarginBottom = 0;
            this.bftxtConfirmacionCelularPerfil.TextMarginLeft = 3;
            this.bftxtConfirmacionCelularPerfil.TextMarginTop = 1;
            this.bftxtConfirmacionCelularPerfil.TextPlaceholder = "Confirme numero celular";
            this.bftxtConfirmacionCelularPerfil.UseSystemPasswordChar = false;
            this.bftxtConfirmacionCelularPerfil.WordWrap = true;
            // 
            // bftxtNumeroCelPerfil
            // 
            this.bftxtNumeroCelPerfil.AcceptsReturn = false;
            this.bftxtNumeroCelPerfil.AcceptsTab = false;
            this.bftxtNumeroCelPerfil.AnimationSpeed = 200;
            this.bftxtNumeroCelPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtNumeroCelPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtNumeroCelPerfil.AutoSizeHeight = true;
            this.bftxtNumeroCelPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtNumeroCelPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtNumeroCelPerfil.BackgroundImage")));
            this.bftxtNumeroCelPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtNumeroCelPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtNumeroCelPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtNumeroCelPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtNumeroCelPerfil.BorderRadius = 1;
            this.bftxtNumeroCelPerfil.BorderThickness = 1;
            this.bftxtNumeroCelPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtNumeroCelPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtNumeroCelPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtNumeroCelPerfil.DefaultText = "";
            this.bftxtNumeroCelPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtNumeroCelPerfil.HideSelection = true;
            this.bftxtNumeroCelPerfil.IconLeft = null;
            this.bftxtNumeroCelPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtNumeroCelPerfil.IconPadding = 10;
            this.bftxtNumeroCelPerfil.IconRight = null;
            this.bftxtNumeroCelPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtNumeroCelPerfil.Lines = new string[0];
            this.bftxtNumeroCelPerfil.Location = new System.Drawing.Point(73, 608);
            this.bftxtNumeroCelPerfil.MaxLength = 32767;
            this.bftxtNumeroCelPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtNumeroCelPerfil.Modified = false;
            this.bftxtNumeroCelPerfil.Multiline = false;
            this.bftxtNumeroCelPerfil.Name = "bftxtNumeroCelPerfil";
            stateProperties101.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties101.FillColor = System.Drawing.Color.Empty;
            stateProperties101.ForeColor = System.Drawing.Color.Empty;
            stateProperties101.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtNumeroCelPerfil.OnActiveState = stateProperties101;
            stateProperties102.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties102.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties102.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties102.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtNumeroCelPerfil.OnDisabledState = stateProperties102;
            stateProperties103.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties103.FillColor = System.Drawing.Color.Empty;
            stateProperties103.ForeColor = System.Drawing.Color.Empty;
            stateProperties103.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtNumeroCelPerfil.OnHoverState = stateProperties103;
            stateProperties104.BorderColor = System.Drawing.Color.Silver;
            stateProperties104.FillColor = System.Drawing.Color.White;
            stateProperties104.ForeColor = System.Drawing.Color.Empty;
            stateProperties104.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtNumeroCelPerfil.OnIdleState = stateProperties104;
            this.bftxtNumeroCelPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtNumeroCelPerfil.PasswordChar = '\0';
            this.bftxtNumeroCelPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtNumeroCelPerfil.PlaceholderText = "Numero de celular";
            this.bftxtNumeroCelPerfil.ReadOnly = false;
            this.bftxtNumeroCelPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtNumeroCelPerfil.SelectedText = "";
            this.bftxtNumeroCelPerfil.SelectionLength = 0;
            this.bftxtNumeroCelPerfil.SelectionStart = 0;
            this.bftxtNumeroCelPerfil.ShortcutsEnabled = true;
            this.bftxtNumeroCelPerfil.Size = new System.Drawing.Size(226, 37);
            this.bftxtNumeroCelPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtNumeroCelPerfil.TabIndex = 33;
            this.bftxtNumeroCelPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtNumeroCelPerfil.TextMarginBottom = 0;
            this.bftxtNumeroCelPerfil.TextMarginLeft = 3;
            this.bftxtNumeroCelPerfil.TextMarginTop = 1;
            this.bftxtNumeroCelPerfil.TextPlaceholder = "Numero de celular";
            this.bftxtNumeroCelPerfil.UseSystemPasswordChar = false;
            this.bftxtNumeroCelPerfil.WordWrap = true;
            // 
            // bftxtConfirmarEmailPerfil
            // 
            this.bftxtConfirmarEmailPerfil.AcceptsReturn = false;
            this.bftxtConfirmarEmailPerfil.AcceptsTab = false;
            this.bftxtConfirmarEmailPerfil.AnimationSpeed = 200;
            this.bftxtConfirmarEmailPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmarEmailPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmarEmailPerfil.AutoSizeHeight = true;
            this.bftxtConfirmarEmailPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmarEmailPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmarEmailPerfil.BackgroundImage")));
            this.bftxtConfirmarEmailPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmarEmailPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmarEmailPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmarEmailPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmailPerfil.BorderRadius = 1;
            this.bftxtConfirmarEmailPerfil.BorderThickness = 1;
            this.bftxtConfirmarEmailPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmarEmailPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmarEmailPerfil.DefaultText = "";
            this.bftxtConfirmarEmailPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmarEmailPerfil.HideSelection = true;
            this.bftxtConfirmarEmailPerfil.IconLeft = null;
            this.bftxtConfirmarEmailPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.IconPadding = 10;
            this.bftxtConfirmarEmailPerfil.IconRight = null;
            this.bftxtConfirmarEmailPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.Lines = new string[0];
            this.bftxtConfirmarEmailPerfil.Location = new System.Drawing.Point(338, 522);
            this.bftxtConfirmarEmailPerfil.MaxLength = 32767;
            this.bftxtConfirmarEmailPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmarEmailPerfil.Modified = false;
            this.bftxtConfirmarEmailPerfil.Multiline = false;
            this.bftxtConfirmarEmailPerfil.Name = "bftxtConfirmarEmailPerfil";
            stateProperties105.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties105.FillColor = System.Drawing.Color.Empty;
            stateProperties105.ForeColor = System.Drawing.Color.Empty;
            stateProperties105.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnActiveState = stateProperties105;
            stateProperties106.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties106.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties106.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties106.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmarEmailPerfil.OnDisabledState = stateProperties106;
            stateProperties107.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties107.FillColor = System.Drawing.Color.Empty;
            stateProperties107.ForeColor = System.Drawing.Color.Empty;
            stateProperties107.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnHoverState = stateProperties107;
            stateProperties108.BorderColor = System.Drawing.Color.Silver;
            stateProperties108.FillColor = System.Drawing.Color.White;
            stateProperties108.ForeColor = System.Drawing.Color.Empty;
            stateProperties108.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnIdleState = stateProperties108;
            this.bftxtConfirmarEmailPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmarEmailPerfil.PasswordChar = '\0';
            this.bftxtConfirmarEmailPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmailPerfil.PlaceholderText = "Confirme e-mail";
            this.bftxtConfirmarEmailPerfil.ReadOnly = false;
            this.bftxtConfirmarEmailPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmarEmailPerfil.SelectedText = "";
            this.bftxtConfirmarEmailPerfil.SelectionLength = 0;
            this.bftxtConfirmarEmailPerfil.SelectionStart = 0;
            this.bftxtConfirmarEmailPerfil.ShortcutsEnabled = true;
            this.bftxtConfirmarEmailPerfil.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmarEmailPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmarEmailPerfil.TabIndex = 32;
            this.bftxtConfirmarEmailPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmarEmailPerfil.TextMarginBottom = 0;
            this.bftxtConfirmarEmailPerfil.TextMarginLeft = 3;
            this.bftxtConfirmarEmailPerfil.TextMarginTop = 1;
            this.bftxtConfirmarEmailPerfil.TextPlaceholder = "Confirme e-mail";
            this.bftxtConfirmarEmailPerfil.UseSystemPasswordChar = false;
            this.bftxtConfirmarEmailPerfil.WordWrap = true;
            // 
            // bftxtxEmailPerfil
            // 
            this.bftxtxEmailPerfil.AcceptsReturn = false;
            this.bftxtxEmailPerfil.AcceptsTab = false;
            this.bftxtxEmailPerfil.AnimationSpeed = 200;
            this.bftxtxEmailPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxEmailPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxEmailPerfil.AutoSizeHeight = true;
            this.bftxtxEmailPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxEmailPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxEmailPerfil.BackgroundImage")));
            this.bftxtxEmailPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxEmailPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxEmailPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxEmailPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxEmailPerfil.BorderRadius = 1;
            this.bftxtxEmailPerfil.BorderThickness = 1;
            this.bftxtxEmailPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxEmailPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxEmailPerfil.DefaultText = "";
            this.bftxtxEmailPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtxEmailPerfil.HideSelection = true;
            this.bftxtxEmailPerfil.IconLeft = null;
            this.bftxtxEmailPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.IconPadding = 10;
            this.bftxtxEmailPerfil.IconRight = null;
            this.bftxtxEmailPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.Lines = new string[0];
            this.bftxtxEmailPerfil.Location = new System.Drawing.Point(73, 522);
            this.bftxtxEmailPerfil.MaxLength = 32767;
            this.bftxtxEmailPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxEmailPerfil.Modified = false;
            this.bftxtxEmailPerfil.Multiline = false;
            this.bftxtxEmailPerfil.Name = "bftxtxEmailPerfil";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxEmailPerfil.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.Silver;
            stateProperties112.FillColor = System.Drawing.Color.White;
            stateProperties112.ForeColor = System.Drawing.Color.Empty;
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnIdleState = stateProperties112;
            this.bftxtxEmailPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxEmailPerfil.PasswordChar = '\0';
            this.bftxtxEmailPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxEmailPerfil.PlaceholderText = "E-mail";
            this.bftxtxEmailPerfil.ReadOnly = false;
            this.bftxtxEmailPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxEmailPerfil.SelectedText = "";
            this.bftxtxEmailPerfil.SelectionLength = 0;
            this.bftxtxEmailPerfil.SelectionStart = 0;
            this.bftxtxEmailPerfil.ShortcutsEnabled = true;
            this.bftxtxEmailPerfil.Size = new System.Drawing.Size(226, 37);
            this.bftxtxEmailPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxEmailPerfil.TabIndex = 31;
            this.bftxtxEmailPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxEmailPerfil.TextMarginBottom = 0;
            this.bftxtxEmailPerfil.TextMarginLeft = 3;
            this.bftxtxEmailPerfil.TextMarginTop = 1;
            this.bftxtxEmailPerfil.TextPlaceholder = "E-mail";
            this.bftxtxEmailPerfil.UseSystemPasswordChar = false;
            this.bftxtxEmailPerfil.WordWrap = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 59;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(21, 71);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(118, 118);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 38;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // lblNombreUsuarioPerfil
            // 
            this.lblNombreUsuarioPerfil.AutoSize = true;
            this.lblNombreUsuarioPerfil.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombreUsuarioPerfil.Location = new System.Drawing.Point(175, 90);
            this.lblNombreUsuarioPerfil.Name = "lblNombreUsuarioPerfil";
            this.lblNombreUsuarioPerfil.Size = new System.Drawing.Size(251, 25);
            this.lblNombreUsuarioPerfil.TabIndex = 39;
            this.lblNombreUsuarioPerfil.Text = "NOMBRE DEL USUARIO";
            // 
            // lblTipoUsuarioPerfil
            // 
            this.lblTipoUsuarioPerfil.AutoSize = true;
            this.lblTipoUsuarioPerfil.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTipoUsuarioPerfil.Location = new System.Drawing.Point(212, 128);
            this.lblTipoUsuarioPerfil.Name = "lblTipoUsuarioPerfil";
            this.lblTipoUsuarioPerfil.Size = new System.Drawing.Size(172, 24);
            this.lblTipoUsuarioPerfil.TabIndex = 40;
            this.lblTipoUsuarioPerfil.Text = "TIPO DE USUARIO";
            // 
            // lblDatosPersonales
            // 
            this.lblDatosPersonales.AutoSize = true;
            this.lblDatosPersonales.Font = new System.Drawing.Font("Verdana", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDatosPersonales.Location = new System.Drawing.Point(193, 166);
            this.lblDatosPersonales.Name = "lblDatosPersonales";
            this.lblDatosPersonales.Size = new System.Drawing.Size(233, 23);
            this.lblDatosPersonales.TabIndex = 52;
            this.lblDatosPersonales.Text = "DATOS PERSONALES";
            // 
            // cmbGeneroPerfil
            // 
            this.cmbGeneroPerfil.FormattingEnabled = true;
            this.cmbGeneroPerfil.Location = new System.Drawing.Point(71, 463);
            this.cmbGeneroPerfil.Name = "cmbGeneroPerfil";
            this.cmbGeneroPerfil.Size = new System.Drawing.Size(161, 21);
            this.cmbGeneroPerfil.TabIndex = 51;
            // 
            // bflblGenero
            // 
            this.bflblGenero.AllowParentOverrides = false;
            this.bflblGenero.AutoEllipsis = false;
            this.bflblGenero.CursorType = null;
            this.bflblGenero.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblGenero.Location = new System.Drawing.Point(71, 442);
            this.bflblGenero.Name = "bflblGenero";
            this.bflblGenero.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblGenero.Size = new System.Drawing.Size(38, 15);
            this.bflblGenero.TabIndex = 50;
            this.bflblGenero.Text = "Genero";
            this.bflblGenero.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblGenero.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bflblFechaNacimiento
            // 
            this.bflblFechaNacimiento.AllowParentOverrides = false;
            this.bflblFechaNacimiento.AutoEllipsis = false;
            this.bflblFechaNacimiento.Cursor = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblFechaNacimiento.Location = new System.Drawing.Point(71, 366);
            this.bflblFechaNacimiento.Name = "bflblFechaNacimiento";
            this.bflblFechaNacimiento.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblFechaNacimiento.Size = new System.Drawing.Size(110, 15);
            this.bflblFechaNacimiento.TabIndex = 49;
            this.bflblFechaNacimiento.Text = "Fecha de nacimiento";
            this.bflblFechaNacimiento.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblFechaNacimiento.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bfdtpFechaNacimientoPerfil
            // 
            this.bfdtpFechaNacimientoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bfdtpFechaNacimientoPerfil.BorderColor = System.Drawing.Color.Silver;
            this.bfdtpFechaNacimientoPerfil.BorderRadius = 1;
            this.bfdtpFechaNacimientoPerfil.Color = System.Drawing.Color.Silver;
            this.bfdtpFechaNacimientoPerfil.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bfdtpFechaNacimientoPerfil.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bfdtpFechaNacimientoPerfil.DisabledColor = System.Drawing.Color.Gray;
            this.bfdtpFechaNacimientoPerfil.DisplayWeekNumbers = false;
            this.bfdtpFechaNacimientoPerfil.DPHeight = 0;
            this.bfdtpFechaNacimientoPerfil.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bfdtpFechaNacimientoPerfil.FillDatePicker = false;
            this.bfdtpFechaNacimientoPerfil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfdtpFechaNacimientoPerfil.ForeColor = System.Drawing.Color.Black;
            this.bfdtpFechaNacimientoPerfil.Icon = ((System.Drawing.Image)(resources.GetObject("bfdtpFechaNacimientoPerfil.Icon")));
            this.bfdtpFechaNacimientoPerfil.IconColor = System.Drawing.Color.Gray;
            this.bfdtpFechaNacimientoPerfil.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bfdtpFechaNacimientoPerfil.LeftTextMargin = 5;
            this.bfdtpFechaNacimientoPerfil.Location = new System.Drawing.Point(71, 380);
            this.bfdtpFechaNacimientoPerfil.MinimumSize = new System.Drawing.Size(4, 32);
            this.bfdtpFechaNacimientoPerfil.Name = "bfdtpFechaNacimientoPerfil";
            this.bfdtpFechaNacimientoPerfil.Size = new System.Drawing.Size(202, 32);
            this.bfdtpFechaNacimientoPerfil.TabIndex = 48;
            this.bfdtpFechaNacimientoPerfil.Value = new System.DateTime(2021, 10, 15, 13, 59, 0, 0);
            // 
            // bftxtDocumentoPerfil
            // 
            this.bftxtDocumentoPerfil.AcceptsReturn = false;
            this.bftxtDocumentoPerfil.AcceptsTab = false;
            this.bftxtDocumentoPerfil.AnimationSpeed = 200;
            this.bftxtDocumentoPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtDocumentoPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtDocumentoPerfil.AutoSizeHeight = true;
            this.bftxtDocumentoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtDocumentoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtDocumentoPerfil.BackgroundImage")));
            this.bftxtDocumentoPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtDocumentoPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtDocumentoPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtDocumentoPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtDocumentoPerfil.BorderRadius = 1;
            this.bftxtDocumentoPerfil.BorderThickness = 1;
            this.bftxtDocumentoPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtDocumentoPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bftxtDocumentoPerfil.DefaultText = "";
            this.bftxtDocumentoPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtDocumentoPerfil.HideSelection = true;
            this.bftxtDocumentoPerfil.IconLeft = null;
            this.bftxtDocumentoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.IconPadding = 10;
            this.bftxtDocumentoPerfil.IconRight = null;
            this.bftxtDocumentoPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.Lines = new string[0];
            this.bftxtDocumentoPerfil.Location = new System.Drawing.Point(338, 373);
            this.bftxtDocumentoPerfil.MaxLength = 32767;
            this.bftxtDocumentoPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtDocumentoPerfil.Modified = false;
            this.bftxtDocumentoPerfil.Multiline = false;
            this.bftxtDocumentoPerfil.Name = "bftxtDocumentoPerfil";
            stateProperties113.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties113.FillColor = System.Drawing.Color.Empty;
            stateProperties113.ForeColor = System.Drawing.Color.Empty;
            stateProperties113.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnActiveState = stateProperties113;
            stateProperties114.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties114.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties114.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties114.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtDocumentoPerfil.OnDisabledState = stateProperties114;
            stateProperties115.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties115.FillColor = System.Drawing.Color.Empty;
            stateProperties115.ForeColor = System.Drawing.Color.Empty;
            stateProperties115.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnHoverState = stateProperties115;
            stateProperties116.BorderColor = System.Drawing.Color.Silver;
            stateProperties116.FillColor = System.Drawing.Color.White;
            stateProperties116.ForeColor = System.Drawing.Color.Empty;
            stateProperties116.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnIdleState = stateProperties116;
            this.bftxtDocumentoPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtDocumentoPerfil.PasswordChar = '\0';
            this.bftxtDocumentoPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtDocumentoPerfil.PlaceholderText = "Documento de identidad";
            this.bftxtDocumentoPerfil.ReadOnly = false;
            this.bftxtDocumentoPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtDocumentoPerfil.SelectedText = "";
            this.bftxtDocumentoPerfil.SelectionLength = 0;
            this.bftxtDocumentoPerfil.SelectionStart = 0;
            this.bftxtDocumentoPerfil.ShortcutsEnabled = true;
            this.bftxtDocumentoPerfil.Size = new System.Drawing.Size(193, 39);
            this.bftxtDocumentoPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtDocumentoPerfil.TabIndex = 47;
            this.bftxtDocumentoPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bftxtDocumentoPerfil.TextMarginBottom = 0;
            this.bftxtDocumentoPerfil.TextMarginLeft = 3;
            this.bftxtDocumentoPerfil.TextMarginTop = 1;
            this.bftxtDocumentoPerfil.TextPlaceholder = "Documento de identidad";
            this.bftxtDocumentoPerfil.UseSystemPasswordChar = false;
            this.bftxtDocumentoPerfil.WordWrap = true;
            // 
            // bftxtSegundoApellidoperfil
            // 
            this.bftxtSegundoApellidoperfil.AcceptsReturn = false;
            this.bftxtSegundoApellidoperfil.AcceptsTab = false;
            this.bftxtSegundoApellidoperfil.AnimationSpeed = 200;
            this.bftxtSegundoApellidoperfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoApellidoperfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoApellidoperfil.AutoSizeHeight = true;
            this.bftxtSegundoApellidoperfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoApellidoperfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoApellidoperfil.BackgroundImage")));
            this.bftxtSegundoApellidoperfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoApellidoperfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoApellidoperfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoApellidoperfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoApellidoperfil.BorderRadius = 1;
            this.bftxtSegundoApellidoperfil.BorderThickness = 1;
            this.bftxtSegundoApellidoperfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoApellidoperfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoApellidoperfil.DefaultText = "";
            this.bftxtSegundoApellidoperfil.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoApellidoperfil.HideSelection = true;
            this.bftxtSegundoApellidoperfil.IconLeft = null;
            this.bftxtSegundoApellidoperfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.IconPadding = 10;
            this.bftxtSegundoApellidoperfil.IconRight = null;
            this.bftxtSegundoApellidoperfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.Lines = new string[0];
            this.bftxtSegundoApellidoperfil.Location = new System.Drawing.Point(338, 293);
            this.bftxtSegundoApellidoperfil.MaxLength = 32767;
            this.bftxtSegundoApellidoperfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoApellidoperfil.Modified = false;
            this.bftxtSegundoApellidoperfil.Multiline = false;
            this.bftxtSegundoApellidoperfil.Name = "bftxtSegundoApellidoperfil";
            stateProperties117.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties117.FillColor = System.Drawing.Color.Empty;
            stateProperties117.ForeColor = System.Drawing.Color.Empty;
            stateProperties117.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnActiveState = stateProperties117;
            stateProperties118.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties118.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties118.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties118.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoApellidoperfil.OnDisabledState = stateProperties118;
            stateProperties119.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties119.FillColor = System.Drawing.Color.Empty;
            stateProperties119.ForeColor = System.Drawing.Color.Empty;
            stateProperties119.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnHoverState = stateProperties119;
            stateProperties120.BorderColor = System.Drawing.Color.Silver;
            stateProperties120.FillColor = System.Drawing.Color.White;
            stateProperties120.ForeColor = System.Drawing.Color.Empty;
            stateProperties120.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnIdleState = stateProperties120;
            this.bftxtSegundoApellidoperfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoApellidoperfil.PasswordChar = '\0';
            this.bftxtSegundoApellidoperfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoApellidoperfil.PlaceholderText = "Segundo apellido";
            this.bftxtSegundoApellidoperfil.ReadOnly = false;
            this.bftxtSegundoApellidoperfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoApellidoperfil.SelectedText = "";
            this.bftxtSegundoApellidoperfil.SelectionLength = 0;
            this.bftxtSegundoApellidoperfil.SelectionStart = 0;
            this.bftxtSegundoApellidoperfil.ShortcutsEnabled = true;
            this.bftxtSegundoApellidoperfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoApellidoperfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoApellidoperfil.TabIndex = 46;
            this.bftxtSegundoApellidoperfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoApellidoperfil.TextMarginBottom = 0;
            this.bftxtSegundoApellidoperfil.TextMarginLeft = 3;
            this.bftxtSegundoApellidoperfil.TextMarginTop = 1;
            this.bftxtSegundoApellidoperfil.TextPlaceholder = "Segundo apellido";
            this.bftxtSegundoApellidoperfil.UseSystemPasswordChar = false;
            this.bftxtSegundoApellidoperfil.WordWrap = true;
            // 
            // bftxtPrimerApellidoPerfil
            // 
            this.bftxtPrimerApellidoPerfil.AcceptsReturn = false;
            this.bftxtPrimerApellidoPerfil.AcceptsTab = false;
            this.bftxtPrimerApellidoPerfil.AnimationSpeed = 200;
            this.bftxtPrimerApellidoPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerApellidoPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerApellidoPerfil.AutoSizeHeight = true;
            this.bftxtPrimerApellidoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerApellidoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerApellidoPerfil.BackgroundImage")));
            this.bftxtPrimerApellidoPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerApellidoPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerApellidoPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerApellidoPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerApellidoPerfil.BorderRadius = 1;
            this.bftxtPrimerApellidoPerfil.BorderThickness = 1;
            this.bftxtPrimerApellidoPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerApellidoPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerApellidoPerfil.DefaultText = "";
            this.bftxtPrimerApellidoPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerApellidoPerfil.HideSelection = true;
            this.bftxtPrimerApellidoPerfil.IconLeft = null;
            this.bftxtPrimerApellidoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.IconPadding = 10;
            this.bftxtPrimerApellidoPerfil.IconRight = null;
            this.bftxtPrimerApellidoPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.Lines = new string[0];
            this.bftxtPrimerApellidoPerfil.Location = new System.Drawing.Point(71, 293);
            this.bftxtPrimerApellidoPerfil.MaxLength = 32767;
            this.bftxtPrimerApellidoPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerApellidoPerfil.Modified = false;
            this.bftxtPrimerApellidoPerfil.Multiline = false;
            this.bftxtPrimerApellidoPerfil.Name = "bftxtPrimerApellidoPerfil";
            stateProperties121.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties121.FillColor = System.Drawing.Color.Empty;
            stateProperties121.ForeColor = System.Drawing.Color.Empty;
            stateProperties121.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnActiveState = stateProperties121;
            stateProperties122.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties122.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties122.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties122.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerApellidoPerfil.OnDisabledState = stateProperties122;
            stateProperties123.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties123.FillColor = System.Drawing.Color.Empty;
            stateProperties123.ForeColor = System.Drawing.Color.Empty;
            stateProperties123.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnHoverState = stateProperties123;
            stateProperties124.BorderColor = System.Drawing.Color.Silver;
            stateProperties124.FillColor = System.Drawing.Color.White;
            stateProperties124.ForeColor = System.Drawing.Color.Empty;
            stateProperties124.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnIdleState = stateProperties124;
            this.bftxtPrimerApellidoPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerApellidoPerfil.PasswordChar = '\0';
            this.bftxtPrimerApellidoPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerApellidoPerfil.PlaceholderText = "Primer Apellido";
            this.bftxtPrimerApellidoPerfil.ReadOnly = false;
            this.bftxtPrimerApellidoPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerApellidoPerfil.SelectedText = "";
            this.bftxtPrimerApellidoPerfil.SelectionLength = 0;
            this.bftxtPrimerApellidoPerfil.SelectionStart = 0;
            this.bftxtPrimerApellidoPerfil.ShortcutsEnabled = true;
            this.bftxtPrimerApellidoPerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerApellidoPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerApellidoPerfil.TabIndex = 45;
            this.bftxtPrimerApellidoPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerApellidoPerfil.TextMarginBottom = 0;
            this.bftxtPrimerApellidoPerfil.TextMarginLeft = 3;
            this.bftxtPrimerApellidoPerfil.TextMarginTop = 1;
            this.bftxtPrimerApellidoPerfil.TextPlaceholder = "Primer Apellido";
            this.bftxtPrimerApellidoPerfil.UseSystemPasswordChar = false;
            this.bftxtPrimerApellidoPerfil.WordWrap = true;
            // 
            // bftxtSegundoNombrePerfil
            // 
            this.bftxtSegundoNombrePerfil.AcceptsReturn = false;
            this.bftxtSegundoNombrePerfil.AcceptsTab = false;
            this.bftxtSegundoNombrePerfil.AnimationSpeed = 200;
            this.bftxtSegundoNombrePerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoNombrePerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoNombrePerfil.AutoSizeHeight = true;
            this.bftxtSegundoNombrePerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoNombrePerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoNombrePerfil.BackgroundImage")));
            this.bftxtSegundoNombrePerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoNombrePerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoNombrePerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoNombrePerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoNombrePerfil.BorderRadius = 1;
            this.bftxtSegundoNombrePerfil.BorderThickness = 1;
            this.bftxtSegundoNombrePerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoNombrePerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoNombrePerfil.DefaultText = "";
            this.bftxtSegundoNombrePerfil.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoNombrePerfil.HideSelection = true;
            this.bftxtSegundoNombrePerfil.IconLeft = null;
            this.bftxtSegundoNombrePerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.IconPadding = 10;
            this.bftxtSegundoNombrePerfil.IconRight = null;
            this.bftxtSegundoNombrePerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.Lines = new string[0];
            this.bftxtSegundoNombrePerfil.Location = new System.Drawing.Point(338, 218);
            this.bftxtSegundoNombrePerfil.MaxLength = 32767;
            this.bftxtSegundoNombrePerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoNombrePerfil.Modified = false;
            this.bftxtSegundoNombrePerfil.Multiline = false;
            this.bftxtSegundoNombrePerfil.Name = "bftxtSegundoNombrePerfil";
            stateProperties125.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties125.FillColor = System.Drawing.Color.Empty;
            stateProperties125.ForeColor = System.Drawing.Color.Empty;
            stateProperties125.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnActiveState = stateProperties125;
            stateProperties126.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties126.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties126.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties126.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoNombrePerfil.OnDisabledState = stateProperties126;
            stateProperties127.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties127.FillColor = System.Drawing.Color.Empty;
            stateProperties127.ForeColor = System.Drawing.Color.Empty;
            stateProperties127.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnHoverState = stateProperties127;
            stateProperties128.BorderColor = System.Drawing.Color.Silver;
            stateProperties128.FillColor = System.Drawing.Color.White;
            stateProperties128.ForeColor = System.Drawing.Color.Empty;
            stateProperties128.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnIdleState = stateProperties128;
            this.bftxtSegundoNombrePerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoNombrePerfil.PasswordChar = '\0';
            this.bftxtSegundoNombrePerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoNombrePerfil.PlaceholderText = "Segundo nombre";
            this.bftxtSegundoNombrePerfil.ReadOnly = false;
            this.bftxtSegundoNombrePerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoNombrePerfil.SelectedText = "";
            this.bftxtSegundoNombrePerfil.SelectionLength = 0;
            this.bftxtSegundoNombrePerfil.SelectionStart = 0;
            this.bftxtSegundoNombrePerfil.ShortcutsEnabled = true;
            this.bftxtSegundoNombrePerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoNombrePerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoNombrePerfil.TabIndex = 44;
            this.bftxtSegundoNombrePerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoNombrePerfil.TextMarginBottom = 0;
            this.bftxtSegundoNombrePerfil.TextMarginLeft = 3;
            this.bftxtSegundoNombrePerfil.TextMarginTop = 1;
            this.bftxtSegundoNombrePerfil.TextPlaceholder = "Segundo nombre";
            this.bftxtSegundoNombrePerfil.UseSystemPasswordChar = false;
            this.bftxtSegundoNombrePerfil.WordWrap = true;
            // 
            // bftxtPrimerNombrePerfil
            // 
            this.bftxtPrimerNombrePerfil.AcceptsReturn = false;
            this.bftxtPrimerNombrePerfil.AcceptsTab = false;
            this.bftxtPrimerNombrePerfil.AnimationSpeed = 200;
            this.bftxtPrimerNombrePerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerNombrePerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerNombrePerfil.AutoSizeHeight = true;
            this.bftxtPrimerNombrePerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerNombrePerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerNombrePerfil.BackgroundImage")));
            this.bftxtPrimerNombrePerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerNombrePerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerNombrePerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerNombrePerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerNombrePerfil.BorderRadius = 1;
            this.bftxtPrimerNombrePerfil.BorderThickness = 1;
            this.bftxtPrimerNombrePerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerNombrePerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerNombrePerfil.DefaultText = "";
            this.bftxtPrimerNombrePerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerNombrePerfil.HideSelection = true;
            this.bftxtPrimerNombrePerfil.IconLeft = null;
            this.bftxtPrimerNombrePerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.IconPadding = 10;
            this.bftxtPrimerNombrePerfil.IconRight = null;
            this.bftxtPrimerNombrePerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.Lines = new string[0];
            this.bftxtPrimerNombrePerfil.Location = new System.Drawing.Point(71, 218);
            this.bftxtPrimerNombrePerfil.MaxLength = 32767;
            this.bftxtPrimerNombrePerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerNombrePerfil.Modified = false;
            this.bftxtPrimerNombrePerfil.Multiline = false;
            this.bftxtPrimerNombrePerfil.Name = "bftxtPrimerNombrePerfil";
            stateProperties129.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties129.FillColor = System.Drawing.Color.Empty;
            stateProperties129.ForeColor = System.Drawing.Color.Empty;
            stateProperties129.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnActiveState = stateProperties129;
            stateProperties130.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties130.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties130.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties130.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerNombrePerfil.OnDisabledState = stateProperties130;
            stateProperties131.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties131.FillColor = System.Drawing.Color.Empty;
            stateProperties131.ForeColor = System.Drawing.Color.Empty;
            stateProperties131.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnHoverState = stateProperties131;
            stateProperties132.BorderColor = System.Drawing.Color.Silver;
            stateProperties132.FillColor = System.Drawing.Color.White;
            stateProperties132.ForeColor = System.Drawing.Color.Empty;
            stateProperties132.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnIdleState = stateProperties132;
            this.bftxtPrimerNombrePerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerNombrePerfil.PasswordChar = '\0';
            this.bftxtPrimerNombrePerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerNombrePerfil.PlaceholderText = "Primer nombre";
            this.bftxtPrimerNombrePerfil.ReadOnly = false;
            this.bftxtPrimerNombrePerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerNombrePerfil.SelectedText = "";
            this.bftxtPrimerNombrePerfil.SelectionLength = 0;
            this.bftxtPrimerNombrePerfil.SelectionStart = 0;
            this.bftxtPrimerNombrePerfil.ShortcutsEnabled = true;
            this.bftxtPrimerNombrePerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerNombrePerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerNombrePerfil.TabIndex = 43;
            this.bftxtPrimerNombrePerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerNombrePerfil.TextMarginBottom = 0;
            this.bftxtPrimerNombrePerfil.TextMarginLeft = 3;
            this.bftxtPrimerNombrePerfil.TextMarginTop = 1;
            this.bftxtPrimerNombrePerfil.TextPlaceholder = "Primer nombre";
            this.bftxtPrimerNombrePerfil.UseSystemPasswordChar = false;
            this.bftxtPrimerNombrePerfil.WordWrap = true;
            // 
            // bunifuVScrollBar1
            // 
            this.bunifuVScrollBar1.AllowCursorChanges = true;
            this.bunifuVScrollBar1.AllowHomeEndKeysDetection = false;
            this.bunifuVScrollBar1.AllowIncrementalClickMoves = true;
            this.bunifuVScrollBar1.AllowMouseDownEffects = true;
            this.bunifuVScrollBar1.AllowMouseHoverEffects = true;
            this.bunifuVScrollBar1.AllowScrollingAnimations = true;
            this.bunifuVScrollBar1.AllowScrollKeysDetection = true;
            this.bunifuVScrollBar1.AllowScrollOptionsMenu = true;
            this.bunifuVScrollBar1.AllowShrinkingOnFocusLost = false;
            this.bunifuVScrollBar1.BackgroundColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuVScrollBar1.BackgroundImage")));
            this.bunifuVScrollBar1.BindingContainer = this;
            this.bunifuVScrollBar1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.BorderRadius = 14;
            this.bunifuVScrollBar1.BorderThickness = 1;
            this.bunifuVScrollBar1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuVScrollBar1.DurationBeforeShrink = 2000;
            this.bunifuVScrollBar1.LargeChange = 50;
            this.bunifuVScrollBar1.Location = new System.Drawing.Point(578, 0);
            this.bunifuVScrollBar1.Maximum = 150;
            this.bunifuVScrollBar1.Minimum = 0;
            this.bunifuVScrollBar1.MinimumThumbLength = 18;
            this.bunifuVScrollBar1.Name = "bunifuVScrollBar1";
            this.bunifuVScrollBar1.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.bunifuVScrollBar1.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.ScrollBarColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar1.ShrinkSizeLimit = 3;
            this.bunifuVScrollBar1.Size = new System.Drawing.Size(14, 747);
            this.bunifuVScrollBar1.SmallChange = 1;
            this.bunifuVScrollBar1.TabIndex = 53;
            this.bunifuVScrollBar1.ThumbColor = System.Drawing.Color.Gray;
            this.bunifuVScrollBar1.ThumbLength = 247;
            this.bunifuVScrollBar1.ThumbMargin = 1;
            this.bunifuVScrollBar1.ThumbStyle = Bunifu.UI.WinForms.BunifuVScrollBar.ThumbStyles.Proportional;
            this.bunifuVScrollBar1.Value = 0;
            // 
            // frmPerfil
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(592, 747);
            this.Controls.Add(this.bunifuVScrollBar1);
            this.Controls.Add(this.lblDatosPersonales);
            this.Controls.Add(this.cmbGeneroPerfil);
            this.Controls.Add(this.bflblGenero);
            this.Controls.Add(this.bflblFechaNacimiento);
            this.Controls.Add(this.bfdtpFechaNacimientoPerfil);
            this.Controls.Add(this.bftxtDocumentoPerfil);
            this.Controls.Add(this.bftxtSegundoApellidoperfil);
            this.Controls.Add(this.bftxtPrimerApellidoPerfil);
            this.Controls.Add(this.bftxtSegundoNombrePerfil);
            this.Controls.Add(this.bftxtPrimerNombrePerfil);
            this.Controls.Add(this.lblTipoUsuarioPerfil);
            this.Controls.Add(this.lblNombreUsuarioPerfil);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bftxtConfirmPasswordPerfil);
            this.Controls.Add(this.bftxtPasswordPerfil);
            this.Controls.Add(this.bftxtConfirmacionCelularPerfil);
            this.Controls.Add(this.bftxtNumeroCelPerfil);
            this.Controls.Add(this.bftxtConfirmarEmailPerfil);
            this.Controls.Add(this.bftxtxEmailPerfil);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmPerfil";
            this.Text = "frmPerfil";
            this.Load += new System.EventHandler(this.frmPerfil_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmPasswordPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPasswordPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmacionCelularPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtNumeroCelPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmarEmailPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxEmailPerfil;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Label lblNombreUsuarioPerfil;
        private System.Windows.Forms.Label lblTipoUsuarioPerfil;
        private System.Windows.Forms.Label lblDatosPersonales;
        private System.Windows.Forms.ComboBox cmbGeneroPerfil;
        private Bunifu.UI.WinForms.BunifuLabel bflblGenero;
        private Bunifu.UI.WinForms.BunifuLabel bflblFechaNacimiento;
        private Bunifu.UI.WinForms.BunifuDatePicker bfdtpFechaNacimientoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtDocumentoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoApellidoperfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerApellidoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoNombrePerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerNombrePerfil;
        private Bunifu.UI.WinForms.BunifuVScrollBar bunifuVScrollBar1;
    }
}