
namespace final_motoDix.Vistas
{
    partial class frmPerfil
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPerfil));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bftxtConfirmPasswordPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPasswordPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmarEmailPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxEmailPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.lblNombreUsuarioPerfil = new System.Windows.Forms.Label();
            this.lblTipoUsuarioPerfil = new System.Windows.Forms.Label();
            this.lblDatosPersonales = new System.Windows.Forms.Label();
            this.cmbGeneroPerfil = new System.Windows.Forms.ComboBox();
            this.bflblGenero = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblFechaNacimiento = new Bunifu.UI.WinForms.BunifuLabel();
            this.bfdtpFechaNacimientoPerfil = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bftxtDocumentoPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoApellidoperfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerApellidoPerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoNombrePerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerNombrePerfil = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bfbtnActualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panelPerfil = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.panelPerfil.SuspendLayout();
            this.SuspendLayout();
            // 
            // bftxtConfirmPasswordPerfil
            // 
            this.bftxtConfirmPasswordPerfil.AcceptsReturn = false;
            this.bftxtConfirmPasswordPerfil.AcceptsTab = false;
            this.bftxtConfirmPasswordPerfil.AnimationSpeed = 200;
            this.bftxtConfirmPasswordPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmPasswordPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmPasswordPerfil.AutoSizeHeight = true;
            this.bftxtConfirmPasswordPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmPasswordPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmPasswordPerfil.BackgroundImage")));
            this.bftxtConfirmPasswordPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmPasswordPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmPasswordPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmPasswordPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmPasswordPerfil.BorderRadius = 1;
            this.bftxtConfirmPasswordPerfil.BorderThickness = 1;
            this.bftxtConfirmPasswordPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmPasswordPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmPasswordPerfil.DefaultText = "";
            this.bftxtConfirmPasswordPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmPasswordPerfil.HideSelection = true;
            this.bftxtConfirmPasswordPerfil.IconLeft = null;
            this.bftxtConfirmPasswordPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.IconPadding = 10;
            this.bftxtConfirmPasswordPerfil.IconRight = null;
            this.bftxtConfirmPasswordPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPasswordPerfil.Lines = new string[0];
            this.bftxtConfirmPasswordPerfil.Location = new System.Drawing.Point(316, 440);
            this.bftxtConfirmPasswordPerfil.MaxLength = 32767;
            this.bftxtConfirmPasswordPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmPasswordPerfil.Modified = false;
            this.bftxtConfirmPasswordPerfil.Multiline = false;
            this.bftxtConfirmPasswordPerfil.Name = "bftxtConfirmPasswordPerfil";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmPasswordPerfil.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPasswordPerfil.OnIdleState = stateProperties40;
            this.bftxtConfirmPasswordPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmPasswordPerfil.PasswordChar = '*';
            this.bftxtConfirmPasswordPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmPasswordPerfil.PlaceholderText = "Confirmar Contraseña";
            this.bftxtConfirmPasswordPerfil.ReadOnly = false;
            this.bftxtConfirmPasswordPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmPasswordPerfil.SelectedText = "";
            this.bftxtConfirmPasswordPerfil.SelectionLength = 0;
            this.bftxtConfirmPasswordPerfil.SelectionStart = 0;
            this.bftxtConfirmPasswordPerfil.ShortcutsEnabled = true;
            this.bftxtConfirmPasswordPerfil.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmPasswordPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmPasswordPerfil.TabIndex = 36;
            this.bftxtConfirmPasswordPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmPasswordPerfil.TextMarginBottom = 0;
            this.bftxtConfirmPasswordPerfil.TextMarginLeft = 3;
            this.bftxtConfirmPasswordPerfil.TextMarginTop = 1;
            this.bftxtConfirmPasswordPerfil.TextPlaceholder = "Confirmar Contraseña";
            this.bftxtConfirmPasswordPerfil.UseSystemPasswordChar = false;
            this.bftxtConfirmPasswordPerfil.WordWrap = true;
            // 
            // bftxtPasswordPerfil
            // 
            this.bftxtPasswordPerfil.AcceptsReturn = false;
            this.bftxtPasswordPerfil.AcceptsTab = false;
            this.bftxtPasswordPerfil.AnimationSpeed = 200;
            this.bftxtPasswordPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPasswordPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPasswordPerfil.AutoSizeHeight = true;
            this.bftxtPasswordPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPasswordPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPasswordPerfil.BackgroundImage")));
            this.bftxtPasswordPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPasswordPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPasswordPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPasswordPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPasswordPerfil.BorderRadius = 1;
            this.bftxtPasswordPerfil.BorderThickness = 1;
            this.bftxtPasswordPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPasswordPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPasswordPerfil.DefaultText = "";
            this.bftxtPasswordPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPasswordPerfil.HideSelection = true;
            this.bftxtPasswordPerfil.IconLeft = null;
            this.bftxtPasswordPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.IconPadding = 10;
            this.bftxtPasswordPerfil.IconRight = null;
            this.bftxtPasswordPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPasswordPerfil.Lines = new string[0];
            this.bftxtPasswordPerfil.Location = new System.Drawing.Point(49, 440);
            this.bftxtPasswordPerfil.MaxLength = 32767;
            this.bftxtPasswordPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPasswordPerfil.Modified = false;
            this.bftxtPasswordPerfil.Multiline = false;
            this.bftxtPasswordPerfil.Name = "bftxtPasswordPerfil";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPasswordPerfil.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPasswordPerfil.OnIdleState = stateProperties44;
            this.bftxtPasswordPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPasswordPerfil.PasswordChar = '*';
            this.bftxtPasswordPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPasswordPerfil.PlaceholderText = "Contraseña";
            this.bftxtPasswordPerfil.ReadOnly = false;
            this.bftxtPasswordPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPasswordPerfil.SelectedText = "";
            this.bftxtPasswordPerfil.SelectionLength = 0;
            this.bftxtPasswordPerfil.SelectionStart = 0;
            this.bftxtPasswordPerfil.ShortcutsEnabled = true;
            this.bftxtPasswordPerfil.Size = new System.Drawing.Size(226, 37);
            this.bftxtPasswordPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPasswordPerfil.TabIndex = 35;
            this.bftxtPasswordPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPasswordPerfil.TextMarginBottom = 0;
            this.bftxtPasswordPerfil.TextMarginLeft = 3;
            this.bftxtPasswordPerfil.TextMarginTop = 1;
            this.bftxtPasswordPerfil.TextPlaceholder = "Contraseña";
            this.bftxtPasswordPerfil.UseSystemPasswordChar = false;
            this.bftxtPasswordPerfil.WordWrap = true;
            // 
            // bftxtConfirmarEmailPerfil
            // 
            this.bftxtConfirmarEmailPerfil.AcceptsReturn = false;
            this.bftxtConfirmarEmailPerfil.AcceptsTab = false;
            this.bftxtConfirmarEmailPerfil.AnimationSpeed = 200;
            this.bftxtConfirmarEmailPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmarEmailPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmarEmailPerfil.AutoSizeHeight = true;
            this.bftxtConfirmarEmailPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmarEmailPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmarEmailPerfil.BackgroundImage")));
            this.bftxtConfirmarEmailPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmarEmailPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmarEmailPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmarEmailPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmailPerfil.BorderRadius = 1;
            this.bftxtConfirmarEmailPerfil.BorderThickness = 1;
            this.bftxtConfirmarEmailPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmarEmailPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmarEmailPerfil.DefaultText = "";
            this.bftxtConfirmarEmailPerfil.Enabled = false;
            this.bftxtConfirmarEmailPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmarEmailPerfil.HideSelection = true;
            this.bftxtConfirmarEmailPerfil.IconLeft = null;
            this.bftxtConfirmarEmailPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.IconPadding = 10;
            this.bftxtConfirmarEmailPerfil.IconRight = null;
            this.bftxtConfirmarEmailPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmailPerfil.Lines = new string[0];
            this.bftxtConfirmarEmailPerfil.Location = new System.Drawing.Point(316, 319);
            this.bftxtConfirmarEmailPerfil.MaxLength = 32767;
            this.bftxtConfirmarEmailPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmarEmailPerfil.Modified = false;
            this.bftxtConfirmarEmailPerfil.Multiline = false;
            this.bftxtConfirmarEmailPerfil.Name = "bftxtConfirmarEmailPerfil";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmarEmailPerfil.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmailPerfil.OnIdleState = stateProperties48;
            this.bftxtConfirmarEmailPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmarEmailPerfil.PasswordChar = '\0';
            this.bftxtConfirmarEmailPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmailPerfil.PlaceholderText = "Confirme e-mail";
            this.bftxtConfirmarEmailPerfil.ReadOnly = false;
            this.bftxtConfirmarEmailPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmarEmailPerfil.SelectedText = "";
            this.bftxtConfirmarEmailPerfil.SelectionLength = 0;
            this.bftxtConfirmarEmailPerfil.SelectionStart = 0;
            this.bftxtConfirmarEmailPerfil.ShortcutsEnabled = true;
            this.bftxtConfirmarEmailPerfil.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmarEmailPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmarEmailPerfil.TabIndex = 32;
            this.bftxtConfirmarEmailPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmarEmailPerfil.TextMarginBottom = 0;
            this.bftxtConfirmarEmailPerfil.TextMarginLeft = 3;
            this.bftxtConfirmarEmailPerfil.TextMarginTop = 1;
            this.bftxtConfirmarEmailPerfil.TextPlaceholder = "Confirme e-mail";
            this.bftxtConfirmarEmailPerfil.UseSystemPasswordChar = false;
            this.bftxtConfirmarEmailPerfil.WordWrap = true;
            // 
            // bftxtxEmailPerfil
            // 
            this.bftxtxEmailPerfil.AcceptsReturn = false;
            this.bftxtxEmailPerfil.AcceptsTab = false;
            this.bftxtxEmailPerfil.AnimationSpeed = 200;
            this.bftxtxEmailPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxEmailPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxEmailPerfil.AutoSizeHeight = true;
            this.bftxtxEmailPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxEmailPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxEmailPerfil.BackgroundImage")));
            this.bftxtxEmailPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxEmailPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxEmailPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxEmailPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxEmailPerfil.BorderRadius = 1;
            this.bftxtxEmailPerfil.BorderThickness = 1;
            this.bftxtxEmailPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxEmailPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxEmailPerfil.DefaultText = "";
            this.bftxtxEmailPerfil.Enabled = false;
            this.bftxtxEmailPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtxEmailPerfil.HideSelection = true;
            this.bftxtxEmailPerfil.IconLeft = null;
            this.bftxtxEmailPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.IconPadding = 10;
            this.bftxtxEmailPerfil.IconRight = null;
            this.bftxtxEmailPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmailPerfil.Lines = new string[0];
            this.bftxtxEmailPerfil.Location = new System.Drawing.Point(51, 319);
            this.bftxtxEmailPerfil.MaxLength = 32767;
            this.bftxtxEmailPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxEmailPerfil.Modified = false;
            this.bftxtxEmailPerfil.Multiline = false;
            this.bftxtxEmailPerfil.Name = "bftxtxEmailPerfil";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxEmailPerfil.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmailPerfil.OnIdleState = stateProperties52;
            this.bftxtxEmailPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxEmailPerfil.PasswordChar = '\0';
            this.bftxtxEmailPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxEmailPerfil.PlaceholderText = "E-mail";
            this.bftxtxEmailPerfil.ReadOnly = false;
            this.bftxtxEmailPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxEmailPerfil.SelectedText = "";
            this.bftxtxEmailPerfil.SelectionLength = 0;
            this.bftxtxEmailPerfil.SelectionStart = 0;
            this.bftxtxEmailPerfil.ShortcutsEnabled = true;
            this.bftxtxEmailPerfil.Size = new System.Drawing.Size(226, 37);
            this.bftxtxEmailPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxEmailPerfil.TabIndex = 31;
            this.bftxtxEmailPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxEmailPerfil.TextMarginBottom = 0;
            this.bftxtxEmailPerfil.TextMarginLeft = 3;
            this.bftxtxEmailPerfil.TextMarginTop = 1;
            this.bftxtxEmailPerfil.TextPlaceholder = "E-mail";
            this.bftxtxEmailPerfil.UseSystemPasswordChar = false;
            this.bftxtxEmailPerfil.WordWrap = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 59;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(29, 62);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(118, 118);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 38;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click);
            // 
            // lblNombreUsuarioPerfil
            // 
            this.lblNombreUsuarioPerfil.AutoSize = true;
            this.lblNombreUsuarioPerfil.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombreUsuarioPerfil.Location = new System.Drawing.Point(175, 90);
            this.lblNombreUsuarioPerfil.Name = "lblNombreUsuarioPerfil";
            this.lblNombreUsuarioPerfil.Size = new System.Drawing.Size(251, 25);
            this.lblNombreUsuarioPerfil.TabIndex = 39;
            this.lblNombreUsuarioPerfil.Text = "NOMBRE DEL USUARIO";
            // 
            // lblTipoUsuarioPerfil
            // 
            this.lblTipoUsuarioPerfil.AutoSize = true;
            this.lblTipoUsuarioPerfil.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTipoUsuarioPerfil.Location = new System.Drawing.Point(212, 128);
            this.lblTipoUsuarioPerfil.Name = "lblTipoUsuarioPerfil";
            this.lblTipoUsuarioPerfil.Size = new System.Drawing.Size(172, 24);
            this.lblTipoUsuarioPerfil.TabIndex = 40;
            this.lblTipoUsuarioPerfil.Text = "TIPO DE USUARIO";
            // 
            // lblDatosPersonales
            // 
            this.lblDatosPersonales.AutoSize = true;
            this.lblDatosPersonales.Font = new System.Drawing.Font("Verdana", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDatosPersonales.Location = new System.Drawing.Point(193, 166);
            this.lblDatosPersonales.Name = "lblDatosPersonales";
            this.lblDatosPersonales.Size = new System.Drawing.Size(233, 23);
            this.lblDatosPersonales.TabIndex = 52;
            this.lblDatosPersonales.Text = "DATOS PERSONALES";
            // 
            // cmbGeneroPerfil
            // 
            this.cmbGeneroPerfil.FormattingEnabled = true;
            this.cmbGeneroPerfil.Location = new System.Drawing.Point(49, 260);
            this.cmbGeneroPerfil.Name = "cmbGeneroPerfil";
            this.cmbGeneroPerfil.Size = new System.Drawing.Size(161, 21);
            this.cmbGeneroPerfil.TabIndex = 51;
            // 
            // bflblGenero
            // 
            this.bflblGenero.AllowParentOverrides = false;
            this.bflblGenero.AutoEllipsis = false;
            this.bflblGenero.CursorType = null;
            this.bflblGenero.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblGenero.Location = new System.Drawing.Point(49, 239);
            this.bflblGenero.Name = "bflblGenero";
            this.bflblGenero.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblGenero.Size = new System.Drawing.Size(38, 15);
            this.bflblGenero.TabIndex = 50;
            this.bflblGenero.Text = "Genero";
            this.bflblGenero.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblGenero.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bflblFechaNacimiento
            // 
            this.bflblFechaNacimiento.AllowParentOverrides = false;
            this.bflblFechaNacimiento.AutoEllipsis = false;
            this.bflblFechaNacimiento.Cursor = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblFechaNacimiento.Location = new System.Drawing.Point(49, 163);
            this.bflblFechaNacimiento.Name = "bflblFechaNacimiento";
            this.bflblFechaNacimiento.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblFechaNacimiento.Size = new System.Drawing.Size(110, 15);
            this.bflblFechaNacimiento.TabIndex = 49;
            this.bflblFechaNacimiento.Text = "Fecha de nacimiento";
            this.bflblFechaNacimiento.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblFechaNacimiento.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bfdtpFechaNacimientoPerfil
            // 
            this.bfdtpFechaNacimientoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bfdtpFechaNacimientoPerfil.BorderColor = System.Drawing.Color.Silver;
            this.bfdtpFechaNacimientoPerfil.BorderRadius = 1;
            this.bfdtpFechaNacimientoPerfil.Color = System.Drawing.Color.Silver;
            this.bfdtpFechaNacimientoPerfil.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bfdtpFechaNacimientoPerfil.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bfdtpFechaNacimientoPerfil.DisabledColor = System.Drawing.Color.Gray;
            this.bfdtpFechaNacimientoPerfil.DisplayWeekNumbers = false;
            this.bfdtpFechaNacimientoPerfil.DPHeight = 0;
            this.bfdtpFechaNacimientoPerfil.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bfdtpFechaNacimientoPerfil.Enabled = false;
            this.bfdtpFechaNacimientoPerfil.FillDatePicker = false;
            this.bfdtpFechaNacimientoPerfil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfdtpFechaNacimientoPerfil.ForeColor = System.Drawing.Color.Black;
            this.bfdtpFechaNacimientoPerfil.Icon = ((System.Drawing.Image)(resources.GetObject("bfdtpFechaNacimientoPerfil.Icon")));
            this.bfdtpFechaNacimientoPerfil.IconColor = System.Drawing.Color.Gray;
            this.bfdtpFechaNacimientoPerfil.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bfdtpFechaNacimientoPerfil.LeftTextMargin = 5;
            this.bfdtpFechaNacimientoPerfil.Location = new System.Drawing.Point(49, 177);
            this.bfdtpFechaNacimientoPerfil.MinimumSize = new System.Drawing.Size(4, 32);
            this.bfdtpFechaNacimientoPerfil.Name = "bfdtpFechaNacimientoPerfil";
            this.bfdtpFechaNacimientoPerfil.Size = new System.Drawing.Size(202, 32);
            this.bfdtpFechaNacimientoPerfil.TabIndex = 48;
            this.bfdtpFechaNacimientoPerfil.Value = new System.DateTime(2021, 10, 15, 13, 59, 0, 0);
            // 
            // bftxtDocumentoPerfil
            // 
            this.bftxtDocumentoPerfil.AcceptsReturn = false;
            this.bftxtDocumentoPerfil.AcceptsTab = false;
            this.bftxtDocumentoPerfil.AnimationSpeed = 200;
            this.bftxtDocumentoPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtDocumentoPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtDocumentoPerfil.AutoSizeHeight = true;
            this.bftxtDocumentoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtDocumentoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtDocumentoPerfil.BackgroundImage")));
            this.bftxtDocumentoPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtDocumentoPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtDocumentoPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtDocumentoPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtDocumentoPerfil.BorderRadius = 1;
            this.bftxtDocumentoPerfil.BorderThickness = 1;
            this.bftxtDocumentoPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtDocumentoPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bftxtDocumentoPerfil.DefaultText = "";
            this.bftxtDocumentoPerfil.Enabled = false;
            this.bftxtDocumentoPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtDocumentoPerfil.HideSelection = true;
            this.bftxtDocumentoPerfil.IconLeft = null;
            this.bftxtDocumentoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.IconPadding = 10;
            this.bftxtDocumentoPerfil.IconRight = null;
            this.bftxtDocumentoPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumentoPerfil.Lines = new string[0];
            this.bftxtDocumentoPerfil.Location = new System.Drawing.Point(316, 170);
            this.bftxtDocumentoPerfil.MaxLength = 32767;
            this.bftxtDocumentoPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtDocumentoPerfil.Modified = false;
            this.bftxtDocumentoPerfil.Multiline = false;
            this.bftxtDocumentoPerfil.Name = "bftxtDocumentoPerfil";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtDocumentoPerfil.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumentoPerfil.OnIdleState = stateProperties56;
            this.bftxtDocumentoPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtDocumentoPerfil.PasswordChar = '\0';
            this.bftxtDocumentoPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtDocumentoPerfil.PlaceholderText = "Documento de identidad";
            this.bftxtDocumentoPerfil.ReadOnly = false;
            this.bftxtDocumentoPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtDocumentoPerfil.SelectedText = "";
            this.bftxtDocumentoPerfil.SelectionLength = 0;
            this.bftxtDocumentoPerfil.SelectionStart = 0;
            this.bftxtDocumentoPerfil.ShortcutsEnabled = true;
            this.bftxtDocumentoPerfil.Size = new System.Drawing.Size(193, 39);
            this.bftxtDocumentoPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtDocumentoPerfil.TabIndex = 47;
            this.bftxtDocumentoPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bftxtDocumentoPerfil.TextMarginBottom = 0;
            this.bftxtDocumentoPerfil.TextMarginLeft = 3;
            this.bftxtDocumentoPerfil.TextMarginTop = 1;
            this.bftxtDocumentoPerfil.TextPlaceholder = "Documento de identidad";
            this.bftxtDocumentoPerfil.UseSystemPasswordChar = false;
            this.bftxtDocumentoPerfil.WordWrap = true;
            // 
            // bftxtSegundoApellidoperfil
            // 
            this.bftxtSegundoApellidoperfil.AcceptsReturn = false;
            this.bftxtSegundoApellidoperfil.AcceptsTab = false;
            this.bftxtSegundoApellidoperfil.AnimationSpeed = 200;
            this.bftxtSegundoApellidoperfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoApellidoperfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoApellidoperfil.AutoSizeHeight = true;
            this.bftxtSegundoApellidoperfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoApellidoperfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoApellidoperfil.BackgroundImage")));
            this.bftxtSegundoApellidoperfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoApellidoperfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoApellidoperfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoApellidoperfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoApellidoperfil.BorderRadius = 1;
            this.bftxtSegundoApellidoperfil.BorderThickness = 1;
            this.bftxtSegundoApellidoperfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoApellidoperfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoApellidoperfil.DefaultText = "";
            this.bftxtSegundoApellidoperfil.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoApellidoperfil.HideSelection = true;
            this.bftxtSegundoApellidoperfil.IconLeft = null;
            this.bftxtSegundoApellidoperfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.IconPadding = 10;
            this.bftxtSegundoApellidoperfil.IconRight = null;
            this.bftxtSegundoApellidoperfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellidoperfil.Lines = new string[0];
            this.bftxtSegundoApellidoperfil.Location = new System.Drawing.Point(316, 90);
            this.bftxtSegundoApellidoperfil.MaxLength = 32767;
            this.bftxtSegundoApellidoperfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoApellidoperfil.Modified = false;
            this.bftxtSegundoApellidoperfil.Multiline = false;
            this.bftxtSegundoApellidoperfil.Name = "bftxtSegundoApellidoperfil";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoApellidoperfil.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellidoperfil.OnIdleState = stateProperties60;
            this.bftxtSegundoApellidoperfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoApellidoperfil.PasswordChar = '\0';
            this.bftxtSegundoApellidoperfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoApellidoperfil.PlaceholderText = "Segundo apellido";
            this.bftxtSegundoApellidoperfil.ReadOnly = false;
            this.bftxtSegundoApellidoperfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoApellidoperfil.SelectedText = "";
            this.bftxtSegundoApellidoperfil.SelectionLength = 0;
            this.bftxtSegundoApellidoperfil.SelectionStart = 0;
            this.bftxtSegundoApellidoperfil.ShortcutsEnabled = true;
            this.bftxtSegundoApellidoperfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoApellidoperfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoApellidoperfil.TabIndex = 46;
            this.bftxtSegundoApellidoperfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoApellidoperfil.TextMarginBottom = 0;
            this.bftxtSegundoApellidoperfil.TextMarginLeft = 3;
            this.bftxtSegundoApellidoperfil.TextMarginTop = 1;
            this.bftxtSegundoApellidoperfil.TextPlaceholder = "Segundo apellido";
            this.bftxtSegundoApellidoperfil.UseSystemPasswordChar = false;
            this.bftxtSegundoApellidoperfil.WordWrap = true;
            // 
            // bftxtPrimerApellidoPerfil
            // 
            this.bftxtPrimerApellidoPerfil.AcceptsReturn = false;
            this.bftxtPrimerApellidoPerfil.AcceptsTab = false;
            this.bftxtPrimerApellidoPerfil.AnimationSpeed = 200;
            this.bftxtPrimerApellidoPerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerApellidoPerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerApellidoPerfil.AutoSizeHeight = true;
            this.bftxtPrimerApellidoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerApellidoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerApellidoPerfil.BackgroundImage")));
            this.bftxtPrimerApellidoPerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerApellidoPerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerApellidoPerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerApellidoPerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerApellidoPerfil.BorderRadius = 1;
            this.bftxtPrimerApellidoPerfil.BorderThickness = 1;
            this.bftxtPrimerApellidoPerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerApellidoPerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerApellidoPerfil.DefaultText = "";
            this.bftxtPrimerApellidoPerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerApellidoPerfil.HideSelection = true;
            this.bftxtPrimerApellidoPerfil.IconLeft = null;
            this.bftxtPrimerApellidoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.IconPadding = 10;
            this.bftxtPrimerApellidoPerfil.IconRight = null;
            this.bftxtPrimerApellidoPerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellidoPerfil.Lines = new string[0];
            this.bftxtPrimerApellidoPerfil.Location = new System.Drawing.Point(49, 90);
            this.bftxtPrimerApellidoPerfil.MaxLength = 32767;
            this.bftxtPrimerApellidoPerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerApellidoPerfil.Modified = false;
            this.bftxtPrimerApellidoPerfil.Multiline = false;
            this.bftxtPrimerApellidoPerfil.Name = "bftxtPrimerApellidoPerfil";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerApellidoPerfil.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellidoPerfil.OnIdleState = stateProperties64;
            this.bftxtPrimerApellidoPerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerApellidoPerfil.PasswordChar = '\0';
            this.bftxtPrimerApellidoPerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerApellidoPerfil.PlaceholderText = "Primer Apellido";
            this.bftxtPrimerApellidoPerfil.ReadOnly = false;
            this.bftxtPrimerApellidoPerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerApellidoPerfil.SelectedText = "";
            this.bftxtPrimerApellidoPerfil.SelectionLength = 0;
            this.bftxtPrimerApellidoPerfil.SelectionStart = 0;
            this.bftxtPrimerApellidoPerfil.ShortcutsEnabled = true;
            this.bftxtPrimerApellidoPerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerApellidoPerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerApellidoPerfil.TabIndex = 45;
            this.bftxtPrimerApellidoPerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerApellidoPerfil.TextMarginBottom = 0;
            this.bftxtPrimerApellidoPerfil.TextMarginLeft = 3;
            this.bftxtPrimerApellidoPerfil.TextMarginTop = 1;
            this.bftxtPrimerApellidoPerfil.TextPlaceholder = "Primer Apellido";
            this.bftxtPrimerApellidoPerfil.UseSystemPasswordChar = false;
            this.bftxtPrimerApellidoPerfil.WordWrap = true;
            // 
            // bftxtSegundoNombrePerfil
            // 
            this.bftxtSegundoNombrePerfil.AcceptsReturn = false;
            this.bftxtSegundoNombrePerfil.AcceptsTab = false;
            this.bftxtSegundoNombrePerfil.AnimationSpeed = 200;
            this.bftxtSegundoNombrePerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoNombrePerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoNombrePerfil.AutoSizeHeight = true;
            this.bftxtSegundoNombrePerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoNombrePerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoNombrePerfil.BackgroundImage")));
            this.bftxtSegundoNombrePerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoNombrePerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoNombrePerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoNombrePerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoNombrePerfil.BorderRadius = 1;
            this.bftxtSegundoNombrePerfil.BorderThickness = 1;
            this.bftxtSegundoNombrePerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoNombrePerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoNombrePerfil.DefaultText = "";
            this.bftxtSegundoNombrePerfil.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoNombrePerfil.HideSelection = true;
            this.bftxtSegundoNombrePerfil.IconLeft = null;
            this.bftxtSegundoNombrePerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.IconPadding = 10;
            this.bftxtSegundoNombrePerfil.IconRight = null;
            this.bftxtSegundoNombrePerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombrePerfil.Lines = new string[0];
            this.bftxtSegundoNombrePerfil.Location = new System.Drawing.Point(316, 15);
            this.bftxtSegundoNombrePerfil.MaxLength = 32767;
            this.bftxtSegundoNombrePerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoNombrePerfil.Modified = false;
            this.bftxtSegundoNombrePerfil.Multiline = false;
            this.bftxtSegundoNombrePerfil.Name = "bftxtSegundoNombrePerfil";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoNombrePerfil.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombrePerfil.OnIdleState = stateProperties68;
            this.bftxtSegundoNombrePerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoNombrePerfil.PasswordChar = '\0';
            this.bftxtSegundoNombrePerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoNombrePerfil.PlaceholderText = "Segundo nombre";
            this.bftxtSegundoNombrePerfil.ReadOnly = false;
            this.bftxtSegundoNombrePerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoNombrePerfil.SelectedText = "";
            this.bftxtSegundoNombrePerfil.SelectionLength = 0;
            this.bftxtSegundoNombrePerfil.SelectionStart = 0;
            this.bftxtSegundoNombrePerfil.ShortcutsEnabled = true;
            this.bftxtSegundoNombrePerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoNombrePerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoNombrePerfil.TabIndex = 44;
            this.bftxtSegundoNombrePerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoNombrePerfil.TextMarginBottom = 0;
            this.bftxtSegundoNombrePerfil.TextMarginLeft = 3;
            this.bftxtSegundoNombrePerfil.TextMarginTop = 1;
            this.bftxtSegundoNombrePerfil.TextPlaceholder = "Segundo nombre";
            this.bftxtSegundoNombrePerfil.UseSystemPasswordChar = false;
            this.bftxtSegundoNombrePerfil.WordWrap = true;
            // 
            // bftxtPrimerNombrePerfil
            // 
            this.bftxtPrimerNombrePerfil.AcceptsReturn = false;
            this.bftxtPrimerNombrePerfil.AcceptsTab = false;
            this.bftxtPrimerNombrePerfil.AnimationSpeed = 200;
            this.bftxtPrimerNombrePerfil.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerNombrePerfil.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerNombrePerfil.AutoSizeHeight = true;
            this.bftxtPrimerNombrePerfil.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerNombrePerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerNombrePerfil.BackgroundImage")));
            this.bftxtPrimerNombrePerfil.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerNombrePerfil.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerNombrePerfil.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerNombrePerfil.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerNombrePerfil.BorderRadius = 1;
            this.bftxtPrimerNombrePerfil.BorderThickness = 1;
            this.bftxtPrimerNombrePerfil.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerNombrePerfil.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerNombrePerfil.DefaultText = "";
            this.bftxtPrimerNombrePerfil.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerNombrePerfil.HideSelection = true;
            this.bftxtPrimerNombrePerfil.IconLeft = null;
            this.bftxtPrimerNombrePerfil.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.IconPadding = 10;
            this.bftxtPrimerNombrePerfil.IconRight = null;
            this.bftxtPrimerNombrePerfil.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombrePerfil.Lines = new string[0];
            this.bftxtPrimerNombrePerfil.Location = new System.Drawing.Point(49, 15);
            this.bftxtPrimerNombrePerfil.MaxLength = 32767;
            this.bftxtPrimerNombrePerfil.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerNombrePerfil.Modified = false;
            this.bftxtPrimerNombrePerfil.Multiline = false;
            this.bftxtPrimerNombrePerfil.Name = "bftxtPrimerNombrePerfil";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerNombrePerfil.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombrePerfil.OnIdleState = stateProperties72;
            this.bftxtPrimerNombrePerfil.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerNombrePerfil.PasswordChar = '\0';
            this.bftxtPrimerNombrePerfil.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerNombrePerfil.PlaceholderText = "Primer nombre";
            this.bftxtPrimerNombrePerfil.ReadOnly = false;
            this.bftxtPrimerNombrePerfil.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerNombrePerfil.SelectedText = "";
            this.bftxtPrimerNombrePerfil.SelectionLength = 0;
            this.bftxtPrimerNombrePerfil.SelectionStart = 0;
            this.bftxtPrimerNombrePerfil.ShortcutsEnabled = true;
            this.bftxtPrimerNombrePerfil.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerNombrePerfil.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerNombrePerfil.TabIndex = 43;
            this.bftxtPrimerNombrePerfil.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerNombrePerfil.TextMarginBottom = 0;
            this.bftxtPrimerNombrePerfil.TextMarginLeft = 3;
            this.bftxtPrimerNombrePerfil.TextMarginTop = 1;
            this.bftxtPrimerNombrePerfil.TextPlaceholder = "Primer nombre";
            this.bftxtPrimerNombrePerfil.UseSystemPasswordChar = false;
            this.bftxtPrimerNombrePerfil.WordWrap = true;
            // 
            // bfbtnActualizar
            // 
            this.bfbtnActualizar.AllowAnimations = true;
            this.bfbtnActualizar.AllowMouseEffects = true;
            this.bfbtnActualizar.AllowToggling = false;
            this.bfbtnActualizar.AnimationSpeed = 200;
            this.bfbtnActualizar.AutoGenerateColors = false;
            this.bfbtnActualizar.AutoRoundBorders = false;
            this.bfbtnActualizar.AutoSizeLeftIcon = true;
            this.bfbtnActualizar.AutoSizeRightIcon = true;
            this.bfbtnActualizar.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnActualizar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bfbtnActualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnActualizar.BackgroundImage")));
            this.bfbtnActualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnActualizar.ButtonText = "Actualizar";
            this.bfbtnActualizar.ButtonTextMarginLeft = 0;
            this.bfbtnActualizar.ColorContrastOnClick = 45;
            this.bfbtnActualizar.ColorContrastOnHover = 45;
            this.bfbtnActualizar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bfbtnActualizar.CustomizableEdges = borderEdges2;
            this.bfbtnActualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnActualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnActualizar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnActualizar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnActualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnActualizar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnActualizar.ForeColor = System.Drawing.Color.White;
            this.bfbtnActualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnActualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnActualizar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnActualizar.IconMarginLeft = 11;
            this.bfbtnActualizar.IconPadding = 10;
            this.bfbtnActualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnActualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnActualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnActualizar.IconSize = 25;
            this.bfbtnActualizar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnActualizar.IdleBorderRadius = 1;
            this.bfbtnActualizar.IdleBorderThickness = 1;
            this.bfbtnActualizar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnActualizar.IdleIconLeftImage = null;
            this.bfbtnActualizar.IdleIconRightImage = null;
            this.bfbtnActualizar.IndicateFocus = false;
            this.bfbtnActualizar.Location = new System.Drawing.Point(546, 707);
            this.bfbtnActualizar.Name = "bfbtnActualizar";
            this.bfbtnActualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnActualizar.OnDisabledState.BorderRadius = 1;
            this.bfbtnActualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnActualizar.OnDisabledState.BorderThickness = 1;
            this.bfbtnActualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnActualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnActualizar.OnDisabledState.IconLeftImage = null;
            this.bfbtnActualizar.OnDisabledState.IconRightImage = null;
            this.bfbtnActualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnActualizar.onHoverState.BorderRadius = 1;
            this.bfbtnActualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnActualizar.onHoverState.BorderThickness = 1;
            this.bfbtnActualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnActualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnActualizar.onHoverState.IconLeftImage = null;
            this.bfbtnActualizar.onHoverState.IconRightImage = null;
            this.bfbtnActualizar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnActualizar.OnIdleState.BorderRadius = 1;
            this.bfbtnActualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnActualizar.OnIdleState.BorderThickness = 1;
            this.bfbtnActualizar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnActualizar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnActualizar.OnIdleState.IconLeftImage = null;
            this.bfbtnActualizar.OnIdleState.IconRightImage = null;
            this.bfbtnActualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnActualizar.OnPressedState.BorderRadius = 1;
            this.bfbtnActualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnActualizar.OnPressedState.BorderThickness = 1;
            this.bfbtnActualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnActualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnActualizar.OnPressedState.IconLeftImage = null;
            this.bfbtnActualizar.OnPressedState.IconRightImage = null;
            this.bfbtnActualizar.Size = new System.Drawing.Size(81, 29);
            this.bfbtnActualizar.TabIndex = 53;
            this.bfbtnActualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnActualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnActualizar.TextMarginLeft = 0;
            this.bfbtnActualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnActualizar.UseDefaultRadiusAndThickness = true;
            this.bfbtnActualizar.Click += new System.EventHandler(this.bfbtnActualizar_Click);
            // 
            // panelPerfil
            // 
            this.panelPerfil.Controls.Add(this.bunifuLabel3);
            this.panelPerfil.Controls.Add(this.bunifuLabel2);
            this.panelPerfil.Controls.Add(this.bunifuLabel1);
            this.panelPerfil.Controls.Add(this.cmbGeneroPerfil);
            this.panelPerfil.Controls.Add(this.bflblGenero);
            this.panelPerfil.Controls.Add(this.bflblFechaNacimiento);
            this.panelPerfil.Controls.Add(this.bfdtpFechaNacimientoPerfil);
            this.panelPerfil.Controls.Add(this.bftxtDocumentoPerfil);
            this.panelPerfil.Controls.Add(this.bftxtSegundoApellidoperfil);
            this.panelPerfil.Controls.Add(this.bftxtPrimerApellidoPerfil);
            this.panelPerfil.Controls.Add(this.bftxtSegundoNombrePerfil);
            this.panelPerfil.Controls.Add(this.bftxtPrimerNombrePerfil);
            this.panelPerfil.Controls.Add(this.bftxtConfirmPasswordPerfil);
            this.panelPerfil.Controls.Add(this.bftxtPasswordPerfil);
            this.panelPerfil.Controls.Add(this.bftxtConfirmarEmailPerfil);
            this.panelPerfil.Controls.Add(this.bftxtxEmailPerfil);
            this.panelPerfil.Location = new System.Drawing.Point(22, 203);
            this.panelPerfil.Name = "panelPerfil";
            this.panelPerfil.Size = new System.Drawing.Size(621, 550);
            this.panelPerfil.TabIndex = 54;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkCyan;
            this.bunifuLabel1.Location = new System.Drawing.Point(51, 389);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(262, 15);
            this.bunifuLabel1.TabIndex = 52;
            this.bunifuLabel1.Text = "Para actualizar datos debes ingresar tu contraseña";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(51, 419);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(60, 15);
            this.bunifuLabel2.TabIndex = 53;
            this.bunifuLabel2.Text = "Contraseña";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(316, 419);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(115, 15);
            this.bunifuLabel3.TabIndex = 54;
            this.bunifuLabel3.Text = "Confirmar contraseña";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmPerfil
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(655, 765);
            this.Controls.Add(this.bfbtnActualizar);
            this.Controls.Add(this.lblDatosPersonales);
            this.Controls.Add(this.lblTipoUsuarioPerfil);
            this.Controls.Add(this.lblNombreUsuarioPerfil);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.panelPerfil);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmPerfil";
            this.Text = "frmPerfil";
            this.Load += new System.EventHandler(this.frmPerfil_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.panelPerfil.ResumeLayout(false);
            this.panelPerfil.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmPasswordPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPasswordPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmarEmailPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxEmailPerfil;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Label lblNombreUsuarioPerfil;
        private System.Windows.Forms.Label lblTipoUsuarioPerfil;
        private System.Windows.Forms.Label lblDatosPersonales;
        private System.Windows.Forms.ComboBox cmbGeneroPerfil;
        private Bunifu.UI.WinForms.BunifuLabel bflblGenero;
        private Bunifu.UI.WinForms.BunifuLabel bflblFechaNacimiento;
        private Bunifu.UI.WinForms.BunifuDatePicker bfdtpFechaNacimientoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtDocumentoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoApellidoperfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerApellidoPerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoNombrePerfil;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerNombrePerfil;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnActualizar;
        private System.Windows.Forms.Panel panelPerfil;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}