
namespace final_motoDix.Vistas
{
    partial class frmRegisterClient
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmRegisterClient));
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bflblCreateAccount1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblCreateAccount2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ptbCrearCuentaMinimizar = new System.Windows.Forms.PictureBox();
            this.ptbCrearCuentaCerrar = new System.Windows.Forms.PictureBox();
            this.bfpgPersonInfo = new Bunifu.UI.WinForms.BunifuPages();
            this.bftpInfoPersonal = new System.Windows.Forms.TabPage();
            this.cmbCiudad = new System.Windows.Forms.ComboBox();
            this.lblCiudad = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblDepartamento = new Bunifu.UI.WinForms.BunifuLabel();
            this.cmbDepartamento = new System.Windows.Forms.ComboBox();
            this.lblDatosPersonales = new System.Windows.Forms.Label();
            this.bfbtnRegisterNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.cmbGenero = new System.Windows.Forms.ComboBox();
            this.bflblGenero = new Bunifu.UI.WinForms.BunifuLabel();
            this.bflblFechaNacimiento = new Bunifu.UI.WinForms.BunifuLabel();
            this.bfdpkFechaNacimiento = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bftxtDocumento = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtSegundoNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPrimerNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftgLogin = new System.Windows.Forms.TabPage();
            this.bfbtnInfoFinish = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bftxtConfirmPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtConfirmarEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bftxtxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            ((System.ComponentModel.ISupportInitialize)(this.ptbCrearCuentaMinimizar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbCrearCuentaCerrar)).BeginInit();
            this.bfpgPersonInfo.SuspendLayout();
            this.bftpInfoPersonal.SuspendLayout();
            this.bftgLogin.SuspendLayout();
            this.SuspendLayout();
            // 
            // bflblCreateAccount1
            // 
            this.bflblCreateAccount1.AllowParentOverrides = false;
            this.bflblCreateAccount1.AutoEllipsis = false;
            this.bflblCreateAccount1.AutoSize = false;
            this.bflblCreateAccount1.AutoSizeHeightOnly = true;
            this.bflblCreateAccount1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bflblCreateAccount1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblCreateAccount1.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.bflblCreateAccount1.ForeColor = System.Drawing.Color.Black;
            this.bflblCreateAccount1.Location = new System.Drawing.Point(282, 51);
            this.bflblCreateAccount1.Name = "bflblCreateAccount1";
            this.bflblCreateAccount1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblCreateAccount1.Size = new System.Drawing.Size(135, 29);
            this.bflblCreateAccount1.TabIndex = 0;
            this.bflblCreateAccount1.Text = "Crear una";
            this.bflblCreateAccount1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bflblCreateAccount1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bflblCreateAccount1.Click += new System.EventHandler(this.bflblCreateAccount_Click);
            // 
            // bflblCreateAccount2
            // 
            this.bflblCreateAccount2.AllowParentOverrides = false;
            this.bflblCreateAccount2.AutoEllipsis = false;
            this.bflblCreateAccount2.AutoSize = false;
            this.bflblCreateAccount2.AutoSizeHeightOnly = true;
            this.bflblCreateAccount2.CursorType = null;
            this.bflblCreateAccount2.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.bflblCreateAccount2.ForeColor = System.Drawing.Color.White;
            this.bflblCreateAccount2.Location = new System.Drawing.Point(414, 51);
            this.bflblCreateAccount2.Name = "bflblCreateAccount2";
            this.bflblCreateAccount2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblCreateAccount2.Size = new System.Drawing.Size(175, 29);
            this.bflblCreateAccount2.TabIndex = 12;
            this.bflblCreateAccount2.Text = "nueva cuenta";
            this.bflblCreateAccount2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bflblCreateAccount2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ptbCrearCuentaMinimizar
            // 
            this.ptbCrearCuentaMinimizar.Image = ((System.Drawing.Image)(resources.GetObject("ptbCrearCuentaMinimizar.Image")));
            this.ptbCrearCuentaMinimizar.Location = new System.Drawing.Point(800, 12);
            this.ptbCrearCuentaMinimizar.Name = "ptbCrearCuentaMinimizar";
            this.ptbCrearCuentaMinimizar.Size = new System.Drawing.Size(17, 18);
            this.ptbCrearCuentaMinimizar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ptbCrearCuentaMinimizar.TabIndex = 15;
            this.ptbCrearCuentaMinimizar.TabStop = false;
            this.ptbCrearCuentaMinimizar.Click += new System.EventHandler(this.ptbCrearCuentaMinimizar_Click);
            // 
            // ptbCrearCuentaCerrar
            // 
            this.ptbCrearCuentaCerrar.Image = ((System.Drawing.Image)(resources.GetObject("ptbCrearCuentaCerrar.Image")));
            this.ptbCrearCuentaCerrar.Location = new System.Drawing.Point(823, 12);
            this.ptbCrearCuentaCerrar.Name = "ptbCrearCuentaCerrar";
            this.ptbCrearCuentaCerrar.Size = new System.Drawing.Size(18, 18);
            this.ptbCrearCuentaCerrar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ptbCrearCuentaCerrar.TabIndex = 16;
            this.ptbCrearCuentaCerrar.TabStop = false;
            this.ptbCrearCuentaCerrar.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // bfpgPersonInfo
            // 
            this.bfpgPersonInfo.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bfpgPersonInfo.AllowTransitions = false;
            this.bfpgPersonInfo.Controls.Add(this.bftpInfoPersonal);
            this.bfpgPersonInfo.Controls.Add(this.bftgLogin);
            this.bfpgPersonInfo.Location = new System.Drawing.Point(67, 86);
            this.bfpgPersonInfo.Multiline = true;
            this.bfpgPersonInfo.Name = "bfpgPersonInfo";
            this.bfpgPersonInfo.Page = this.bftgLogin;
            this.bfpgPersonInfo.PageIndex = 1;
            this.bfpgPersonInfo.PageName = "bftgLogin";
            this.bfpgPersonInfo.PageTitle = "Login";
            this.bfpgPersonInfo.SelectedIndex = 0;
            this.bfpgPersonInfo.Size = new System.Drawing.Size(725, 412);
            this.bfpgPersonInfo.TabIndex = 17;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bfpgPersonInfo.Transition = animation1;
            this.bfpgPersonInfo.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // bftpInfoPersonal
            // 
            this.bftpInfoPersonal.Controls.Add(this.cmbCiudad);
            this.bftpInfoPersonal.Controls.Add(this.lblCiudad);
            this.bftpInfoPersonal.Controls.Add(this.bflblDepartamento);
            this.bftpInfoPersonal.Controls.Add(this.cmbDepartamento);
            this.bftpInfoPersonal.Controls.Add(this.lblDatosPersonales);
            this.bftpInfoPersonal.Controls.Add(this.bfbtnRegisterNext);
            this.bftpInfoPersonal.Controls.Add(this.cmbGenero);
            this.bftpInfoPersonal.Controls.Add(this.bflblGenero);
            this.bftpInfoPersonal.Controls.Add(this.bflblFechaNacimiento);
            this.bftpInfoPersonal.Controls.Add(this.bfdpkFechaNacimiento);
            this.bftpInfoPersonal.Controls.Add(this.bftxtDocumento);
            this.bftpInfoPersonal.Controls.Add(this.bftxtSegundoApellido);
            this.bftpInfoPersonal.Controls.Add(this.bftxtPrimerApellido);
            this.bftpInfoPersonal.Controls.Add(this.bftxtSegundoNombre);
            this.bftpInfoPersonal.Controls.Add(this.bftxtPrimerNombre);
            this.bftpInfoPersonal.Location = new System.Drawing.Point(4, 4);
            this.bftpInfoPersonal.Name = "bftpInfoPersonal";
            this.bftpInfoPersonal.Padding = new System.Windows.Forms.Padding(3);
            this.bftpInfoPersonal.Size = new System.Drawing.Size(717, 386);
            this.bftpInfoPersonal.TabIndex = 1;
            this.bftpInfoPersonal.Text = "Register";
            this.bftpInfoPersonal.UseVisualStyleBackColor = true;
            this.bftpInfoPersonal.Click += new System.EventHandler(this.bftpInfoPersonal_Click);
            // 
            // cmbCiudad
            // 
            this.cmbCiudad.FormattingEnabled = true;
            this.cmbCiudad.Location = new System.Drawing.Point(126, 326);
            this.cmbCiudad.Name = "cmbCiudad";
            this.cmbCiudad.Size = new System.Drawing.Size(161, 21);
            this.cmbCiudad.TabIndex = 46;
            this.cmbCiudad.SelectedIndexChanged += new System.EventHandler(this.cmbCiudad_SelectedIndexChanged);
            // 
            // lblCiudad
            // 
            this.lblCiudad.AllowParentOverrides = false;
            this.lblCiudad.AutoEllipsis = false;
            this.lblCiudad.CursorType = null;
            this.lblCiudad.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblCiudad.Location = new System.Drawing.Point(126, 305);
            this.lblCiudad.Name = "lblCiudad";
            this.lblCiudad.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCiudad.Size = new System.Drawing.Size(105, 15);
            this.lblCiudad.TabIndex = 45;
            this.lblCiudad.Text = "Ciudad o municipio";
            this.lblCiudad.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCiudad.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bflblDepartamento
            // 
            this.bflblDepartamento.AllowParentOverrides = false;
            this.bflblDepartamento.AutoEllipsis = false;
            this.bflblDepartamento.CursorType = null;
            this.bflblDepartamento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblDepartamento.Location = new System.Drawing.Point(393, 246);
            this.bflblDepartamento.Name = "bflblDepartamento";
            this.bflblDepartamento.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblDepartamento.Size = new System.Drawing.Size(76, 15);
            this.bflblDepartamento.TabIndex = 44;
            this.bflblDepartamento.Text = "Departamento";
            this.bflblDepartamento.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblDepartamento.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cmbDepartamento
            // 
            this.cmbDepartamento.FormattingEnabled = true;
            this.cmbDepartamento.Location = new System.Drawing.Point(393, 267);
            this.cmbDepartamento.Name = "cmbDepartamento";
            this.cmbDepartamento.Size = new System.Drawing.Size(161, 21);
            this.cmbDepartamento.TabIndex = 43;
            this.cmbDepartamento.SelectedIndexChanged += new System.EventHandler(this.cmbDepartamento_SelectedIndexChanged);
            // 
            // lblDatosPersonales
            // 
            this.lblDatosPersonales.AutoSize = true;
            this.lblDatosPersonales.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDatosPersonales.Location = new System.Drawing.Point(289, 12);
            this.lblDatosPersonales.Name = "lblDatosPersonales";
            this.lblDatosPersonales.Size = new System.Drawing.Size(155, 24);
            this.lblDatosPersonales.TabIndex = 42;
            this.lblDatosPersonales.Text = "Datos personales";
            // 
            // bfbtnRegisterNext
            // 
            this.bfbtnRegisterNext.AllowAnimations = true;
            this.bfbtnRegisterNext.AllowMouseEffects = true;
            this.bfbtnRegisterNext.AllowToggling = false;
            this.bfbtnRegisterNext.AnimationSpeed = 200;
            this.bfbtnRegisterNext.AutoGenerateColors = false;
            this.bfbtnRegisterNext.AutoRoundBorders = false;
            this.bfbtnRegisterNext.AutoSizeLeftIcon = true;
            this.bfbtnRegisterNext.AutoSizeRightIcon = true;
            this.bfbtnRegisterNext.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnRegisterNext.BackColor1 = System.Drawing.Color.Red;
            this.bfbtnRegisterNext.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnRegisterNext.BackgroundImage")));
            this.bfbtnRegisterNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnRegisterNext.ButtonText = "Next";
            this.bfbtnRegisterNext.ButtonTextMarginLeft = 0;
            this.bfbtnRegisterNext.ColorContrastOnClick = 45;
            this.bfbtnRegisterNext.ColorContrastOnHover = 45;
            this.bfbtnRegisterNext.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = false;
            borderEdges1.BottomRight = false;
            borderEdges1.TopLeft = false;
            borderEdges1.TopRight = false;
            this.bfbtnRegisterNext.CustomizableEdges = borderEdges1;
            this.bfbtnRegisterNext.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnRegisterNext.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnRegisterNext.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnRegisterNext.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnRegisterNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bfbtnRegisterNext.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfbtnRegisterNext.ForeColor = System.Drawing.SystemColors.Window;
            this.bfbtnRegisterNext.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnRegisterNext.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnRegisterNext.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnRegisterNext.IconMarginLeft = 11;
            this.bfbtnRegisterNext.IconPadding = 10;
            this.bfbtnRegisterNext.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnRegisterNext.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnRegisterNext.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnRegisterNext.IconSize = 25;
            this.bfbtnRegisterNext.IdleBorderColor = System.Drawing.Color.Red;
            this.bfbtnRegisterNext.IdleBorderRadius = 1;
            this.bfbtnRegisterNext.IdleBorderThickness = 1;
            this.bfbtnRegisterNext.IdleFillColor = System.Drawing.Color.Red;
            this.bfbtnRegisterNext.IdleIconLeftImage = null;
            this.bfbtnRegisterNext.IdleIconRightImage = null;
            this.bfbtnRegisterNext.IndicateFocus = false;
            this.bfbtnRegisterNext.Location = new System.Drawing.Point(612, 345);
            this.bfbtnRegisterNext.Margin = new System.Windows.Forms.Padding(2);
            this.bfbtnRegisterNext.Name = "bfbtnRegisterNext";
            this.bfbtnRegisterNext.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnRegisterNext.OnDisabledState.BorderRadius = 1;
            this.bfbtnRegisterNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnRegisterNext.OnDisabledState.BorderThickness = 1;
            this.bfbtnRegisterNext.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnRegisterNext.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnRegisterNext.OnDisabledState.IconLeftImage = null;
            this.bfbtnRegisterNext.OnDisabledState.IconRightImage = null;
            this.bfbtnRegisterNext.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnRegisterNext.onHoverState.BorderRadius = 1;
            this.bfbtnRegisterNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnRegisterNext.onHoverState.BorderThickness = 1;
            this.bfbtnRegisterNext.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bfbtnRegisterNext.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegisterNext.onHoverState.IconLeftImage = null;
            this.bfbtnRegisterNext.onHoverState.IconRightImage = null;
            this.bfbtnRegisterNext.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.bfbtnRegisterNext.OnIdleState.BorderRadius = 1;
            this.bfbtnRegisterNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnRegisterNext.OnIdleState.BorderThickness = 1;
            this.bfbtnRegisterNext.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.bfbtnRegisterNext.OnIdleState.ForeColor = System.Drawing.SystemColors.Window;
            this.bfbtnRegisterNext.OnIdleState.IconLeftImage = null;
            this.bfbtnRegisterNext.OnIdleState.IconRightImage = null;
            this.bfbtnRegisterNext.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnRegisterNext.OnPressedState.BorderRadius = 1;
            this.bfbtnRegisterNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bfbtnRegisterNext.OnPressedState.BorderThickness = 1;
            this.bfbtnRegisterNext.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnRegisterNext.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnRegisterNext.OnPressedState.IconLeftImage = null;
            this.bfbtnRegisterNext.OnPressedState.IconRightImage = null;
            this.bfbtnRegisterNext.Size = new System.Drawing.Size(75, 25);
            this.bfbtnRegisterNext.TabIndex = 41;
            this.bfbtnRegisterNext.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnRegisterNext.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnRegisterNext.TextMarginLeft = 0;
            this.bfbtnRegisterNext.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnRegisterNext.UseDefaultRadiusAndThickness = true;
            this.bfbtnRegisterNext.Click += new System.EventHandler(this.bfbtnRegisterNext_Click);
            // 
            // cmbGenero
            // 
            this.cmbGenero.FormattingEnabled = true;
            this.cmbGenero.Location = new System.Drawing.Point(126, 267);
            this.cmbGenero.Name = "cmbGenero";
            this.cmbGenero.Size = new System.Drawing.Size(161, 21);
            this.cmbGenero.TabIndex = 40;
            // 
            // bflblGenero
            // 
            this.bflblGenero.AllowParentOverrides = false;
            this.bflblGenero.AutoEllipsis = false;
            this.bflblGenero.CursorType = null;
            this.bflblGenero.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblGenero.Location = new System.Drawing.Point(126, 246);
            this.bflblGenero.Name = "bflblGenero";
            this.bflblGenero.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblGenero.Size = new System.Drawing.Size(38, 15);
            this.bflblGenero.TabIndex = 39;
            this.bflblGenero.Text = "Genero";
            this.bflblGenero.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblGenero.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bflblFechaNacimiento
            // 
            this.bflblFechaNacimiento.AllowParentOverrides = false;
            this.bflblFechaNacimiento.AutoEllipsis = false;
            this.bflblFechaNacimiento.Cursor = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.CursorType = System.Windows.Forms.Cursors.Default;
            this.bflblFechaNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bflblFechaNacimiento.Location = new System.Drawing.Point(126, 173);
            this.bflblFechaNacimiento.Name = "bflblFechaNacimiento";
            this.bflblFechaNacimiento.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bflblFechaNacimiento.Size = new System.Drawing.Size(110, 15);
            this.bflblFechaNacimiento.TabIndex = 38;
            this.bflblFechaNacimiento.Text = "Fecha de nacimiento";
            this.bflblFechaNacimiento.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bflblFechaNacimiento.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bfdpkFechaNacimiento
            // 
            this.bfdpkFechaNacimiento.BackColor = System.Drawing.Color.Transparent;
            this.bfdpkFechaNacimiento.BorderColor = System.Drawing.Color.Silver;
            this.bfdpkFechaNacimiento.BorderRadius = 1;
            this.bfdpkFechaNacimiento.Color = System.Drawing.Color.Silver;
            this.bfdpkFechaNacimiento.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bfdpkFechaNacimiento.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bfdpkFechaNacimiento.DisabledColor = System.Drawing.Color.Gray;
            this.bfdpkFechaNacimiento.DisplayWeekNumbers = false;
            this.bfdpkFechaNacimiento.DPHeight = 0;
            this.bfdpkFechaNacimiento.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bfdpkFechaNacimiento.FillDatePicker = false;
            this.bfdpkFechaNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bfdpkFechaNacimiento.ForeColor = System.Drawing.Color.Black;
            this.bfdpkFechaNacimiento.Icon = ((System.Drawing.Image)(resources.GetObject("bfdpkFechaNacimiento.Icon")));
            this.bfdpkFechaNacimiento.IconColor = System.Drawing.Color.Gray;
            this.bfdpkFechaNacimiento.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bfdpkFechaNacimiento.LeftTextMargin = 5;
            this.bfdpkFechaNacimiento.Location = new System.Drawing.Point(126, 194);
            this.bfdpkFechaNacimiento.MinimumSize = new System.Drawing.Size(4, 32);
            this.bfdpkFechaNacimiento.Name = "bfdpkFechaNacimiento";
            this.bfdpkFechaNacimiento.Size = new System.Drawing.Size(202, 32);
            this.bfdpkFechaNacimiento.TabIndex = 37;
            this.bfdpkFechaNacimiento.Value = new System.DateTime(2021, 10, 15, 13, 59, 0, 0);
            // 
            // bftxtDocumento
            // 
            this.bftxtDocumento.AcceptsReturn = false;
            this.bftxtDocumento.AcceptsTab = false;
            this.bftxtDocumento.AnimationSpeed = 200;
            this.bftxtDocumento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtDocumento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtDocumento.AutoSizeHeight = true;
            this.bftxtDocumento.BackColor = System.Drawing.Color.Transparent;
            this.bftxtDocumento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtDocumento.BackgroundImage")));
            this.bftxtDocumento.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtDocumento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtDocumento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtDocumento.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtDocumento.BorderRadius = 1;
            this.bftxtDocumento.BorderThickness = 1;
            this.bftxtDocumento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtDocumento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumento.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bftxtDocumento.DefaultText = "";
            this.bftxtDocumento.FillColor = System.Drawing.Color.White;
            this.bftxtDocumento.HideSelection = true;
            this.bftxtDocumento.IconLeft = null;
            this.bftxtDocumento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumento.IconPadding = 10;
            this.bftxtDocumento.IconRight = null;
            this.bftxtDocumento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtDocumento.Lines = new string[0];
            this.bftxtDocumento.Location = new System.Drawing.Point(393, 187);
            this.bftxtDocumento.MaxLength = 32767;
            this.bftxtDocumento.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtDocumento.Modified = false;
            this.bftxtDocumento.Multiline = false;
            this.bftxtDocumento.Name = "bftxtDocumento";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumento.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtDocumento.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumento.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtDocumento.OnIdleState = stateProperties4;
            this.bftxtDocumento.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtDocumento.PasswordChar = '\0';
            this.bftxtDocumento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtDocumento.PlaceholderText = "Documento de identidad";
            this.bftxtDocumento.ReadOnly = false;
            this.bftxtDocumento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtDocumento.SelectedText = "";
            this.bftxtDocumento.SelectionLength = 0;
            this.bftxtDocumento.SelectionStart = 0;
            this.bftxtDocumento.ShortcutsEnabled = true;
            this.bftxtDocumento.Size = new System.Drawing.Size(193, 39);
            this.bftxtDocumento.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtDocumento.TabIndex = 36;
            this.bftxtDocumento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bftxtDocumento.TextMarginBottom = 0;
            this.bftxtDocumento.TextMarginLeft = 3;
            this.bftxtDocumento.TextMarginTop = 1;
            this.bftxtDocumento.TextPlaceholder = "Documento de identidad";
            this.bftxtDocumento.UseSystemPasswordChar = false;
            this.bftxtDocumento.WordWrap = true;
            // 
            // bftxtSegundoApellido
            // 
            this.bftxtSegundoApellido.AcceptsReturn = false;
            this.bftxtSegundoApellido.AcceptsTab = false;
            this.bftxtSegundoApellido.AnimationSpeed = 200;
            this.bftxtSegundoApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoApellido.AutoSizeHeight = true;
            this.bftxtSegundoApellido.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoApellido.BackgroundImage")));
            this.bftxtSegundoApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoApellido.BorderRadius = 1;
            this.bftxtSegundoApellido.BorderThickness = 1;
            this.bftxtSegundoApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellido.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoApellido.DefaultText = "";
            this.bftxtSegundoApellido.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoApellido.HideSelection = true;
            this.bftxtSegundoApellido.IconLeft = null;
            this.bftxtSegundoApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellido.IconPadding = 10;
            this.bftxtSegundoApellido.IconRight = null;
            this.bftxtSegundoApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoApellido.Lines = new string[0];
            this.bftxtSegundoApellido.Location = new System.Drawing.Point(393, 113);
            this.bftxtSegundoApellido.MaxLength = 32767;
            this.bftxtSegundoApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoApellido.Modified = false;
            this.bftxtSegundoApellido.Multiline = false;
            this.bftxtSegundoApellido.Name = "bftxtSegundoApellido";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellido.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoApellido.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellido.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoApellido.OnIdleState = stateProperties8;
            this.bftxtSegundoApellido.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoApellido.PasswordChar = '\0';
            this.bftxtSegundoApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoApellido.PlaceholderText = "Segundo apellido";
            this.bftxtSegundoApellido.ReadOnly = false;
            this.bftxtSegundoApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoApellido.SelectedText = "";
            this.bftxtSegundoApellido.SelectionLength = 0;
            this.bftxtSegundoApellido.SelectionStart = 0;
            this.bftxtSegundoApellido.ShortcutsEnabled = true;
            this.bftxtSegundoApellido.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoApellido.TabIndex = 35;
            this.bftxtSegundoApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoApellido.TextMarginBottom = 0;
            this.bftxtSegundoApellido.TextMarginLeft = 3;
            this.bftxtSegundoApellido.TextMarginTop = 1;
            this.bftxtSegundoApellido.TextPlaceholder = "Segundo apellido";
            this.bftxtSegundoApellido.UseSystemPasswordChar = false;
            this.bftxtSegundoApellido.WordWrap = true;
            // 
            // bftxtPrimerApellido
            // 
            this.bftxtPrimerApellido.AcceptsReturn = false;
            this.bftxtPrimerApellido.AcceptsTab = false;
            this.bftxtPrimerApellido.AnimationSpeed = 200;
            this.bftxtPrimerApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerApellido.AutoSizeHeight = true;
            this.bftxtPrimerApellido.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerApellido.BackgroundImage")));
            this.bftxtPrimerApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerApellido.BorderRadius = 1;
            this.bftxtPrimerApellido.BorderThickness = 1;
            this.bftxtPrimerApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellido.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerApellido.DefaultText = "";
            this.bftxtPrimerApellido.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerApellido.HideSelection = true;
            this.bftxtPrimerApellido.IconLeft = null;
            this.bftxtPrimerApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellido.IconPadding = 10;
            this.bftxtPrimerApellido.IconRight = null;
            this.bftxtPrimerApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerApellido.Lines = new string[0];
            this.bftxtPrimerApellido.Location = new System.Drawing.Point(126, 113);
            this.bftxtPrimerApellido.MaxLength = 32767;
            this.bftxtPrimerApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerApellido.Modified = false;
            this.bftxtPrimerApellido.Multiline = false;
            this.bftxtPrimerApellido.Name = "bftxtPrimerApellido";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellido.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerApellido.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellido.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerApellido.OnIdleState = stateProperties12;
            this.bftxtPrimerApellido.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerApellido.PasswordChar = '\0';
            this.bftxtPrimerApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerApellido.PlaceholderText = "Primer Apellido";
            this.bftxtPrimerApellido.ReadOnly = false;
            this.bftxtPrimerApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerApellido.SelectedText = "";
            this.bftxtPrimerApellido.SelectionLength = 0;
            this.bftxtPrimerApellido.SelectionStart = 0;
            this.bftxtPrimerApellido.ShortcutsEnabled = true;
            this.bftxtPrimerApellido.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerApellido.TabIndex = 34;
            this.bftxtPrimerApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerApellido.TextMarginBottom = 0;
            this.bftxtPrimerApellido.TextMarginLeft = 3;
            this.bftxtPrimerApellido.TextMarginTop = 1;
            this.bftxtPrimerApellido.TextPlaceholder = "Primer Apellido";
            this.bftxtPrimerApellido.UseSystemPasswordChar = false;
            this.bftxtPrimerApellido.WordWrap = true;
            // 
            // bftxtSegundoNombre
            // 
            this.bftxtSegundoNombre.AcceptsReturn = false;
            this.bftxtSegundoNombre.AcceptsTab = false;
            this.bftxtSegundoNombre.AnimationSpeed = 200;
            this.bftxtSegundoNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtSegundoNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtSegundoNombre.AutoSizeHeight = true;
            this.bftxtSegundoNombre.BackColor = System.Drawing.Color.Transparent;
            this.bftxtSegundoNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtSegundoNombre.BackgroundImage")));
            this.bftxtSegundoNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtSegundoNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtSegundoNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtSegundoNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtSegundoNombre.BorderRadius = 1;
            this.bftxtSegundoNombre.BorderThickness = 1;
            this.bftxtSegundoNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtSegundoNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombre.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtSegundoNombre.DefaultText = "";
            this.bftxtSegundoNombre.FillColor = System.Drawing.Color.White;
            this.bftxtSegundoNombre.HideSelection = true;
            this.bftxtSegundoNombre.IconLeft = null;
            this.bftxtSegundoNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombre.IconPadding = 10;
            this.bftxtSegundoNombre.IconRight = null;
            this.bftxtSegundoNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtSegundoNombre.Lines = new string[0];
            this.bftxtSegundoNombre.Location = new System.Drawing.Point(393, 56);
            this.bftxtSegundoNombre.MaxLength = 32767;
            this.bftxtSegundoNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtSegundoNombre.Modified = false;
            this.bftxtSegundoNombre.Multiline = false;
            this.bftxtSegundoNombre.Name = "bftxtSegundoNombre";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtSegundoNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtSegundoNombre.OnIdleState = stateProperties16;
            this.bftxtSegundoNombre.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtSegundoNombre.PasswordChar = '\0';
            this.bftxtSegundoNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtSegundoNombre.PlaceholderText = "Segundo nombre";
            this.bftxtSegundoNombre.ReadOnly = false;
            this.bftxtSegundoNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtSegundoNombre.SelectedText = "";
            this.bftxtSegundoNombre.SelectionLength = 0;
            this.bftxtSegundoNombre.SelectionStart = 0;
            this.bftxtSegundoNombre.ShortcutsEnabled = true;
            this.bftxtSegundoNombre.Size = new System.Drawing.Size(193, 37);
            this.bftxtSegundoNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtSegundoNombre.TabIndex = 33;
            this.bftxtSegundoNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtSegundoNombre.TextMarginBottom = 0;
            this.bftxtSegundoNombre.TextMarginLeft = 3;
            this.bftxtSegundoNombre.TextMarginTop = 1;
            this.bftxtSegundoNombre.TextPlaceholder = "Segundo nombre";
            this.bftxtSegundoNombre.UseSystemPasswordChar = false;
            this.bftxtSegundoNombre.WordWrap = true;
            // 
            // bftxtPrimerNombre
            // 
            this.bftxtPrimerNombre.AcceptsReturn = false;
            this.bftxtPrimerNombre.AcceptsTab = false;
            this.bftxtPrimerNombre.AnimationSpeed = 200;
            this.bftxtPrimerNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPrimerNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPrimerNombre.AutoSizeHeight = true;
            this.bftxtPrimerNombre.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPrimerNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPrimerNombre.BackgroundImage")));
            this.bftxtPrimerNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPrimerNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPrimerNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPrimerNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPrimerNombre.BorderRadius = 1;
            this.bftxtPrimerNombre.BorderThickness = 1;
            this.bftxtPrimerNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPrimerNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombre.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPrimerNombre.DefaultText = "";
            this.bftxtPrimerNombre.FillColor = System.Drawing.Color.White;
            this.bftxtPrimerNombre.HideSelection = true;
            this.bftxtPrimerNombre.IconLeft = null;
            this.bftxtPrimerNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombre.IconPadding = 10;
            this.bftxtPrimerNombre.IconRight = null;
            this.bftxtPrimerNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPrimerNombre.Lines = new string[0];
            this.bftxtPrimerNombre.Location = new System.Drawing.Point(126, 56);
            this.bftxtPrimerNombre.MaxLength = 32767;
            this.bftxtPrimerNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPrimerNombre.Modified = false;
            this.bftxtPrimerNombre.Multiline = false;
            this.bftxtPrimerNombre.Name = "bftxtPrimerNombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPrimerNombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPrimerNombre.OnIdleState = stateProperties20;
            this.bftxtPrimerNombre.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPrimerNombre.PasswordChar = '\0';
            this.bftxtPrimerNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPrimerNombre.PlaceholderText = "Primer nombre";
            this.bftxtPrimerNombre.ReadOnly = false;
            this.bftxtPrimerNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPrimerNombre.SelectedText = "";
            this.bftxtPrimerNombre.SelectionLength = 0;
            this.bftxtPrimerNombre.SelectionStart = 0;
            this.bftxtPrimerNombre.ShortcutsEnabled = true;
            this.bftxtPrimerNombre.Size = new System.Drawing.Size(193, 37);
            this.bftxtPrimerNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPrimerNombre.TabIndex = 32;
            this.bftxtPrimerNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPrimerNombre.TextMarginBottom = 0;
            this.bftxtPrimerNombre.TextMarginLeft = 3;
            this.bftxtPrimerNombre.TextMarginTop = 1;
            this.bftxtPrimerNombre.TextPlaceholder = "Primer nombre";
            this.bftxtPrimerNombre.UseSystemPasswordChar = false;
            this.bftxtPrimerNombre.WordWrap = true;
            this.bftxtPrimerNombre.TextChanged += new System.EventHandler(this.bftxtPrimerNombre_TextChanged);
            // 
            // bftgLogin
            // 
            this.bftgLogin.Controls.Add(this.bfbtnInfoFinish);
            this.bftgLogin.Controls.Add(this.bftxtConfirmPassword);
            this.bftgLogin.Controls.Add(this.bftxtPassword);
            this.bftgLogin.Controls.Add(this.bftxtConfirmarEmail);
            this.bftgLogin.Controls.Add(this.bftxtxEmail);
            this.bftgLogin.Location = new System.Drawing.Point(4, 4);
            this.bftgLogin.Name = "bftgLogin";
            this.bftgLogin.Padding = new System.Windows.Forms.Padding(3);
            this.bftgLogin.Size = new System.Drawing.Size(717, 386);
            this.bftgLogin.TabIndex = 2;
            this.bftgLogin.Text = "Login";
            this.bftgLogin.UseVisualStyleBackColor = true;
            // 
            // bfbtnInfoFinish
            // 
            this.bfbtnInfoFinish.AllowAnimations = true;
            this.bfbtnInfoFinish.AllowMouseEffects = true;
            this.bfbtnInfoFinish.AllowToggling = false;
            this.bfbtnInfoFinish.AnimationSpeed = 200;
            this.bfbtnInfoFinish.AutoGenerateColors = false;
            this.bfbtnInfoFinish.AutoRoundBorders = true;
            this.bfbtnInfoFinish.AutoSizeLeftIcon = true;
            this.bfbtnInfoFinish.AutoSizeRightIcon = true;
            this.bfbtnInfoFinish.BackColor = System.Drawing.Color.Transparent;
            this.bfbtnInfoFinish.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bfbtnInfoFinish.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bfbtnInfoFinish.BackgroundImage")));
            this.bfbtnInfoFinish.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnInfoFinish.ButtonText = "Finish";
            this.bfbtnInfoFinish.ButtonTextMarginLeft = 0;
            this.bfbtnInfoFinish.ColorContrastOnClick = 45;
            this.bfbtnInfoFinish.ColorContrastOnHover = 45;
            this.bfbtnInfoFinish.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bfbtnInfoFinish.CustomizableEdges = borderEdges2;
            this.bfbtnInfoFinish.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bfbtnInfoFinish.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnInfoFinish.DisabledFillColor = System.Drawing.Color.Empty;
            this.bfbtnInfoFinish.DisabledForecolor = System.Drawing.Color.Empty;
            this.bfbtnInfoFinish.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bfbtnInfoFinish.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bfbtnInfoFinish.ForeColor = System.Drawing.Color.White;
            this.bfbtnInfoFinish.IconLeft = null;
            this.bfbtnInfoFinish.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bfbtnInfoFinish.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnInfoFinish.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bfbtnInfoFinish.IconMarginLeft = 11;
            this.bfbtnInfoFinish.IconPadding = 10;
            this.bfbtnInfoFinish.IconRight = null;
            this.bfbtnInfoFinish.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bfbtnInfoFinish.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bfbtnInfoFinish.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bfbtnInfoFinish.IconSize = 25;
            this.bfbtnInfoFinish.IdleBorderColor = System.Drawing.Color.Empty;
            this.bfbtnInfoFinish.IdleBorderRadius = 0;
            this.bfbtnInfoFinish.IdleBorderThickness = 0;
            this.bfbtnInfoFinish.IdleFillColor = System.Drawing.Color.Empty;
            this.bfbtnInfoFinish.IdleIconLeftImage = null;
            this.bfbtnInfoFinish.IdleIconRightImage = null;
            this.bfbtnInfoFinish.IndicateFocus = false;
            this.bfbtnInfoFinish.Location = new System.Drawing.Point(554, 330);
            this.bfbtnInfoFinish.Margin = new System.Windows.Forms.Padding(4);
            this.bfbtnInfoFinish.Name = "bfbtnInfoFinish";
            this.bfbtnInfoFinish.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bfbtnInfoFinish.OnDisabledState.BorderRadius = 35;
            this.bfbtnInfoFinish.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnInfoFinish.OnDisabledState.BorderThickness = 1;
            this.bfbtnInfoFinish.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bfbtnInfoFinish.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bfbtnInfoFinish.OnDisabledState.IconLeftImage = null;
            this.bfbtnInfoFinish.OnDisabledState.IconRightImage = null;
            this.bfbtnInfoFinish.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bfbtnInfoFinish.onHoverState.BorderRadius = 35;
            this.bfbtnInfoFinish.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnInfoFinish.onHoverState.BorderThickness = 1;
            this.bfbtnInfoFinish.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bfbtnInfoFinish.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bfbtnInfoFinish.onHoverState.IconLeftImage = null;
            this.bfbtnInfoFinish.onHoverState.IconRightImage = null;
            this.bfbtnInfoFinish.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnInfoFinish.OnIdleState.BorderRadius = 35;
            this.bfbtnInfoFinish.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnInfoFinish.OnIdleState.BorderThickness = 1;
            this.bfbtnInfoFinish.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bfbtnInfoFinish.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bfbtnInfoFinish.OnIdleState.IconLeftImage = null;
            this.bfbtnInfoFinish.OnIdleState.IconRightImage = null;
            this.bfbtnInfoFinish.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnInfoFinish.OnPressedState.BorderRadius = 35;
            this.bfbtnInfoFinish.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bfbtnInfoFinish.OnPressedState.BorderThickness = 1;
            this.bfbtnInfoFinish.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bfbtnInfoFinish.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bfbtnInfoFinish.OnPressedState.IconLeftImage = null;
            this.bfbtnInfoFinish.OnPressedState.IconRightImage = null;
            this.bfbtnInfoFinish.Size = new System.Drawing.Size(156, 29);
            this.bfbtnInfoFinish.TabIndex = 40;
            this.bfbtnInfoFinish.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bfbtnInfoFinish.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bfbtnInfoFinish.TextMarginLeft = 0;
            this.bfbtnInfoFinish.TextPadding = new System.Windows.Forms.Padding(0);
            this.bfbtnInfoFinish.UseDefaultRadiusAndThickness = true;
            this.bfbtnInfoFinish.Click += new System.EventHandler(this.bfbtnInfoFinish_Click);
            // 
            // bftxtConfirmPassword
            // 
            this.bftxtConfirmPassword.AcceptsReturn = false;
            this.bftxtConfirmPassword.AcceptsTab = false;
            this.bftxtConfirmPassword.AnimationSpeed = 200;
            this.bftxtConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmPassword.AutoSizeHeight = true;
            this.bftxtConfirmPassword.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmPassword.BackgroundImage")));
            this.bftxtConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmPassword.BorderRadius = 1;
            this.bftxtConfirmPassword.BorderThickness = 1;
            this.bftxtConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmPassword.DefaultText = "";
            this.bftxtConfirmPassword.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmPassword.HideSelection = true;
            this.bftxtConfirmPassword.IconLeft = null;
            this.bftxtConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.IconPadding = 10;
            this.bftxtConfirmPassword.IconRight = null;
            this.bftxtConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmPassword.Lines = new string[0];
            this.bftxtConfirmPassword.Location = new System.Drawing.Point(403, 112);
            this.bftxtConfirmPassword.MaxLength = 32767;
            this.bftxtConfirmPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmPassword.Modified = false;
            this.bftxtConfirmPassword.Multiline = false;
            this.bftxtConfirmPassword.Name = "bftxtConfirmPassword";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmPassword.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmPassword.OnIdleState = stateProperties24;
            this.bftxtConfirmPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmPassword.PasswordChar = '\0';
            this.bftxtConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmPassword.PlaceholderText = "Confirmar Contraseña";
            this.bftxtConfirmPassword.ReadOnly = false;
            this.bftxtConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmPassword.SelectedText = "";
            this.bftxtConfirmPassword.SelectionLength = 0;
            this.bftxtConfirmPassword.SelectionStart = 0;
            this.bftxtConfirmPassword.ShortcutsEnabled = true;
            this.bftxtConfirmPassword.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmPassword.TabIndex = 30;
            this.bftxtConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmPassword.TextMarginBottom = 0;
            this.bftxtConfirmPassword.TextMarginLeft = 3;
            this.bftxtConfirmPassword.TextMarginTop = 1;
            this.bftxtConfirmPassword.TextPlaceholder = "Confirmar Contraseña";
            this.bftxtConfirmPassword.UseSystemPasswordChar = false;
            this.bftxtConfirmPassword.WordWrap = true;
            // 
            // bftxtPassword
            // 
            this.bftxtPassword.AcceptsReturn = false;
            this.bftxtPassword.AcceptsTab = false;
            this.bftxtPassword.AnimationSpeed = 200;
            this.bftxtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtPassword.AutoSizeHeight = true;
            this.bftxtPassword.BackColor = System.Drawing.Color.Transparent;
            this.bftxtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtPassword.BackgroundImage")));
            this.bftxtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtPassword.BorderRadius = 1;
            this.bftxtPassword.BorderThickness = 1;
            this.bftxtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtPassword.DefaultText = "";
            this.bftxtPassword.FillColor = System.Drawing.Color.White;
            this.bftxtPassword.HideSelection = true;
            this.bftxtPassword.IconLeft = null;
            this.bftxtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.IconPadding = 10;
            this.bftxtPassword.IconRight = null;
            this.bftxtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtPassword.Lines = new string[0];
            this.bftxtPassword.Location = new System.Drawing.Point(103, 112);
            this.bftxtPassword.MaxLength = 32767;
            this.bftxtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtPassword.Modified = false;
            this.bftxtPassword.Multiline = false;
            this.bftxtPassword.Name = "bftxtPassword";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtPassword.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtPassword.OnIdleState = stateProperties28;
            this.bftxtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtPassword.PasswordChar = '\0';
            this.bftxtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtPassword.PlaceholderText = "Contraseña";
            this.bftxtPassword.ReadOnly = false;
            this.bftxtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtPassword.SelectedText = "";
            this.bftxtPassword.SelectionLength = 0;
            this.bftxtPassword.SelectionStart = 0;
            this.bftxtPassword.ShortcutsEnabled = true;
            this.bftxtPassword.Size = new System.Drawing.Size(226, 37);
            this.bftxtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtPassword.TabIndex = 29;
            this.bftxtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtPassword.TextMarginBottom = 0;
            this.bftxtPassword.TextMarginLeft = 3;
            this.bftxtPassword.TextMarginTop = 1;
            this.bftxtPassword.TextPlaceholder = "Contraseña";
            this.bftxtPassword.UseSystemPasswordChar = false;
            this.bftxtPassword.WordWrap = true;
            // 
            // bftxtConfirmarEmail
            // 
            this.bftxtConfirmarEmail.AcceptsReturn = false;
            this.bftxtConfirmarEmail.AcceptsTab = false;
            this.bftxtConfirmarEmail.AnimationSpeed = 200;
            this.bftxtConfirmarEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtConfirmarEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtConfirmarEmail.AutoSizeHeight = true;
            this.bftxtConfirmarEmail.BackColor = System.Drawing.Color.Transparent;
            this.bftxtConfirmarEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtConfirmarEmail.BackgroundImage")));
            this.bftxtConfirmarEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtConfirmarEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtConfirmarEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtConfirmarEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmail.BorderRadius = 1;
            this.bftxtConfirmarEmail.BorderThickness = 1;
            this.bftxtConfirmarEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtConfirmarEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmail.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtConfirmarEmail.DefaultText = "";
            this.bftxtConfirmarEmail.FillColor = System.Drawing.Color.White;
            this.bftxtConfirmarEmail.HideSelection = true;
            this.bftxtConfirmarEmail.IconLeft = null;
            this.bftxtConfirmarEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmail.IconPadding = 10;
            this.bftxtConfirmarEmail.IconRight = null;
            this.bftxtConfirmarEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtConfirmarEmail.Lines = new string[0];
            this.bftxtConfirmarEmail.Location = new System.Drawing.Point(403, 49);
            this.bftxtConfirmarEmail.MaxLength = 32767;
            this.bftxtConfirmarEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtConfirmarEmail.Modified = false;
            this.bftxtConfirmarEmail.Multiline = false;
            this.bftxtConfirmarEmail.Name = "bftxtConfirmarEmail";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmail.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtConfirmarEmail.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmail.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtConfirmarEmail.OnIdleState = stateProperties32;
            this.bftxtConfirmarEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtConfirmarEmail.PasswordChar = '\0';
            this.bftxtConfirmarEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtConfirmarEmail.PlaceholderText = "Confirme e-mail";
            this.bftxtConfirmarEmail.ReadOnly = false;
            this.bftxtConfirmarEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtConfirmarEmail.SelectedText = "";
            this.bftxtConfirmarEmail.SelectionLength = 0;
            this.bftxtConfirmarEmail.SelectionStart = 0;
            this.bftxtConfirmarEmail.ShortcutsEnabled = true;
            this.bftxtConfirmarEmail.Size = new System.Drawing.Size(208, 37);
            this.bftxtConfirmarEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtConfirmarEmail.TabIndex = 26;
            this.bftxtConfirmarEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtConfirmarEmail.TextMarginBottom = 0;
            this.bftxtConfirmarEmail.TextMarginLeft = 3;
            this.bftxtConfirmarEmail.TextMarginTop = 1;
            this.bftxtConfirmarEmail.TextPlaceholder = "Confirme e-mail";
            this.bftxtConfirmarEmail.UseSystemPasswordChar = false;
            this.bftxtConfirmarEmail.WordWrap = true;
            // 
            // bftxtxEmail
            // 
            this.bftxtxEmail.AcceptsReturn = false;
            this.bftxtxEmail.AcceptsTab = false;
            this.bftxtxEmail.AnimationSpeed = 200;
            this.bftxtxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bftxtxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bftxtxEmail.AutoSizeHeight = true;
            this.bftxtxEmail.BackColor = System.Drawing.Color.Transparent;
            this.bftxtxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bftxtxEmail.BackgroundImage")));
            this.bftxtxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bftxtxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bftxtxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bftxtxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bftxtxEmail.BorderRadius = 1;
            this.bftxtxEmail.BorderThickness = 1;
            this.bftxtxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bftxtxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bftxtxEmail.DefaultText = "";
            this.bftxtxEmail.FillColor = System.Drawing.Color.White;
            this.bftxtxEmail.HideSelection = true;
            this.bftxtxEmail.IconLeft = null;
            this.bftxtxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.IconPadding = 10;
            this.bftxtxEmail.IconRight = null;
            this.bftxtxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bftxtxEmail.Lines = new string[0];
            this.bftxtxEmail.Location = new System.Drawing.Point(103, 49);
            this.bftxtxEmail.MaxLength = 32767;
            this.bftxtxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bftxtxEmail.Modified = false;
            this.bftxtxEmail.Multiline = false;
            this.bftxtxEmail.Name = "bftxtxEmail";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bftxtxEmail.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bftxtxEmail.OnIdleState = stateProperties36;
            this.bftxtxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bftxtxEmail.PasswordChar = '\0';
            this.bftxtxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bftxtxEmail.PlaceholderText = "E-mail";
            this.bftxtxEmail.ReadOnly = false;
            this.bftxtxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bftxtxEmail.SelectedText = "";
            this.bftxtxEmail.SelectionLength = 0;
            this.bftxtxEmail.SelectionStart = 0;
            this.bftxtxEmail.ShortcutsEnabled = true;
            this.bftxtxEmail.Size = new System.Drawing.Size(226, 37);
            this.bftxtxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bftxtxEmail.TabIndex = 25;
            this.bftxtxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bftxtxEmail.TextMarginBottom = 0;
            this.bftxtxEmail.TextMarginLeft = 3;
            this.bftxtxEmail.TextMarginTop = 1;
            this.bftxtxEmail.TextPlaceholder = "E-mail";
            this.bftxtxEmail.UseSystemPasswordChar = false;
            this.bftxtxEmail.WordWrap = true;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // frmRegisterClient
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(54)))), ((int)(((byte)(66)))));
            this.ClientSize = new System.Drawing.Size(863, 510);
            this.Controls.Add(this.bfpgPersonInfo);
            this.Controls.Add(this.ptbCrearCuentaCerrar);
            this.Controls.Add(this.ptbCrearCuentaMinimizar);
            this.Controls.Add(this.bflblCreateAccount2);
            this.Controls.Add(this.bflblCreateAccount1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRegisterClient";
            this.Text = "frmRegister";
            this.Load += new System.EventHandler(this.frmRegister_Load);
            ((System.ComponentModel.ISupportInitialize)(this.ptbCrearCuentaMinimizar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptbCrearCuentaCerrar)).EndInit();
            this.bfpgPersonInfo.ResumeLayout(false);
            this.bftpInfoPersonal.ResumeLayout(false);
            this.bftpInfoPersonal.PerformLayout();
            this.bftgLogin.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bflblCreateAccount1;
        private Bunifu.UI.WinForms.BunifuLabel bflblCreateAccount2;
        private System.Windows.Forms.PictureBox ptbCrearCuentaMinimizar;
        private System.Windows.Forms.PictureBox ptbCrearCuentaCerrar;
        private Bunifu.UI.WinForms.BunifuPages bfpgPersonInfo;
        private System.Windows.Forms.TabPage bftpInfoPersonal;
        private System.Windows.Forms.ComboBox cmbGenero;
        private Bunifu.UI.WinForms.BunifuLabel bflblGenero;
        private Bunifu.UI.WinForms.BunifuLabel bflblFechaNacimiento;
        private Bunifu.UI.WinForms.BunifuDatePicker bfdpkFechaNacimiento;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtDocumento;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoApellido;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerApellido;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtSegundoNombre;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPrimerNombre;
        private System.Windows.Forms.TabPage bftgLogin;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmPassword;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtConfirmarEmail;
        private Bunifu.UI.WinForms.BunifuTextBox bftxtxEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bfbtnInfoFinish;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bfbtnRegisterNext;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.Label lblDatosPersonales;
        private Bunifu.UI.WinForms.BunifuLabel bflblDepartamento;
        private System.Windows.Forms.ComboBox cmbDepartamento;
        private System.Windows.Forms.ComboBox cmbCiudad;
        private Bunifu.UI.WinForms.BunifuLabel lblCiudad;
    }
}